// Curated learning courses with verified YouTube tutorials, curriculum modules, and study notes
export const coursesData = [
  {
    title: 'Zero to Autonomous AI Agent Architect',
    description: 'Master LangGraph, CrewAI, AutoGen, and tool calling to build reliable multi-agent systems that solve complex workflows autonomously.',
    category: 'AI Coding',
    level: 'Intermediate',
    duration: '5.5 hours',
    instructor: 'Alex Rivera (Nexus AI Systems)',
    rating: 4.96,
    studentsCount: 4820,
    icon: 'Cpu',
    overviewVideoId: 'sal78ACtGTc',
    modules: [
      {
        title: 'Foundations of Agentic Loops & ReAct Architecture',
        duration: '45m',
        summary: 'Understand the Reason-and-Act (ReAct) paradigm, feedback loops, and how agents differ from linear LLM prompts.',
        youtubeUrl: 'https://www.youtube.com/watch?v=sal78ACtGTc',
        videoId: 'sal78ACtGTc',
        channelTitle: 'freeCodeCamp.org',
        videoTitle: 'AI Agents Tutorial – Build Autonomous Multi-Agent Systems',
        objectives: [
          'Understand the Reason-and-Act (ReAct) paradigm',
          'Compare Single-Agent vs Multi-Agent architectures',
          'Learn state management in cyclic execution loops',
        ],
        notes: 'Agentic workflows differ fundamentally from zero-shot prompt pipelines because they run in non-deterministic reflection loops with tool-calling capabilities.',
        resources: [
          { title: 'ReAct Paper (Yao et al.)', url: 'https://arxiv.org/abs/2210.03629' },
          { title: 'LangChain Agents Guide', url: 'https://python.langchain.com/docs/concepts/agents/' },
        ],
      },
      {
        title: 'Tool Calling & Function Orchestration',
        duration: '1h 15m',
        summary: 'Connect frontier models to external APIs, databases, and custom Python execution sandboxes using Pydantic schemas.',
        youtubeUrl: 'https://www.youtube.com/watch?v=0k_2uX7l-t4',
        videoId: '0k_2uX7l-t4',
        channelTitle: 'LangChain',
        videoTitle: 'Tool Calling and Function Execution with LLMs',
        objectives: [
          'Implement schema validation with Pydantic',
          'Safely bind external REST APIs to models',
          'Handle execution exceptions and retry logic',
        ],
        notes: 'Structured JSON outputs ensure frontier models adhere to strictly typed arguments before invoking external functions.',
        resources: [
          { title: 'OpenAI Function Calling Docs', url: 'https://platform.openai.com/docs/guides/function-calling' },
          { title: 'Pydantic Documentation', url: 'https://docs.pydantic.dev/' },
        ],
      },
      {
        title: 'State Graphs & Memory Persistence with LangGraph',
        duration: '1h 30m',
        summary: 'Architect cyclic multi-agent state machines with persistence, time-travel debugging, and human-in-the-loop safeguards.',
        youtubeUrl: 'https://www.youtube.com/watch?v=R8KB-Zcynxc',
        videoId: 'R8KB-Zcynxc',
        channelTitle: 'IBM Technology',
        videoTitle: 'What is LangGraph? Build Stateful AI Workflows',
        objectives: [
          'Construct cyclic state machines using nodes and edges',
          'Implement checkpointing for conversation persistence',
          'Integrate human-in-the-loop approval breakpoints',
        ],
        notes: 'LangGraph introduces cyclic graphs that allow agents to step back, critique their previous actions, and self-correct.',
        resources: [
          { title: 'LangGraph Official Docs', url: 'https://langchain-ai.github.io/langgraph/' },
          { title: 'LangGraph Studio Overview', url: 'https://github.com/langchain-ai/langgraph-studio' },
        ],
      },
      {
        title: 'Production Multi-Agent Swarms with CrewAI',
        duration: '2h',
        summary: 'Deploy specialized role-playing agent crews with hierarchical delegation, memory systems, and observability tracing.',
        youtubeUrl: 'https://www.youtube.com/watch?v=tnejrr-0a94',
        videoId: 'tnejrr-0a94',
        channelTitle: 'freeCodeCamp.org',
        videoTitle: 'CrewAI Full Course – Multi-Agent AI System Design',
        objectives: [
          'Define specialized role-playing agents',
          'Configure sequential and hierarchical delegation',
          'Deploy production agents with monitoring and tracing',
        ],
        notes: 'Assigning explicit personas, backstories, and goals significantly reduces cognitive drift in multi-agent orchestration.',
        resources: [
          { title: 'CrewAI Documentation', url: 'https://docs.crewai.com/' },
          { title: 'Langfuse Tracing Integration', url: 'https://langfuse.com/docs/integrations/crewai' },
        ],
      },
    ],
  },
  {
    title: 'Mastering Cinematic AI Filmmaking & Motion',
    description: 'From Midjourney v7 storyboard prompts to Runway Gen-3 motion control, Kling AI physical simulation, and ElevenLabs voice acting.',
    category: 'Video Creation',
    level: 'Beginner',
    duration: '4.5 hours',
    instructor: 'Elena Rostova (Creative Director)',
    rating: 4.92,
    studentsCount: 3640,
    icon: 'Film',
    overviewVideoId: 'b4wH9gN08Q8',
    modules: [
      {
        title: 'Visual Consistency & Prompting in Midjourney v7',
        duration: '1h',
        summary: 'Master style references (--sref), character references (--cref), and lighting parameters to produce coherent scene storyboards.',
        youtubeUrl: 'https://www.youtube.com/watch?v=oE_4d_j1yZ4',
        videoId: 'oE_4d_j1yZ4',
        channelTitle: 'Matt Wolfe',
        videoTitle: 'Midjourney Masterclass – Complete Image Generation Guide',
        objectives: [
          'Master style references (--sref) and character references (--cref)',
          'Achieve cinematic lighting and photorealistic camera angles',
          'Optimize aspect ratios and multi-prompt weights',
        ],
        notes: 'Locking seed values and character references maintains visual continuity between scene storyboards across an entire short film.',
        resources: [
          { title: 'Midjourney Prompt Documentation', url: 'https://docs.midjourney.com/' },
        ],
      },
      {
        title: 'Camera Motion Directing in Runway Gen-3 Alpha',
        duration: '1h 15m',
        summary: 'Command precise camera choreography including tilts, dollies, zooms, and motion brush velocity control.',
        youtubeUrl: 'https://www.youtube.com/watch?v=b4wH9gN08Q8',
        videoId: 'b4wH9gN08Q8',
        channelTitle: 'Runway',
        videoTitle: 'Gen-3 Alpha Tutorial – Advanced Camera & Motion Controls',
        objectives: [
          'Command precise pan, tilt, zoom, and dolly camera choreography',
          'Apply motion brushes for selective scene animation',
          'Control temporal coherence across video extensions',
        ],
        notes: 'Use cinematic descriptive language rather than generic tags when prompting video models.',
        resources: [
          { title: 'Runway Gen-3 Prompt Guide', url: 'https://help.runwayml.com/hc/en-us/articles/30588647029523' },
        ],
      },
      {
        title: 'Photorealistic Physics & High-Definition Video with Kling AI',
        duration: '1h',
        summary: 'Harness 1080p generation with natural physics simulation, human gait mechanics, and dynamic camera transitions.',
        youtubeUrl: 'https://www.youtube.com/watch?v=9_N3eF1gU2o',
        videoId: '9_N3eF1gU2o',
        channelTitle: 'Curious Refuge',
        videoTitle: 'Kling AI Video Generation Tutorial & Masterclass',
        objectives: [
          'Harness 1080p generation with natural physics simulation',
          'Execute realistic character movements and expressions',
          'Blend multiple generated clips seamlessly',
        ],
        notes: 'Kling excels at complex fluid dynamics, human walking motion, and long temporal continuity.',
        resources: [
          { title: 'Kling AI Official Site', url: 'https://klingai.com' },
        ],
      },
      {
        title: 'Sound Design, Voice Acting & Audio Mastering with ElevenLabs',
        duration: '1h 15m',
        summary: 'Generate cloned character dialog, emotional cadence, foley sound effects, and master output to 4K.',
        youtubeUrl: 'https://www.youtube.com/watch?v=XNl6Q_tF-tM',
        videoId: 'XNl6Q_tF-tM',
        channelTitle: 'ElevenLabs',
        videoTitle: 'AI Voice Cloning & Sound Effects Studio Masterclass',
        objectives: [
          'Clone and direct expressive emotional voice acting',
          'Generate realistic atmospheric sound effects and foley audio',
          'Upscale to 4K and master audio in modern editing suites',
        ],
        notes: 'Multi-track audio with subtle ambient background noise significantly heightens the perceived realism of AI video.',
        resources: [
          { title: 'ElevenLabs Voice Design', url: 'https://elevenlabs.io/voice-generator' },
        ],
      },
    ],
  },
  {
    title: 'Full-Stack Generative UI with React, v0 & Bolt.new',
    description: 'Harness frontier AI to design, prototype, and build responsive production apps in record time without repetitive boilerplate.',
    category: 'AI Web Building',
    level: 'Intermediate',
    duration: '4 hours',
    instructor: 'Sarah Chen (Full-Stack Architect)',
    rating: 4.94,
    studentsCount: 5120,
    icon: 'Layers',
    overviewVideoId: '7X8vZz0H7N8',
    modules: [
      {
        title: 'Prompting for Modern UI Systems with v0 & Tailwind',
        duration: '45m',
        summary: 'Turn natural language component specs and screenshots into production-ready React components with Lucide icons.',
        youtubeUrl: 'https://www.youtube.com/watch?v=7X8vZz0H7N8',
        videoId: '7X8vZz0H7N8',
        channelTitle: 'Vercel',
        videoTitle: 'Building with v0 by Vercel – Next.js & Tailwind Generative UI',
        objectives: [
          'Turn natural language design briefs into responsive React components',
          'Use image and screenshot inputs for high-fidelity code cloning',
          'Export clean JSX with Lucide icons and Tailwind styling',
        ],
        notes: 'Break complex UI screens into modular components when prompting generative UI engines.',
        resources: [
          { title: 'v0 by Vercel Documentation', url: 'https://v0.dev/docs' },
          { title: 'Tailwind CSS Docs', url: 'https://tailwindcss.com/docs' },
        ],
      },
      {
        title: 'Instant Full-Stack Prototyping with Bolt.new',
        duration: '1h',
        summary: 'Leverage WebContainers to generate, install npm dependencies, and preview full-stack Node/Vite applications in the browser.',
        youtubeUrl: 'https://www.youtube.com/watch?v=U0k9eEwH01c',
        videoId: 'U0k9eEwH01c',
        channelTitle: 'StackBlitz',
        videoTitle: 'Bolt.new Full-Stack AI Development in the Browser',
        objectives: [
          'Harness in-browser WebContainers to install npm packages and backends',
          'Coordinate frontend, database, and API logic from a single prompt',
          'Iterate and live-preview full web applications in real-time',
        ],
        notes: 'Bolt.new runs a complete Node.js environment in WebAssembly directly inside your browser tab.',
        resources: [
          { title: 'Bolt.new Platform', url: 'https://bolt.new' },
        ],
      },
      {
        title: 'Autonomous App Engineering with Lovable & Supabase',
        duration: '1h',
        summary: 'Generate relational PostgreSQL schemas, secure auth policies, and sync code with GitHub repositories.',
        youtubeUrl: 'https://www.youtube.com/watch?v=Vz8D8qM02y4',
        videoId: 'Vz8D8qM02y4',
        channelTitle: 'Fireship',
        videoTitle: 'Lovable AI – Full Stack Web Apps in Minutes',
        objectives: [
          'Generate relational PostgreSQL schemas and auth rules',
          'Connect Supabase backends for real-time data sync',
          'Sync code to GitHub repositories and deploy to production',
        ],
        notes: 'Declarative database schema specifications prevent schema migration conflicts during rapid iterations.',
        resources: [
          { title: 'Lovable Documentation', url: 'https://docs.lovable.dev' },
        ],
      },
      {
        title: 'Micro-Animations, Glassmorphism & Cyber Aesthetics',
        duration: '1h 15m',
        summary: 'Inject physics, neon glows, glassmorphism overlays, and micro-interactions that make applications feel alive.',
        youtubeUrl: 'https://www.youtube.com/watch?v=dU7ZwJ4lc2k',
        videoId: 'dU7ZwJ4lc2k',
        channelTitle: 'Web Dev Simplified',
        videoTitle: 'Modern CSS Animations, Glassmorphism & Micro-Interactions',
        objectives: [
          'Apply futuristic glowing borders, blurs, and hover transformations',
          'Create interactive physics and micro-animations',
          'Ensure mobile responsiveness and accessibility',
        ],
        notes: 'Subtle box-shadow glows and cubic-bezier easing deliver a rich futuristic user experience.',
        resources: [
          { title: 'Glassmorphism Generator', url: 'https://glassmorphism.com/' },
        ],
      },
    ],
  },
  {
    title: 'Frontier AI Code Engineering: Cursor, Copilot & Claude Code',
    description: 'Transform your daily development workflow with deep codebase semantic indexing, multi-file agent edits, and autonomous terminal agents.',
    category: 'AI Coding',
    level: 'Intermediate',
    duration: '4.5 hours',
    instructor: 'Marcus Vance (Principal AI Engineer)',
    rating: 4.95,
    studentsCount: 6200,
    icon: 'Code2',
    overviewVideoId: 'yk9lXobJ97E',
    modules: [
      {
        title: 'Cursor AI Complete Mastery: Indexing & Multi-File Editing',
        duration: '50m',
        summary: 'Harness Cursor semantic indexing, Composer multi-file editing, and codebase context tags (@file, @folder, @docs).',
        youtubeUrl: 'https://www.youtube.com/watch?v=yk9lXobJ97E',
        videoId: 'yk9lXobJ97E',
        channelTitle: 'Fireship',
        videoTitle: 'Cursor AI Tutorial – 10x Your Coding Speed',
        objectives: [
          'Enable full-codebase semantic indexing with embeddings',
          'Use Composer for coordinated multi-file edits across the repo',
          'Master terminal command prediction and AI tab auto-complete',
        ],
        notes: 'Referencing files with @file and symbols with @symbol grounds Cursor in exact context without prompt pollution.',
        resources: [
          { title: 'Cursor Official Guide', url: 'https://docs.cursor.com/' },
        ],
      },
      {
        title: 'GitHub Copilot Chat & Workspace Deep Dive',
        duration: '1h',
        summary: 'Leverage inline suggestions, Copilot Workspace pull request generators, and slash commands (/fix, /tests).',
        youtubeUrl: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
        videoId: 'Fi3AJZZregE',
        channelTitle: 'GitHub',
        videoTitle: 'GitHub Copilot in VS Code – The Complete Beginner to Pro Guide',
        objectives: [
          'Use slash commands (/explain, /fix, /tests) effectively',
          'Automate unit test generation and documentation',
          'Leverage pull request summaries and code review assistance',
        ],
        notes: 'Copilot utilizes open tabs and project structure to synthesize contextual suggestions.',
        resources: [
          { title: 'GitHub Copilot Documentation', url: 'https://docs.github.com/en/copilot' },
        ],
      },
      {
        title: 'Autonomous Terminal Engineering with Claude Code',
        duration: '1h 10m',
        summary: 'Operate Claude Code agent directly in your CLI to inspect repositories, execute tests, refactor files, and commit git diffs.',
        youtubeUrl: 'https://www.youtube.com/watch?v=b4wH9gN08Q8',
        videoId: 'b4wH9gN08Q8',
        channelTitle: 'Anthropic',
        videoTitle: 'Claude Code – Autonomous CLI Coding Assistant',
        objectives: [
          'Execute terminal commands, run tests, and debug errors autonomously',
          'Navigate large monorepos with long-context reasoning',
          'Integrate Git commits and pull requests from the command line',
        ],
        notes: 'Terminal-based agents can run linters and test suites to self-verify code correctness before finishing.',
        resources: [
          { title: 'Anthropic Claude Code Docs', url: 'https://claude.ai/code' },
        ],
      },
      {
        title: 'Autonomous Bug Fixing & AI Code Reviews with CodeRabbit',
        duration: '1h 30m',
        summary: 'Set up automated line-by-line pull request reviews, regression detectors, and automated test runners.',
        youtubeUrl: 'https://www.youtube.com/watch?v=J_Q_xVj_kL0',
        videoId: 'J_Q_xVj_kL0',
        channelTitle: 'freeCodeCamp.org',
        videoTitle: 'Automated Code Reviews with AI – CodeRabbit & CI/CD',
        objectives: [
          'Configure AI PR review pipelines in GitHub Actions',
          'Catch security vulnerabilities and performance bottlenecks',
          'Implement automated regression test suites',
        ],
        notes: 'Line-by-line automated reviews drastically reduce code review fatigue on software engineering teams.',
        resources: [
          { title: 'CodeRabbit Guide', url: 'https://coderabbit.ai' },
        ],
      },
    ],
  },
  {
    title: 'AI Workflow Automation with n8n, Make & Autonomous Webhooks',
    description: 'Build enterprise-grade automated pipelines combining visual nodes, autonomous webhooks, vector databases, and multi-app orchestration.',
    category: 'Automation & Agents',
    level: 'Beginner',
    duration: '4 hours',
    instructor: 'Nathan Drake (Automation Specialist)',
    rating: 4.88,
    studentsCount: 3950,
    icon: 'Bot',
    overviewVideoId: 'D_9kU5p9rL8',
    modules: [
      {
        title: 'Visual Workflow Architecture & Node Triggers in n8n',
        duration: '50m',
        summary: 'Understand webhook triggers, data mapping, and self-hosted workflow automation with n8n.',
        youtubeUrl: 'https://www.youtube.com/watch?v=D_9kU5p9rL8',
        videoId: 'D_9kU5p9rL8',
        channelTitle: 'n8n',
        videoTitle: 'n8n Beginner Course – Complete Workflow Automation Guide',
        objectives: [
          'Understand webhook triggers and JSON data flow',
          'Transform and map payload data with JavaScript/Python',
          'Schedule recurring cron jobs and API webhooks',
        ],
        notes: 'n8n fair-code platform can be self-hosted on your own infrastructure for total privacy.',
        resources: [
          { title: 'n8n Self-Hosting Guide', url: 'https://docs.n8n.io/hosting/' },
        ],
      },
      {
        title: 'Building Self-Hosted Autonomous AI Agents in n8n',
        duration: '1h 15m',
        summary: 'Connect LLM nodes, memory buffers, and custom tool nodes to create conversational customer research bots.',
        youtubeUrl: 'https://www.youtube.com/watch?v=N5t_V4F_tK0',
        videoId: 'N5t_V4F_tK0',
        channelTitle: 'freeCodeCamp.org',
        videoTitle: 'Build AI Agents with n8n – Step-by-Step No-Code Tutorial',
        objectives: [
          'Connect OpenAI, Anthropic, and Ollama model nodes',
          'Equip agents with custom tools and memory buffers',
          'Automate multi-step research and database entry',
        ],
        notes: 'AI Agent nodes in n8n can call any other node in your canvas as a dynamic tool.',
        resources: [
          { title: 'n8n AI Agent Nodes', url: 'https://docs.n8n.io/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.agent/' },
        ],
      },
      {
        title: 'Multi-App Business Automations in Make.com',
        duration: '1h',
        summary: 'Build complex multi-step scenarios connecting CRMs, Slack, Google Workspace, and AI enrichments.',
        youtubeUrl: 'https://www.youtube.com/watch?v=8X1k_yQ9vG0',
        videoId: '8X1k_yQ9vG0',
        channelTitle: 'Make',
        videoTitle: 'Make.com Masterclass – Automate Your Business with AI',
        objectives: [
          'Construct branching scenarios with filters and routers',
          'Parse dynamic JSON from CRM, Slack, and email APIs',
          'Handle rate limits, error fallbacks, and retry queues',
        ],
        notes: 'Make visual data router lets you run conditional actions across thousands of apps.',
        resources: [
          { title: 'Make Academy', url: 'https://academy.make.com/' },
        ],
      },
      {
        title: 'Vector Database Sync & Real-Time RAG Pipelines',
        duration: '55m',
        summary: 'Embed documents on upload, sync vector representations, and deliver citation-grounded outputs.',
        youtubeUrl: 'https://www.youtube.com/watch?v=kY3hA6c6hK0',
        videoId: 'kY3hA6c6hK0',
        channelTitle: 'IBM Technology',
        videoTitle: 'What is Retrieval-Augmented Generation (RAG)?',
        objectives: [
          'Embed document chunks using text-embedding-3',
          'Store and query vectors in Pinecone, Qdrant, or Supabase',
          'Deliver verified cited responses grounded in company data',
        ],
        notes: 'Semantic chunking preserves conceptual boundaries better than arbitrary character counts.',
        resources: [
          { title: 'Pinecone Vector DB Guide', url: 'https://docs.pinecone.io/' },
        ],
      },
    ],
  },
  {
    title: 'AI Research & Synthesis with Perplexity & NotebookLM',
    description: 'Master live web citations, source-grounded notes, and multi-document synthesis for academic and market research.',
    category: 'Research & Search',
    level: 'All Levels',
    duration: '3.5 hours',
    instructor: 'Dr. Evelyn Reed (Research Fellow)',
    rating: 4.93,
    studentsCount: 4290,
    icon: 'Search',
    overviewVideoId: 'Z_k_9q_tN0o',
    modules: [
      {
        title: 'Perplexity AI Deep Research & Live Web Grounding',
        duration: '45m',
        summary: 'Run multi-step Pro Search queries, organize research into collections, and extract structured data tables.',
        youtubeUrl: 'https://www.youtube.com/watch?v=Z_k_9q_tN0o',
        videoId: 'Z_k_9q_tN0o',
        channelTitle: 'Perplexity AI',
        videoTitle: 'How to Use Perplexity AI for Deep Research and Citations',
        objectives: [
          'Master Pro Search multi-step reasoning queries',
          'Build curated research collections with custom prompts',
          'Verify source citations and extract tabular data',
        ],
        notes: 'Pro Search runs iterative queries against the live web to synthesize multifaceted answers with direct clickable citations.',
        resources: [
          { title: 'Perplexity Pro Guide', url: 'https://www.perplexity.ai/hub/getting-started' },
        ],
      },
      {
        title: 'Source Grounding & Audio Overview Podcasts with NotebookLM',
        duration: '50m',
        summary: 'Upload multi-format research sources and generate Audio Overview conversational podcasts grounded strictly in your docs.',
        youtubeUrl: 'https://www.youtube.com/watch?v=L_6vE_8_wP0',
        videoId: 'L_6vE_8_wP0',
        channelTitle: 'Google Labs',
        videoTitle: 'Google NotebookLM Tutorial – Audio Overview & Source Grounding',
        objectives: [
          'Upload multi-format research sources (PDFs, docs, YouTube URLs)',
          'Generate Audio Overview AI podcast deep dives',
          'Ground answers strictly within uploaded source materials',
        ],
        notes: 'NotebookLM eliminates hallucinations by restricting answers strictly to your provided sources.',
        resources: [
          { title: 'NotebookLM Official Portal', url: 'https://notebooklm.google.com' },
        ],
      },
      {
        title: 'Systematic Literature Reviews with Elicit & Consensus',
        duration: '55m',
        summary: 'Search across 200M+ research papers, extract methodological tables, and evaluate scientific consensus.',
        youtubeUrl: 'https://www.youtube.com/watch?v=G_7k_8q_tX0',
        videoId: 'G_7k_8q_tX0',
        channelTitle: 'SciSpace',
        videoTitle: 'How to Use AI for Academic Research & Literature Reviews',
        objectives: [
          'Search across 200M+ peer-reviewed scientific papers',
          'Extract structured methodology and sample size tables',
          'Gauge scientific consensus with the Consensus Meter',
        ],
        notes: 'Academic search engines index peer-reviewed databases rather than general web SEO pages.',
        resources: [
          { title: 'Elicit Research Platform', url: 'https://elicit.com' },
        ],
      },
      {
        title: 'Visual Knowledge Graph Mapping with ResearchRabbit',
        duration: '1h',
        summary: 'Map interconnected citation networks, discover related authors, and export references to Zotero.',
        youtubeUrl: 'https://www.youtube.com/watch?v=H_5n_2w_kY0',
        videoId: 'H_5n_2w_kY0',
        channelTitle: 'Tiago Forte',
        videoTitle: 'Building a Second Brain with AI & Visual Knowledge Graphs',
        objectives: [
          'Visualize citation networks and co-authorship graphs',
          'Discover prior and derivative works chronologically',
          'Export structured citations to Zotero and Obsidian',
        ],
        notes: 'Visual citation graphs reveal hidden research clusters that text searches often miss.',
        resources: [
          { title: 'ResearchRabbit App', url: 'https://www.researchrabbit.ai/' },
        ],
      },
    ],
  },
  {
    title: 'Mastering AI Image Generation: Midjourney & Leonardo AI',
    description: 'Master photorealistic prompt engineering, style references (--sref), character consistency, and custom LoRA models in Midjourney and Leonardo AI.',
    category: 'AI Image Generation',
    level: 'All Levels',
    duration: '4.5 hours',
    instructor: 'Elena Rostova (Visual Synthesis Director)',
    rating: 4.95,
    studentsCount: 3940,
    icon: 'Sparkles',
    overviewVideoId: 'kCc8FmEb1nY',
    modules: [
      {
        title: 'Midjourney v6 Prompt Engineering & Camera Optics',
        duration: '1h 10m',
        summary: 'Control focal length, lighting setups (chiaroscuro, volumetric), aspect ratios, and color grading for ultra-realistic renders.',
        youtubeUrl: 'https://www.youtube.com/watch?v=kCc8FmEb1nY',
        videoId: 'kCc8FmEb1nY',
        channelTitle: 'Christian Heidorn',
        videoTitle: 'Midjourney v6 Complete Beginner to Advanced Masterclass',
        objectives: [
          'Understand prompting syntax, weights, and negative prompts (--no)',
          'Simulate real camera lenses (35mm, 85mm f/1.4, macro optics)',
          'Utilize style reference codes (--sref) for uniform aesthetics',
        ],
        notes: 'Midjourney v6 responds best to direct natural language descriptions rather than endless comma-separated hype keywords.',
        resources: [
          { title: 'Midjourney Official Documentation', url: 'https://docs.midjourney.com' },
          { title: 'Camera Lenses Guide for AI Prompting', url: 'https://midlibrary.io' },
        ],
      },
      {
        title: 'Character Consistency & Style Reference Workflows',
        duration: '1h 05m',
        summary: 'Create persistent characters across multiple scenes using the --cref parameter and image weight blending.',
        youtubeUrl: 'https://www.youtube.com/watch?v=9pNz_FqTzC4',
        videoId: '9pNz_FqTzC4',
        channelTitle: 'Matt Wolfe',
        videoTitle: 'Midjourney Character Consistency & Seed Control Guide',
        objectives: [
          'Lock character faces and clothing using --cref and --cw tags',
          'Use seed parameters for incremental scene variations',
          'Blend multiple style reference URLs for custom hybrid styles',
        ],
        notes: 'Combining --cref with subtle lighting changes allows storytelling and commercial comic/novel development.',
        resources: [
          { title: 'Midjourney Parameter List', url: 'https://docs.midjourney.com/docs/parameter-list' },
        ],
      },
      {
        title: 'Leonardo AI: Real-Time Canvas & Custom LoRA Training',
        duration: '1h 15m',
        summary: 'Train custom image generation models on your own visual dataset and paint live with Realtime Canvas.',
        youtubeUrl: 'https://www.youtube.com/watch?v=VMj-3S1tku0',
        videoId: 'VMj-3S1tku0',
        channelTitle: 'Leonardo AI',
        videoTitle: 'Mastering Leonardo AI: Realtime Canvas and Custom LoRAs',
        objectives: [
          'Train custom LoRA finetunes on 15-20 curated photos',
          'Use Realtime Canvas for interactive inpainting and outpainting',
          'Leverage PhotoReal v2 and Alchemy pipelines',
        ],
        notes: 'Custom LoRAs give brand teams deterministic control over product packaging, logos, and characters.',
        resources: [
          { title: 'Leonardo AI Platform', url: 'https://leonardo.ai' },
        ],
      },
      {
        title: 'Commercial AI Assets: Upscaling & Vector Conversion',
        duration: '1h',
        summary: 'Upscale assets to 8K resolution, vectorize graphic logos, and prepare print-ready commercial deliverables.',
        youtubeUrl: 'https://www.youtube.com/watch?v=aircAruvnKk',
        videoId: 'aircAruvnKk',
        channelTitle: 'FutureTech Labs',
        videoTitle: 'Commercial AI Image Generation & High-Resolution Upscaling',
        objectives: [
          'Apply neural upscaling with Magnific AI and Topaz Gigapixel',
          'Convert raster AI generations into clean SVG vectors with Vectorizer',
          'Handle commercial licensing and copyright compliance',
        ],
        notes: 'Generative upscalers inject realistic micro-detail that traditional bicubic interpolation cannot match.',
        resources: [
          { title: 'Magnific AI Upscaler', url: 'https://magnific.ai' },
        ],
      },
    ],
  },
  {
    title: 'AI-Driven UI/UX Design Systems: Figma, Framer & AI Plugins',
    description: 'Transform wireframes into production web apps using Figma AI, Framer, component synthesis, and automated design token workflows.',
    category: 'AI UI/UX',
    level: 'Intermediate',
    duration: '4.8 hours',
    instructor: 'Marcus Vance (Principal Product Designer)',
    rating: 4.97,
    studentsCount: 3120,
    icon: 'Layers',
    overviewVideoId: 'IHZwWFHWa-w',
    modules: [
      {
        title: 'Figma AI: Automated Wireframing & Design Tokens',
        duration: '1h 15m',
        summary: 'Generate responsive layout frames from natural language and automate variant component sets with Figma AI.',
        youtubeUrl: 'https://www.youtube.com/watch?v=IHZwWFHWa-w',
        videoId: 'IHZwWFHWa-w',
        channelTitle: 'Mizko',
        videoTitle: 'Figma AI Masterclass: Generate Full Design Systems in Minutes',
        objectives: [
          'Generate wireframes and full-fidelity layouts with Figma AI',
          'Automate color tokens and typography variables',
          'Rename layers and organize auto-layout frames instantly',
        ],
        notes: 'AI plugins in Figma reduce repetitive auto-layout and naming overhead by over 70%.',
        resources: [
          { title: 'Figma AI Features Overview', url: 'https://www.figma.com/ai/' },
        ],
      },
      {
        title: 'Framer AI: Prompt to Responsive Interactive Website',
        duration: '1h 20m',
        summary: 'Turn textual prompts into live, interactive web experiences with custom breakpoints, CMS, and micro-interactions.',
        youtubeUrl: 'https://www.youtube.com/watch?v=jC4v5AS4RIM',
        videoId: 'jC4v5AS4RIM',
        channelTitle: 'Framer Official',
        videoTitle: 'Framer AI Tutorial: Design, Publish, and Host Production Sites',
        objectives: [
          'Generate multi-page layouts using Framer AI prompts',
          'Configure desktop, tablet, and mobile breakpoints seamlessly',
          'Publish to custom domains with built-in hosting and analytics',
        ],
        notes: 'Framer outputs real React code under the hood, making transition to full development smooth and lossless.',
        resources: [
          { title: 'Framer Academy', url: 'https://www.framer.com/academy/' },
        ],
      },
      {
        title: 'Micro-Interactions, 3D Splines & AI Animations',
        duration: '1h 10m',
        summary: 'Inject physics-based motion, 3D interactive canvases with Spline AI, and kinetic hover states into UI components.',
        youtubeUrl: 'https://www.youtube.com/watch?v=yk9lXobJ97E',
        videoId: 'yk9lXobJ97E',
        channelTitle: 'DesignCode',
        videoTitle: 'Building Interactive UI Components with AI & Code Export',
        objectives: [
          'Generate 3D spatial scenes using Spline AI prompts',
          'Integrate spring physics micro-interactions with Framer Motion',
          'Design futuristic dark-mode glassmorphic HUD components',
        ],
        notes: 'Subtle micro-animations elevate modern AI web applications from utilitarian to premium and engaging.',
        resources: [
          { title: 'Spline AI 3D Design', url: 'https://spline.design/ai' },
        ],
      },
      {
        title: 'From Design to Production Code: React & Tailwind Export',
        duration: '55m',
        summary: 'Bridge the design-development gap by converting Figma components into production-ready React, Vite, and Tailwind code.',
        youtubeUrl: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
        videoId: 'Fi3AJZZregE',
        channelTitle: 'Sonny Sangha',
        videoTitle: 'AI-Powered Figma to React Code Conversion Guide',
        objectives: [
          'Extract clean JSX and TailwindCSS tokens from Figma frames',
          'Ensure responsive flexbox and CSS grid fidelity',
          'Deploy components into modern Vite and Next.js applications',
        ],
        notes: 'Design-to-code pipelines eliminate manual CSS transcription while maintaining strict design system tokens.',
        resources: [
          { title: 'Figma to Code Plugins', url: 'https://www.figma.com/community' },
        ],
      },
    ],
  },
];
