// Curated Open Source Projects Dataset for AI Nexus Open-Source Learning Hub
export const openSourceReposData = [
  // ==========================================
  // 1. Frontend Design & UI/UX
  // ==========================================
  {
    name: 'React Bits',
    repoOwner: 'DavidHDev',
    repoName: 'react-bits',
    githubUrl: 'https://github.com/DavidHDev/react-bits',
    docsUrl: 'https://reactbits.dev',
    description: 'A large collection of animated, interactive, and customizable React components and micro-interactions.',
    purpose: 'Provides developers with copy-pasteable, highly polished animated React and Tailwind UI components that bring websites to life without heavy external library lock-in.',
    whyUseIt: 'Unlike monolithic component libraries, React Bits emphasizes creative animations, physics-based canvas effects, text scrubbers, and sleek micro-interactions that make interfaces stand out.',
    category: 'Frontend Design & UI/UX',
    techStack: ['React', 'Tailwind CSS', 'Framer Motion', 'TypeScript'],
    language: 'TypeScript',
    difficulty: 'Beginner',
    isBeginnerFriendly: true,
    stars: 12400,
    forks: 840,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'npx shadcn@latest add "https://reactbits.dev/r/component-name" # Or clone and copy from components/Animations',
    learningRoadmap: [
      { step: 1, title: 'Inspect Component Anatomy', description: 'Explore how Framer Motion variants and Tailwind classes are encapsulated inside clean single-file JSX components.' },
      { step: 2, title: 'Understand Canvas & WebGL Shaders', description: 'Check out background effects like Waves, Squares, and Hyperspeed to see how HTML5 Canvas interacts with React hooks.' },
      { step: 3, title: 'Adapt into Your Own Project', description: 'Copy components into your Vite or Next.js app and customize CSS variables for cyan/purple glowing themes.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'src/components',
      keyFolders: [
        { path: 'src/components/Animations', role: 'Motion-driven text reveals, magnetic buttons, and kinetic hover effects.' },
        { path: 'src/components/Backgrounds', role: 'Canvas and SVG procedural ambient backgrounds.' },
        { path: 'src/components/Components', role: 'Interactive cards, stacked carousels, and spotlight grids.' },
      ],
      architecturalNotes: 'Components are intentionally self-contained with minimal dependencies, utilizing Framer Motion for transitions and pure Tailwind CSS for styling tokens.',
    },
    youtubeTutorial: {
      title: 'React Bits: Top Animated Components for Modern Web Apps',
      url: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
      videoId: 'Fi3AJZZregE',
      channel: 'WebDev Tutorials',
    },
    icon: 'Sparkles',
  },
  {
    name: 'Magic UI',
    repoOwner: 'magicuidesign',
    repoName: 'magicui',
    githubUrl: 'https://github.com/magicuidesign/magicui',
    docsUrl: 'https://magicui.design',
    description: 'UI library for design engineers: 50+ animated components built with React, Typescript, Tailwind CSS, and Framer Motion.',
    purpose: 'Offers production-grade landing page animations, bento grids, border beams, animated beams, and globe components designed specifically for SaaS startups.',
    whyUseIt: 'Bridges the gap between design and engineering with copy-paste components that integrate directly into Tailwind and shadcn/ui setups with zero configuration.',
    category: 'Frontend Design & UI/UX',
    techStack: ['React', 'Next.js', 'Tailwind CSS', 'Framer Motion'],
    language: 'TypeScript',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 18500,
    forks: 1420,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'npm install framer-motion clsx tailwind-merge\nnpx shadcn@latest add @magicui/bento-grid',
    learningRoadmap: [
      { step: 1, title: 'Master Framer Motion Layout IDs', description: 'Analyze how Magic UI handles shared layout animations and dynamic path tracing in AnimatedBeam.' },
      { step: 2, title: 'SVG Filter Manipulations', description: 'Explore how components like BorderBeam use SVG stroke offsets and radial gradients.' },
      { step: 3, title: 'Construct a High-Conversion Hero', description: 'Assemble an interactive hero section using Particles, OrbitingCircles, and NeonGradientCard.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'packages/magicui/src',
      keyFolders: [
        { path: 'content/components', role: 'Component source code organized by UI categories (magic, mockups, text).' },
        { path: 'apps/www', role: 'Next.js documentation site showcasing interactive playground previews.' },
      ],
      architecturalNotes: 'Built on top of Tailwind CSS utilities, utilizing tailwind-merge and clsx for robust runtime class overriding.',
    },
    youtubeTutorial: {
      title: 'Build Award-Winning Landing Pages with Magic UI & Next.js',
      url: 'https://www.youtube.com/watch?v=yk9lXobJ97E',
      videoId: 'yk9lXobJ97E',
      channel: 'Frontend Masters',
    },
    icon: 'Layers',
  },
  {
    name: 'shadcn/ui',
    repoOwner: 'shadcn-ui',
    repoName: 'ui',
    githubUrl: 'https://github.com/shadcn-ui/ui',
    docsUrl: 'https://ui.shadcn.com',
    description: 'Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.',
    purpose: 'Revolutionized web development by replacing bulky npm component libraries with copy-pasteable accessible Radix UI primitives styled with Tailwind CSS.',
    whyUseIt: 'You own the code in your repository. You can customize every CSS token, variant, and accessibility attribute without fighting third-party library constraints.',
    category: 'Frontend Design & UI/UX',
    techStack: ['React', 'Radix UI', 'Tailwind CSS', 'TypeScript'],
    language: 'TypeScript',
    difficulty: 'Beginner',
    isBeginnerFriendly: true,
    stars: 82500,
    forks: 6900,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'npx shadcn@latest init\nnpx shadcn@latest add button dialog dropdown-menu',
    learningRoadmap: [
      { step: 1, title: 'Understand Radix UI Primitives', description: 'Learn how headless accessibility (ARIA roles, keyboard focus, screen readers) works beneath the visual styling.' },
      { step: 2, title: 'Class Variance Authority (CVA)', description: 'Master how variants (primary, secondary, destructive, ghost) are declared cleanly using CVA.' },
      { step: 3, title: 'Build a Custom Design System', description: 'Extend components by creating custom tokens in tailwind.config.ts and globals.css.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'apps/www/registry/new-york/ui',
      keyFolders: [
        { path: 'packages/cli', role: 'The CLI codebase that fetches and downloads components into user workspaces.' },
        { path: 'apps/www/registry', role: 'Core component implementations across Default and New York style variants.' },
      ],
      architecturalNotes: 'No runtime dependency on shadcn itself. Components are scaffolded directly into src/components/ui for complete developer ownership.',
    },
    youtubeTutorial: {
      title: 'shadcn/ui Complete Crash Course – Build Production React Apps',
      url: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
      videoId: 'Fi3AJZZregE',
      channel: 'Coding in Public',
    },
    icon: 'Box',
  },
  {
    name: 'Untitled UI React',
    repoOwner: 'untitleduico',
    repoName: 'react',
    githubUrl: 'https://github.com/untitleduico/react',
    docsUrl: 'https://untitledui.com',
    description: 'The React and Tailwind implementation of the world’s most popular Figma design system, Untitled UI.',
    purpose: 'Provides direct code parity with Figma design system tokens, helping product teams translate complex enterprise Figma files into production React interfaces effortlessly.',
    whyUseIt: 'Massive variety of enterprise-grade UI patterns: data tables, settings drawers, metrics cards, avatar groups, and date range pickers already mapped to Figma tokens.',
    category: 'Frontend Design & UI/UX',
    techStack: ['React', 'Tailwind CSS', 'Figma Tokens', 'TypeScript'],
    language: 'TypeScript',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 3800,
    forks: 410,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'git clone https://github.com/untitleduico/react.git\ncd react && npm install && npm run storybook',
    learningRoadmap: [
      { step: 1, title: 'Token Architecture', description: 'Inspect how typography scales, radius values, and semantic color aliases mirror Figma variables.' },
      { step: 2, title: 'Storybook Exploration', description: 'Run Storybook to test and interact with over 100+ production component states.' },
      { step: 3, title: 'Enterprise Dashboard Assembly', description: 'Combine sidebar navigation, data tables, and modal drawers into a responsive SaaS dashboard.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'src/components',
      keyFolders: [
        { path: 'src/components/base', role: 'Fundamental inputs, buttons, toggles, badges, and avatars.' },
        { path: 'src/components/application', role: 'Complex patterns: modal dialogs, slide-overs, tables, and pagination.' },
      ],
      architecturalNotes: 'Designed for pixel-perfect fidelity with Figma Untitled UI, utilizing strictly typed React props and Tailwind arbitrary values where necessary.',
    },
    youtubeTutorial: {
      title: 'Figma to React Workflow with Untitled UI and Tailwind',
      url: 'https://www.youtube.com/watch?v=IHZwWFHWa-w',
      videoId: 'IHZwWFHWa-w',
      channel: 'Design Systems Daily',
    },
    icon: 'Layers',
  },
  {
    name: 'Penpot',
    repoOwner: 'penpot',
    repoName: 'penpot',
    githubUrl: 'https://github.com/penpot/penpot',
    docsUrl: 'https://penpot.app',
    description: 'The first open-source web-based design and prototyping tool built natively on modern web standards (SVG, CSS Grid, Flexbox).',
    purpose: 'Offers a self-hostable, open-source alternative to Figma that empowers designers and developers to collaborate using real CSS layout engines rather than proprietary formats.',
    whyUseIt: 'True web-native output: everything created in Penpot uses real CSS Flexbox and Grid. Eliminates vendor lock-in and protects proprietary UI designs on private cloud servers.',
    category: 'Frontend Design & UI/UX',
    techStack: ['ClojureScript', 'SVG', 'CSS Grid', 'WebAssembly', 'Docker'],
    language: 'ClojureScript',
    difficulty: 'Advanced',
    isBeginnerFriendly: false,
    stars: 33400,
    forks: 1890,
    license: 'MPL-2.0',
    lastUpdated: 'Recent (Active)',
    installGuide: 'docker compose -p penpot -f docker-compose.yaml up -d',
    learningRoadmap: [
      { step: 1, title: 'Inspect Canvas Rendering Loop', description: 'Understand how the vector canvas uses SVG and WebAssembly for high-performance panning and zooming.' },
      { step: 2, title: 'CSS Grid & Flexbox Engine', description: 'Analyze how UI frames translate real CSS layout rules directly to render nodes.' },
      { step: 3, title: 'Plugin Development', description: 'Build a custom Penpot plugin using JavaScript/TypeScript APIs to automate asset export.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'frontend/src/app',
      keyFolders: [
        { path: 'frontend', role: 'ClojureScript web interface and interactive vector canvas.' },
        { path: 'backend', role: 'Server architecture handling collaborative websockets, persistence, and image processing.' },
      ],
      architecturalNotes: 'Heavy emphasis on functional programming and immutability with ClojureScript, paired with low-level WASM rendering for smooth 60fps canvas performance.',
    },
    youtubeTutorial: {
      title: 'Penpot 2.0 Open Source Design Masterclass – Self-Hosted Figma Alternative',
      url: 'https://www.youtube.com/watch?v=IHZwWFHWa-w',
      videoId: 'IHZwWFHWa-w',
      channel: 'Open Source Design',
    },
    icon: 'PenTool',
  },
  {
    name: 'Excalidraw',
    repoOwner: 'excalidraw',
    repoName: 'excalidraw',
    githubUrl: 'https://github.com/excalidraw/excalidraw',
    docsUrl: 'https://excalidraw.com',
    description: 'Virtual collaborative whiteboard for sketching hand-drawn like diagrams with end-to-end encryption.',
    purpose: 'Enables developers and architects to sketch system designs, data flow architectures, and wireframes with an intuitive hand-drawn aesthetic.',
    whyUseIt: 'Embeddable as a standalone React component (`@excalidraw/excalidraw`) in your own apps, featuring real-time multiplayer collaboration, WebRTC P2P sync, and zero server storage of diagram contents.',
    category: 'Frontend Design & UI/UX',
    techStack: ['React', 'Canvas API', 'Rough.js', 'TypeScript', 'WebRTC'],
    language: 'TypeScript',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 88900,
    forks: 8200,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'npm install @excalidraw/excalidraw\n# Embed in React:\nimport { Excalidraw } from "@excalidraw/excalidraw";',
    learningRoadmap: [
      { step: 1, title: 'Rough.js Procedural Rendering', description: 'Understand how Rough.js creates jittered, sketch-like polygon outlines on the HTML5 2D canvas context.' },
      { step: 2, title: 'Scene State Reconciliation', description: 'Analyze how elements array and appState handle undo/redo stacks and zoom transforms.' },
      { step: 3, title: 'Embed in a Custom Dashboard', description: 'Mount Excalidraw inside a React modal to let users annotate charts or draft database schemas.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'packages/excalidraw/index.tsx',
      keyFolders: [
        { path: 'packages/excalidraw/renderer', role: '2D canvas render engine and Rough.js shape generators.' },
        { path: 'packages/excalidraw/components', role: 'Floating toolbars, color pickers, and export dialogs.' },
      ],
      architecturalNotes: 'Optimized 2D canvas rendering with offscreen double-buffering to ensure zero frame drops even with thousands of diagram nodes.',
    },
    youtubeTutorial: {
      title: 'How to Embed Excalidraw in React Apps with Multiplayer Sync',
      url: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
      videoId: 'Fi3AJZZregE',
      channel: 'Jack Herrington',
    },
    icon: 'PenTool',
  },

  // ==========================================
  // 2. Animation & 3D
  // ==========================================
  {
    name: 'Theatre.js',
    repoOwner: 'theatre-js',
    repoName: 'theatre',
    githubUrl: 'https://github.com/theatre-js/theatre',
    docsUrl: 'https://theatrejs.com',
    description: 'Motion design and visual animation editor for the web. Animate Three.js, React Three Fiber, HTML/SVG, and audio visually.',
    purpose: 'Brings an interactive timeline, keyframe graph editor, and visual tweak panel into your web application to choreograph complex 3D and DOM motion sequences.',
    whyUseIt: 'Bridges creative directors and frontend engineers: designers can adjust keyframe curves visually in the browser studio, and developers export the deterministic animation JSON to run at 60fps.',
    category: 'Animation & 3D',
    techStack: ['TypeScript', 'Three.js', 'React', 'WebGL', 'Web Audio'],
    language: 'TypeScript',
    difficulty: 'Advanced',
    isBeginnerFriendly: false,
    stars: 12100,
    forks: 580,
    license: 'Apache-2.0',
    lastUpdated: 'Recent (Active)',
    installGuide: 'npm install @theatre/core @theatre/studio',
    learningRoadmap: [
      { step: 1, title: 'Sheet & Object Concept', description: 'Understand Projects, Sheets, and SheetObjects that bind JavaScript variables to keyframe tracks.' },
      { step: 2, title: 'Three.js Camera Choreography', description: 'Hook a Three.js perspective camera position and focal target to Theatre.js timeline sequences.' },
      { step: 3, title: 'Exporting Production Bundles', description: 'Export the project JSON state and run @theatre/core standalone in production without the studio overhead.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'packages/core',
      keyFolders: [
        { path: 'packages/core', role: 'Runtime evaluation engine that computes interpolated values from keyframe curves.' },
        { path: 'packages/studio', role: 'In-browser visual editor with playhead, graph curves, and property inspector.' },
        { path: 'packages/r3f', role: 'React Three Fiber integration package with declarative <editable.*> components.' },
      ],
      architecturalNotes: 'Clear separation between the heavy @theatre/studio GUI editor and the ultra-lightweight @theatre/core runtime that evaluates bezier curves at 60fps.',
    },
    youtubeTutorial: {
      title: 'Theatre.js & Three.js 3D Web Animation Complete Guide',
      url: 'https://www.youtube.com/watch?v=aircAruvnKk',
      videoId: 'aircAruvnKk',
      channel: 'DesignCourse',
    },
    icon: 'Film',
  },
  {
    name: 'Three.js',
    repoOwner: 'mrdoob',
    repoName: 'three.js',
    githubUrl: 'https://github.com/mrdoob/three.js',
    docsUrl: 'https://threejs.org',
    description: 'JavaScript 3D Library that makes WebGL accessible, powerful, and standard across all modern web browsers.',
    purpose: 'The foundational 3D graphics library of the web, rendering scenes, geometries, materials, PBR shaders, lights, and cameras onto HTML5 WebGL and WebGPU canvases.',
    whyUseIt: 'Industry standard for 3D web experiences, automotive configurators, generative art, and spatial computing in the browser.',
    category: 'Animation & 3D',
    techStack: ['JavaScript', 'WebGL', 'WebGPU', 'GLSL Shaders'],
    language: 'JavaScript',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 104000,
    forks: 36200,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'npm install three @types/three',
    learningRoadmap: [
      { step: 1, title: 'Scene, Camera, Renderer Trinity', description: 'Learn the basic render loop: requestAnimationFrame, scene graph updates, and viewport resizing.' },
      { step: 2, title: 'Meshes, Geometries & Materials', description: 'Experiment with MeshStandardMaterial, roughness, metalness, and environment map HDR lighting.' },
      { step: 3, title: 'Custom GLSL Shaders', description: 'Write vertex and fragment shaders using ShaderMaterial to create custom procedural waves and glows.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'src/Three.js',
      keyFolders: [
        { path: 'src/core', role: 'BufferGeometry, Object3D, Raycaster, and EventDispatcher.' },
        { path: 'src/renderers', role: 'WebGLRenderer and the modern WebGPURenderer backend.' },
        { path: 'examples/jsm', role: 'OrbitControls, GLTFLoader, DRACOLoader, and postprocessing passes.' },
      ],
      architecturalNotes: 'Hierarchical scene graph where child Object3Ds inherit transformation matrices from parents, rendered sequentially through the GPU pipeline.',
    },
    youtubeTutorial: {
      title: 'Three.js Beginner to Pro – Build a 3D Cyber Website',
      url: 'https://www.youtube.com/watch?v=aircAruvnKk',
      videoId: 'aircAruvnKk',
      channel: 'Bruno Simon / FreeCodeCamp',
    },
    icon: 'Box',
  },
  {
    name: 'React Three Fiber (R3F)',
    repoOwner: 'pmndrs',
    repoName: 'react-three-fiber',
    githubUrl: 'https://github.com/pmndrs/react-three-fiber',
    docsUrl: 'https://r3f.docs.pmnd.rs',
    description: 'A React reconciler for Three.js. Build your scene graph declaratively with re-usable, self-contained components.',
    purpose: 'Brings React component composition, state management, and lifecycle hooks to Three.js 3D development without performance compromises.',
    whyUseIt: 'Allows developers to manage 3D objects as clean React JSX tags (`<mesh>`, `<boxGeometry>`, `<meshStandardMaterial>`) that respond to props, hooks, and context naturally.',
    category: 'Animation & 3D',
    techStack: ['React', 'Three.js', 'TypeScript', '@react-three/drei'],
    language: 'TypeScript',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 27900,
    forks: 1950,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'npm install three @react-three/fiber @react-three/drei',
    learningRoadmap: [
      { step: 1, title: 'The <Canvas> Wrapper', description: 'Learn how <Canvas> creates an automatic Three.js scene, camera, and render loop.' },
      { step: 2, title: 'useFrame & useThree Hooks', description: 'Animate rotations and access the canvas viewport using the useFrame delta loop.' },
      { step: 3, title: 'Load 3D Models with Drei', description: 'Use useGLTF from @react-three/drei to load photorealistic GLTF/GLB models with shadows.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'packages/fiber/src',
      keyFolders: [
        { path: 'packages/fiber/src/core', role: 'Custom React reconciler that bridges React element lifecycle with Three.js objects.' },
        { path: 'packages/fiber/src/web', role: 'HTML Canvas mounting and pointer event dispatchers.' },
      ],
      architecturalNotes: 'Does not wrap Three.js objects in React components; instead, it is a true custom reconciler that directly mutates Three.js objects outside React DOM overhead.',
    },
    youtubeTutorial: {
      title: 'React Three Fiber & Drei Crash Course – 3D Web Development',
      url: 'https://www.youtube.com/watch?v=aircAruvnKk',
      videoId: 'aircAruvnKk',
      channel: 'Wawa Sensei',
    },
    icon: 'Cpu',
  },
  {
    name: 'Lottie Web',
    repoOwner: 'airbnb',
    repoName: 'lottie-web',
    githubUrl: 'https://github.com/airbnb/lottie-web',
    docsUrl: 'https://airbnb.io/lottie',
    description: 'Render Adobe After Effects animations natively on Web, Android, and iOS using lightweight JSON export files.',
    purpose: 'Renders complex, vector-crisp After Effects animations on web pages via SVG, Canvas, or HTML elements without the file weight of video or GIF files.',
    whyUseIt: 'Micro-animations (checkmarks, confetti, onboarding characters, loading spinners) can be exported directly from motion design tools and played interactively based on scroll or click.',
    category: 'Animation & 3D',
    techStack: ['JavaScript', 'SVG', 'Canvas API', 'JSON Animation'],
    language: 'JavaScript',
    difficulty: 'Beginner',
    isBeginnerFriendly: true,
    stars: 29800,
    forks: 4800,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'npm install lottie-web',
    learningRoadmap: [
      { step: 1, title: 'Load JSON Animation Data', description: 'Use lottie.loadAnimation to mount a dynamic SVG animation into a container div.' },
      { step: 2, title: 'Interactive Playback Controls', description: 'Hook animation play(), pause(), setSpeed(), and playSegments() to mouse hover and click events.' },
      { step: 3, title: 'Scroll-Driven Scrubbing', description: 'Bind animation frame progression to page scroll position for interactive storytelling.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'player/js/main.js',
      keyFolders: [
        { path: 'player/js/renderers', role: 'SVG, Canvas, and HTML animation render drivers.' },
        { path: 'player/js/elements', role: 'Vector paths, text layers, shapes, and bezier curve transformers.' },
      ],
      architecturalNotes: 'Parses BodyMovin JSON specifications into frame-by-frame SVG transformations with minimal memory footprints.',
    },
    youtubeTutorial: {
      title: 'Lottie Animations in React & Next.js: Complete Guide',
      url: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
      videoId: 'Fi3AJZZregE',
      channel: 'Adrian Twarog',
    },
    icon: 'PlayCircle',
  },

  // ==========================================
  // 3. Frontend Frameworks
  // ==========================================
  {
    name: 'Next.js',
    repoOwner: 'vercel',
    repoName: 'next.js',
    githubUrl: 'https://github.com/vercel/next.js',
    docsUrl: 'https://nextjs.org/docs',
    description: 'The React Framework for the Web. Used by the world’s leading companies to build fast, full-stack web applications.',
    purpose: 'Combines React Server Components, server-side rendering (SSR), static site generation (SSG), streaming, and edge API routes into a unified framework.',
    whyUseIt: 'Best-in-class SEO, performance optimization, image optimization, App Router layouts, and zero-config deployment to Vercel or Node.js servers.',
    category: 'Frontend Frameworks',
    techStack: ['React', 'TypeScript', 'Rust', 'Turbopack', 'Node.js'],
    language: 'TypeScript',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 128000,
    forks: 27100,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'npx create-next-app@latest my-app --typescript --tailwind --app',
    learningRoadmap: [
      { step: 1, title: 'App Router Architecture', description: 'Master layout.tsx, page.tsx, loading.tsx, error.tsx, and nested dynamic routes [slug].' },
      { step: 2, title: 'Server vs Client Components', description: 'Understand when to render on the server for zero client bundle vs "use client" for interactivity.' },
      { step: 3, title: 'Server Actions & Mutations', description: 'Perform secure form submissions and database mutations directly in server functions without manual REST boilerplate.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'packages/next',
      keyFolders: [
        { path: 'packages/next/src/server', role: 'Server rendering engine, Rsc stream processors, and edge execution runtimes.' },
        { path: 'packages/next/src/client', role: 'Client hydration, Link prefetching, and router cache.' },
      ],
      architecturalNotes: 'Combines Rust-based Turbopack for lightning-fast compilation with advanced streaming HTTP responses to render interfaces progressively.',
    },
    youtubeTutorial: {
      title: 'Next.js 15 Complete Full-Stack Crash Course',
      url: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
      videoId: 'Fi3AJZZregE',
      channel: 'freeCodeCamp.org',
    },
    icon: 'Globe',
  },
  {
    name: 'Create T3 App',
    repoOwner: 't3-oss',
    repoName: 'create-t3-app',
    githubUrl: 'https://github.com/t3-oss/create-t3-app',
    docsUrl: 'https://create.t3.gg',
    description: 'The best way to start a full-stack, typesafe Next.js app with tRPC, Tailwind CSS, TypeScript, and Prisma/Drizzle.',
    purpose: 'Standardizes the modern TypeScript full-stack developer experience by providing end-to-end type safety from the database schema up to the React button onClick.',
    whyUseIt: 'Eliminates API contract synchronization errors: changing a backend database column immediately shows TypeScript red squigglies on the frontend if types mismatch.',
    category: 'Frontend Frameworks',
    techStack: ['Next.js', 'tRPC', 'Prisma', 'Tailwind CSS', 'NextAuth.js'],
    language: 'TypeScript',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 25200,
    forks: 1350,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'npm create t3-app@latest',
    learningRoadmap: [
      { step: 1, title: 'End-to-End Type Safety with tRPC', description: 'Define backend routers with Zod validation and call them in React using useQuery with automatic autocompletion.' },
      { step: 2, title: 'Database Schemas with Prisma/Drizzle', description: 'Model relational schemas, run migrations, and query databases safely.' },
      { step: 3, title: 'Authentication Integration', description: 'Set up NextAuth.js session providers and protect routes seamlessly.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'cli/src/index.ts',
      keyFolders: [
        { path: 'cli/src/installers', role: 'Modular installers for Prisma, Drizzle, Tailwind, tRPC, and NextAuth.' },
        { path: 'template', role: 'Starter templates demonstrating clean architectural separation.' },
      ],
      architecturalNotes: 'Focused on type safety, modular scaffolding, and eliminating unnecessary abstractions.',
    },
    youtubeTutorial: {
      title: 'The T3 Stack Tutorial – Full Stack Type Safe Apps',
      url: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
      videoId: 'Fi3AJZZregE',
      channel: 'Theo - t3.gg',
    },
    icon: 'Layers',
  },
  {
    name: 'Vite',
    repoOwner: 'vitejs',
    repoName: 'vite',
    githubUrl: 'https://github.com/vitejs/vite',
    docsUrl: 'https://vite.dev',
    description: 'Next Generation Frontend Tooling. Native ES module dev server with ultra-fast Hot Module Replacement (HMR).',
    purpose: 'Powers modern frontend web development by serving source code over native ESM during development and bundling with Rollup/Rolldown for production.',
    whyUseIt: 'Instant server start and near-instant HMR regardless of project scale. Supported officially by React, Vue, Svelte, Solid, and Vanilla JS.',
    category: 'Frontend Frameworks',
    techStack: ['TypeScript', 'Rollup', 'esbuild', 'Native ESM'],
    language: 'TypeScript',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 71200,
    forks: 6300,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'npm create vite@latest my-app -- --template react-ts',
    learningRoadmap: [
      { step: 1, title: 'Understand Native ESM in Dev', description: 'Learn how browsers fetch requested modules directly via HTTP imports instead of bundling the whole project first.' },
      { step: 2, title: 'Vite Plugins & Configuration', description: 'Write a custom Vite plugin using transform and resolveId hooks to modify file contents on the fly.' },
      { step: 3, title: 'Production Bundle Optimization', description: 'Configure Rollup manualChunks, code splitting, and asset inlining.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'packages/vite/src/node/index.ts',
      keyFolders: [
        { path: 'packages/vite/src/node/server', role: 'Connect HTTP server, WebSocket HMR dispatcher, and module graph.' },
        { path: 'packages/vite/src/client', role: 'In-browser HMR client updating modules without full page reload.' },
      ],
      architecturalNotes: 'Uses esbuild for fast pre-bundling of node_modules and native ESM for instant on-demand compilation of application source code.',
    },
    youtubeTutorial: {
      title: 'Vite Crash Course – Why Modern Web Dev Switched to Vite',
      url: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
      videoId: 'Fi3AJZZregE',
      channel: 'Traversy Media',
    },
    icon: 'Zap',
  },

  // ==========================================
  // 4. Backend Development
  // ==========================================
  {
    name: 'FastAPI',
    repoOwner: 'tiangolo',
    repoName: 'fastapi',
    githubUrl: 'https://github.com/tiangolo/fastapi',
    docsUrl: 'https://fastapi.tiangolo.com',
    description: 'Modern, fast (high-performance), web framework for building APIs with Python 3.8+ based on standard Python type hints.',
    purpose: 'High-performance Python backend framework used worldwide for serving machine learning models, REST APIs, and microservices.',
    whyUseIt: 'Automatic interactive OpenAPI documentation (Swagger UI), asynchronous execution via ASGI (Uvicorn), and robust data validation with Pydantic.',
    category: 'Backend Development',
    techStack: ['Python', 'Pydantic', 'Starlette', 'ASGI', 'Swagger/OpenAPI'],
    language: 'Python',
    difficulty: 'Beginner',
    isBeginnerFriendly: true,
    stars: 78900,
    forks: 6350,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'pip install "fastapi[standard]"\nfastapi dev main.py',
    learningRoadmap: [
      { step: 1, title: 'Type Hints & Request Validation', description: 'Define request and response models with Pydantic BaseModel to automate JSON schema validation.' },
      { step: 2, title: 'Dependency Injection (Depends)', description: 'Structure database sessions, authentication headers, and cache clients cleanly using FastAPI dependencies.' },
      { step: 3, title: 'Async Handlers & AI Model Inference', description: 'Run asynchronous API routes connected to LLM streams or background workers.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'fastapi/applications.py',
      keyFolders: [
        { path: 'fastapi/routing.py', role: 'APIRoute execution, query/body parameter parsing, and response serialization.' },
        { path: 'fastapi/dependencies', role: 'Dependency injection resolution graph and caching.' },
      ],
      architecturalNotes: 'Inherits Starlette for ASGI routing and HTTP middleware, delegating parameter validation to Pydantic and generating OpenAPI specs automatically.',
    },
    youtubeTutorial: {
      title: 'FastAPI Tutorial – Build Production APIs & Connect AI Models',
      url: 'https://www.youtube.com/watch?v=0k_2uX7l-t4',
      videoId: '0k_2uX7l-t4',
      channel: 'freeCodeCamp.org',
    },
    icon: 'Terminal',
  },
  {
    name: 'NestJS',
    repoOwner: 'nestjs',
    repoName: 'nest',
    githubUrl: 'https://github.com/nestjs/nest',
    docsUrl: 'https://nestjs.com',
    description: 'A progressive Node.js framework for building efficient, reliable and scalable enterprise server-side applications.',
    purpose: 'Provides a structured, modular architecture for enterprise Node.js applications with out-of-the-box TypeScript, dependency injection, and microservices support.',
    whyUseIt: 'Brings battle-tested Angular-style architectural patterns (Controllers, Services, Modules, Guards, Interceptors) to backend TypeScript, preventing unmaintainable spaghetti code.',
    category: 'Backend Development',
    techStack: ['Node.js', 'TypeScript', 'Express/Fastify', 'TypeORM/Prisma', 'Microservices'],
    language: 'TypeScript',
    difficulty: 'Intermediate',
    isBeginnerFriendly: false,
    stars: 67200,
    forks: 7400,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'npm i -g @nestjs/cli\nnest new my-nest-project',
    learningRoadmap: [
      { step: 1, title: 'Modules, Controllers & Services', description: 'Learn how @Controller handles incoming requests and @Injectable services manage business logic.' },
      { step: 2, title: 'Guards, Interceptors & JWT Auth', description: 'Implement JWT authentication and role-based access control with NestJS guards.' },
      { step: 3, title: 'Database Integration & Microservices', description: 'Connect Prisma/TypeORM and configure event-driven microservices via RabbitMQ or Redis.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'packages/core',
      keyFolders: [
        { path: 'packages/core/injector', role: 'The dependency injection container and instance loader.' },
        { path: 'packages/common', role: 'Core decorators (@Controller, @Get, @Post) and HTTP exceptions.' },
      ],
      architecturalNotes: 'Features an inversion-of-control (IoC) dependency injection container running over Express or Fastify HTTP adapters.',
    },
    youtubeTutorial: {
      title: 'NestJS Full Course – Enterprise Backend Development',
      url: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
      videoId: 'Fi3AJZZregE',
      channel: 'freeCodeCamp.org',
    },
    icon: 'Server',
  },
  {
    name: 'Gin Gonic',
    repoOwner: 'gin-gonic',
    repoName: 'gin',
    githubUrl: 'https://github.com/gin-gonic/gin',
    docsUrl: 'https://gin-gonic.com',
    description: 'Gin is an HTTP web framework written in Go (Golang). It features a Martini-like API with performance up to 40 times faster.',
    purpose: 'Provides ultra-high throughput and low latency microservice routing in Go using a custom radix tree router.',
    whyUseIt: 'Exceptional memory efficiency and execution speed. Ideal for high-scale backend services handling hundreds of thousands of concurrent requests.',
    category: 'Backend Development',
    techStack: ['Go (Golang)', 'HTTP', 'Radix Tree', 'JSON Binding'],
    language: 'Go',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 79800,
    forks: 8100,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'go get -u github.com/gin-gonic/gin',
    learningRoadmap: [
      { step: 1, title: 'Radix Tree Router & Grouping', description: 'Create versioned API route groups (/api/v1) and bind URL parameter variables.' },
      { step: 2, title: 'Custom Middlewares', description: 'Implement authentication, rate limiting, and structured logging middlewares with c.Next().' },
      { step: 3, title: 'JSON Binding & GORM Database Layer', description: 'Bind request payloads to Go structs and persist records using GORM.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'gin.go',
      keyFolders: [
        { path: 'tree.go', role: 'Radix tree router implementation for ultra-fast URL path matching.' },
        { path: 'context.go', role: 'The gin.Context object encapsulating response writer and request reader.' },
      ],
      architecturalNotes: 'Radix tree routing eliminates regex overhead during URL dispatching, allocating minimal heap memory per request.',
    },
    youtubeTutorial: {
      title: 'Go / Golang Backend API with Gin and PostgreSQL Crash Course',
      url: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
      videoId: 'Fi3AJZZregE',
      channel: 'Tech With Tim',
    },
    icon: 'Terminal',
  },

  // ==========================================
  // 5. Full-Stack Projects
  // ==========================================
  {
    name: 'Supabase',
    repoOwner: 'supabase',
    repoName: 'supabase',
    githubUrl: 'https://github.com/supabase/supabase',
    docsUrl: 'https://supabase.com/docs',
    description: 'The open-source Firebase alternative. Postgres database, Authentication, instant APIs, Edge Functions, Realtime, and Storage.',
    purpose: 'Empowers developers to spin up a production-ready, scalable backend in minutes backed by the world’s most advanced relational database: PostgreSQL.',
    whyUseIt: 'No proprietary database lock-in: real PostgreSQL with Row Level Security (RLS), full SQL power, automated vector embeddings (pgvector), and instant client libraries.',
    category: 'Full-Stack Projects',
    techStack: ['PostgreSQL', 'TypeScript', 'Go', 'Docker', 'pgvector'],
    language: 'TypeScript',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 76500,
    forks: 6400,
    license: 'Apache-2.0',
    lastUpdated: 'Recent (Active)',
    installGuide: 'npx supabase init\nnpx supabase start # Starts local Postgres, Auth, and Studio',
    learningRoadmap: [
      { step: 1, title: 'Row Level Security (RLS)', description: 'Write SQL security policies that protect rows based on auth.uid() directly in PostgreSQL.' },
      { step: 2, title: 'Realtime Subscriptions', description: 'Subscribe to database INSERT/UPDATE/DELETE events via WebSockets from React apps.' },
      { step: 3, title: 'Vector Search with pgvector', description: 'Store AI document embeddings and perform similarity search queries using HNSW indexes.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'apps/studio',
      keyFolders: [
        { path: 'apps/studio', role: 'Next.js admin dashboard and SQL query runner interface.' },
        { path: 'packages/pg-meta', role: 'PostgreSQL schema introspection engine and REST bridge.' },
      ],
      architecturalNotes: 'Composes best-of-breed open-source tools: PostgreSQL, PostgREST for instant HTTP APIs, GoTrue for authentication, and Realtime engine for WebSockets.',
    },
    youtubeTutorial: {
      title: 'Supabase Complete Course – Build a Full Stack App in 1 Hour',
      url: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
      videoId: 'Fi3AJZZregE',
      channel: 'freeCodeCamp.org',
    },
    icon: 'Database',
  },
  {
    name: 'Cal.com',
    repoOwner: 'calcom',
    repoName: 'cal.com',
    githubUrl: 'https://github.com/calcom/cal.com',
    docsUrl: 'https://cal.com/docs',
    description: 'Scheduling infrastructure for everyone. Open source Calendly alternative with white-label booking and calendar integrations.',
    purpose: 'Production full-stack enterprise SaaS monorepo handling global timezones, Google/Outlook calendar syncing, webhooks, payments, and team scheduling.',
    whyUseIt: 'A gold standard example of a modern production Next.js enterprise monorepo using Turborepo, Prisma, Tailwind, tRPC, and Stripe integration.',
    category: 'Full-Stack Projects',
    techStack: ['Next.js', 'Turborepo', 'tRPC', 'Prisma', 'Tailwind CSS', 'PostgreSQL'],
    language: 'TypeScript',
    difficulty: 'Advanced',
    isBeginnerFriendly: false,
    stars: 34100,
    forks: 8200,
    license: 'AGPL-3.0',
    lastUpdated: 'Recent (Active)',
    installGuide: 'git clone https://github.com/calcom/cal.com.git\nyarn && yarn dx',
    learningRoadmap: [
      { step: 1, title: 'Turborepo Monorepo Structure', description: 'Examine how apps/web, packages/prisma, and packages/trpc share types and configs.' },
      { step: 2, title: 'Calendar Sync Engine', description: 'Study how Cal.com handles complex timezone offsets and recurring booking slots.' },
      { step: 3, title: 'App Store Architecture', description: 'Inspect the extensible plugin architecture for Zoom, Google Meet, and Stripe.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'apps/web',
      keyFolders: [
        { path: 'apps/web', role: 'Primary customer dashboard and public booking page.' },
        { path: 'packages/trpc', role: 'End-to-end typed API routers for booking, availability, and teams.' },
        { path: 'packages/prisma', role: 'Database schema models and migrations.' },
      ],
      architecturalNotes: 'Monorepo architecture with strict module boundaries, leveraging Prisma for PostgreSQL persistence and tRPC for seamless type safety.',
    },
    youtubeTutorial: {
      title: 'Inside the Cal.com Codebase: Architecture of an Open Source SaaS',
      url: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
      videoId: 'Fi3AJZZregE',
      channel: 'SaaS Architecture Reviews',
    },
    icon: 'Calendar',
  },
  {
    name: 'Dub.co',
    repoOwner: 'dubinc',
    repoName: 'dub',
    githubUrl: 'https://github.com/dubinc/dub',
    docsUrl: 'https://dub.co/docs',
    description: 'The modern open-source link management platform for marketing, analytics, and vanity short URLs.',
    purpose: 'High-performance link redirection, geotargeting analytics, QR code generation, and custom domain management platform built on Next.js and Redis.',
    whyUseIt: 'Exemplary modern full-stack web application with gorgeous UI design, edge middleware redirection, Upstash Redis caching, and ClickHouse analytics.',
    category: 'Full-Stack Projects',
    techStack: ['Next.js', 'Tailwind CSS', 'Upstash Redis', 'Prisma', 'Tinybird/ClickHouse'],
    language: 'TypeScript',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 20100,
    forks: 2300,
    license: 'AGPL-3.0',
    lastUpdated: 'Recent (Active)',
    installGuide: 'pnpm install && pnpm dev',
    learningRoadmap: [
      { step: 1, title: 'Next.js Edge Middleware', description: 'Learn how short URLs are redirected at the edge in <10ms before hitting the origin server.' },
      { step: 2, title: 'High-Scale Analytics Ingestion', description: 'Explore how click tracking events are batched into Tinybird/ClickHouse.' },
      { step: 3, title: 'Polished Dashboard UX', description: 'Study Dub.co’s command menu (cmdk), modal state management, and animated charts.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'apps/web',
      keyFolders: [
        { path: 'apps/web/middleware.ts', role: 'Edge redirect routing and domain alias dispatching.' },
        { path: 'packages/ui', role: 'Design system components shared across apps.' },
      ],
      architecturalNotes: 'Optimized for sub-millisecond edge resolution using Vercel Edge functions and Redis distributed key-value lookup.',
    },
    youtubeTutorial: {
      title: 'Dub.co Full Stack SaaS Architecture Breakdown',
      url: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
      videoId: 'Fi3AJZZregE',
      channel: 'Code With Antonio',
    },
    icon: 'Share2',
  },

  // ==========================================
  // 6. AI & Machine Learning
  // ==========================================
  {
    name: 'LangChain',
    repoOwner: 'langchain-ai',
    repoName: 'langchain',
    githubUrl: 'https://github.com/langchain-ai/langchain',
    docsUrl: 'https://python.langchain.com',
    description: 'Framework for developing applications powered by large language models (LLMs). Prompt chaining, agents, RAG, and memory.',
    purpose: 'Standardizes the integration of frontier AI models with external tools, vector stores, prompt templates, and autonomous agent loops.',
    whyUseIt: 'Extensive ecosystem of 700+ integrations (OpenAI, Anthropic, Gemini, Pinecone, Chroma, AWS) with built-in streaming and observability.',
    category: 'AI & Machine Learning',
    techStack: ['Python', 'LLMs', 'Vector DBs', 'Embeddings', 'Pydantic'],
    language: 'Python',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 97800,
    forks: 15400,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'pip install langchain langchain-community langchain-openai',
    learningRoadmap: [
      { step: 1, title: 'LangChain Expression Language (LCEL)', description: 'Construct declarative runnable chains using pipe syntax: prompt | model | parser.' },
      { step: 2, title: 'Retrieval-Augmented Generation (RAG)', description: 'Chunk documents, generate vector embeddings, and retrieve relevant contexts for questions.' },
      { step: 3, title: 'Tool Calling & Agents', description: 'Bind custom Python functions to models and let agents select and invoke tools iteratively.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'libs/core/langchain_core',
      keyFolders: [
        { path: 'libs/core', role: 'Base interfaces: Runnables, BaseChatModel, BaseRetriever, Document.' },
        { path: 'libs/community', role: 'Integrations with third-party APIs, vector stores, and tools.' },
      ],
      architecturalNotes: 'Built around the LCEL (LangChain Expression Language) Runnable protocol, providing synchronous, asynchronous, batch, and streaming execution out of the box.',
    },
    youtubeTutorial: {
      title: 'LangChain Full Course – Build Production AI Apps and Agents',
      url: 'https://www.youtube.com/watch?v=sal78ACtGTc',
      videoId: 'sal78ACtGTc',
      channel: 'freeCodeCamp.org',
    },
    icon: 'Cpu',
  },
  {
    name: 'Ollama',
    repoOwner: 'ollama',
    repoName: 'ollama',
    githubUrl: 'https://github.com/ollama/ollama',
    docsUrl: 'https://ollama.com',
    description: 'Get up and running with Llama 3.3, Mistral, Gemma 2, DeepSeek-R1, and other large language models locally.',
    purpose: 'Packages model weights, GPU quantization, and llama.cpp into a simple CLI and OpenAI-compatible REST server for local offline AI execution.',
    whyUseIt: 'Run open-weight models on Mac, Windows, and Linux with automated GPU acceleration (Metal, CUDA, ROCm) with a single command without cloud API fees.',
    category: 'AI & Machine Learning',
    techStack: ['Go (Golang)', 'C++', 'llama.cpp', 'CUDA', 'Metal'],
    language: 'Go',
    difficulty: 'Beginner',
    isBeginnerFriendly: true,
    stars: 114000,
    forks: 9200,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'ollama run deepseek-r1:8b\n# REST API available at http://localhost:11434/api/generate',
    learningRoadmap: [
      { step: 1, title: 'Modelfile Customization', description: 'Write custom Modelfiles to set system instructions, temperatures, and parameter stops.' },
      { step: 2, title: 'OpenAI API Compatibility', description: 'Point OpenAI client libraries to http://localhost:11434/v1 for drop-in local inference.' },
      { step: 3, title: 'Embedding Models & Local RAG', description: 'Pull nomic-embed-text to compute vector embeddings locally for private documents.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'main.go',
      keyFolders: [
        { path: 'server', role: 'HTTP server, streaming response handlers, and OpenAI compatibility layer.' },
        { path: 'llm', role: 'C++ bindings to llama.cpp for native GPU quantization.' },
      ],
      architecturalNotes: 'Written in Go for cross-platform process and container management, invoking optimized C++ llama.cpp inference engines for maximum tokens-per-second.',
    },
    youtubeTutorial: {
      title: 'Ollama Tutorial: Run Open Source AI Models Locally on Any Computer',
      url: 'https://www.youtube.com/watch?v=sal78ACtGTc',
      videoId: 'sal78ACtGTc',
      channel: 'NetworkChuck',
    },
    icon: 'Terminal',
  },
  {
    name: 'Open WebUI',
    repoOwner: 'open-webui',
    repoName: 'open-webui',
    githubUrl: 'https://github.com/open-webui/open-webui',
    docsUrl: 'https://docs.openwebui.com',
    description: 'User-friendly AI interface for LLMs (Formerly Ollama WebUI). Supports Ollama, OpenAI-compatible APIs, RAG, and Web Search.',
    purpose: 'Self-hosted ChatGPT-style web workspace with multi-user authentication, document chatting, live web search grounding, and voice chat.',
    whyUseIt: 'Enterprise-grade private AI portal with model switching, conversation tagging, role management, and zero telemetry.',
    category: 'AI & Machine Learning',
    techStack: ['SvelteKit', 'Python', 'FastAPI', 'ChromaDB', 'Docker'],
    language: 'Python',
    difficulty: 'Beginner',
    isBeginnerFriendly: true,
    stars: 65400,
    forks: 6900,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data ghcr.io/open-webui/open-webui:main',
    learningRoadmap: [
      { step: 1, title: 'Connect Local & Cloud Models', description: 'Configure connections to Ollama, OpenAI, Anthropic, and local vLLM instances.' },
      { step: 2, title: 'Document RAG Pipeline', description: 'Upload PDFs and inspect how ChromaDB chunks text and performs hybrid semantic search.' },
      { step: 3, title: 'Custom Pipelines & Functions', description: 'Write Python plugins to intercept user queries, filter PII, or invoke external APIs.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'backend/open_webui/main.py',
      keyFolders: [
        { path: 'src', role: 'SvelteKit frontend user interface and chat stream renderers.' },
        { path: 'backend/open_webui', role: 'FastAPI server, authentication, RAG vector pipeline, and model proxy.' },
      ],
      architecturalNotes: 'Combines a snappy SvelteKit client with a FastAPI backend that proxies SSE (Server-Sent Events) model streams cleanly to the browser.',
    },
    youtubeTutorial: {
      title: 'Open WebUI Complete Setup – The Ultimate Self-Hosted AI Interface',
      url: 'https://www.youtube.com/watch?v=sal78ACtGTc',
      videoId: 'sal78ACtGTc',
      channel: 'Techno Tim',
    },
    icon: 'MessageSquare',
  },
  {
    name: 'Browser Use',
    repoOwner: 'browser-use',
    repoName: 'browser-use',
    githubUrl: 'https://github.com/browser-use/browser-use',
    docsUrl: 'https://browser-use.com',
    description: 'Make websites accessible for AI agents. Open-source library connecting LLMs to browser automation tools like Playwright.',
    purpose: 'Enables autonomous AI agents to browse the live web, click buttons, fill forms, extract data, and book flights directly through browser interaction.',
    whyUseIt: 'Unlike raw scraping scripts, Browser Use uses multi-modal visual DOM grounding, allowing agents to understand modern dynamic SPAs, popups, and captchas.',
    category: 'AI & Machine Learning',
    techStack: ['Python', 'Playwright', 'LangChain', 'Computer Vision'],
    language: 'Python',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 31200,
    forks: 3100,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'pip install browser-use playwright\nplaywright install',
    learningRoadmap: [
      { step: 1, title: 'DOM Tree Simplification', description: 'Understand how raw HTML is reduced into an annotated visual accessibility tree for the LLM.' },
      { step: 2, title: 'Agent Action Loops', description: 'Inspect the agent cycle: observe screenshot -> plan step -> execute click/type -> verify result.' },
      { step: 3, title: 'Autonomous Research Workflow', description: 'Deploy an agent that logs into a dashboard and extracts weekly KPI metrics into a spreadsheet.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'browser_use/agent/service.py',
      keyFolders: [
        { path: 'browser_use/browser', role: 'Playwright session controller and DOM state extractor.' },
        { path: 'browser_use/agent', role: 'ReAct reasoning loop and action execution dispatchers.' },
      ],
      architecturalNotes: 'Injects custom JavaScript into the browser to highlight clickable elements with index badges, feeding screenshots and coordinates to vision models.',
    },
    youtubeTutorial: {
      title: 'Browser Use: Autonomous AI Web Navigation Tutorial',
      url: 'https://www.youtube.com/watch?v=sal78ACtGTc',
      videoId: 'sal78ACtGTc',
      channel: 'AI Jason',
    },
    icon: 'Compass',
  },

  // ==========================================
  // 7. Developer Tools & DevOps
  // ==========================================
  {
    name: 'Coolify',
    repoOwner: 'coollabsio',
    repoName: 'coolify',
    githubUrl: 'https://github.com/coollabsio/coolify',
    docsUrl: 'https://coolify.io/docs',
    description: 'An open-source & self-hostable Heroku / Netlify / Vercel alternative. Deploy apps, databases, and services to your own server.',
    purpose: 'Self-hosted Platform-as-a-Service (PaaS) that automates Git pushes, SSL certificates, Docker containers, and database provisioning on any Linux VPS.',
    whyUseIt: 'Save thousands of dollars on cloud hosting fees while keeping the push-to-deploy developer experience of Vercel or Heroku on a $5/month Hetzner or DigitalOcean droplet.',
    category: 'Developer Tools & DevOps',
    techStack: ['PHP/Laravel', 'Docker', 'Livewire', 'Traefik', 'Linux'],
    language: 'PHP',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 39800,
    forks: 2100,
    license: 'Apache-2.0',
    lastUpdated: 'Recent (Active)',
    installGuide: 'curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash',
    learningRoadmap: [
      { step: 1, title: 'Traefik Reverse Proxy & Auto-SSL', description: 'Understand how Coolify provisions Let’s Encrypt SSL certificates automatically for wildcard domains.' },
      { step: 2, title: 'Nixpacks & Dockerfile Builds', description: 'Analyze how git commits are converted into optimized container images via Nixpacks.' },
      { step: 3, title: 'One-Click Databases & Backups', description: 'Spin up managed PostgreSQL and Redis clusters with automated S3 backup snapshots.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'app/Console/Kernel.php',
      keyFolders: [
        { path: 'app/Jobs', role: 'Queue workers handling remote SSH executions and Docker daemon events.' },
        { path: 'app/Livewire', role: 'Reactive real-time dashboard UI components.' },
      ],
      architecturalNotes: 'Communicates with host Docker engines over secure local sockets and remote VPS targets via SSH keys.',
    },
    youtubeTutorial: {
      title: 'Coolify Complete Self-Hosting Guide – Leave Vercel and AWS',
      url: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
      videoId: 'Fi3AJZZregE',
      channel: 'NetworkChuck',
    },
    icon: 'Server',
  },
  {
    name: 'Grafana',
    repoOwner: 'grafana',
    repoName: 'grafana',
    githubUrl: 'https://github.com/grafana/grafana',
    docsUrl: 'https://grafana.com/docs',
    description: 'The open and composable observability and data visualization platform. Visualize metrics, logs, and traces from any source.',
    purpose: 'Visualizes time-series metrics, server health, application latencies, and distributed traces from Prometheus, InfluxDB, Elasticsearch, and SQL databases.',
    whyUseIt: 'Industry-standard observability HUD: build real-time dashboards with threshold alerts, heatmap histograms, and multi-tenant security.',
    category: 'Developer Tools & DevOps',
    techStack: ['Go (Golang)', 'TypeScript', 'React', 'Prometheus', 'SQL'],
    language: 'TypeScript',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 64200,
    forks: 12100,
    license: 'AGPL-3.0',
    lastUpdated: 'Recent (Active)',
    installGuide: 'docker run -d -p 3000:3000 --name=grafana grafana/grafana-oss',
    learningRoadmap: [
      { step: 1, title: 'Connect Prometheus Metrics Source', description: 'Query PromQL counters, gauges, and rates (http_requests_total, cpu_usage).' },
      { step: 2, title: 'Design Cyberpunk Dashboard Panels', description: 'Build interactive panels with thresholds, gradient fills, and unit formatters.' },
      { step: 3, title: 'Alerting Rules & Webhooks', description: 'Configure alert triggers that notify Discord, Slack, or PagerDuty when error rates spike.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'pkg/cmd/grafana-server',
      keyFolders: [
        { path: 'pkg', role: 'Go backend handling authentication, datasource proxies, and alerting rules engine.' },
        { path: 'public/app', role: 'React frontend featuring plugin canvas panels and visual chart engines.' },
      ],
      architecturalNotes: 'Plugin-based architecture where datasources and panel renderers are decoupled from the core Go HTTP server.',
    },
    youtubeTutorial: {
      title: 'Prometheus & Grafana Monitoring Full Course',
      url: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
      videoId: 'Fi3AJZZregE',
      channel: 'freeCodeCamp.org',
    },
    icon: 'Activity',
  },

  // ==========================================
  // 8. Mobile App Development
  // ==========================================
  {
    name: 'React Native',
    repoOwner: 'facebook',
    repoName: 'react-native',
    githubUrl: 'https://github.com/facebook/react-native',
    docsUrl: 'https://reactnative.dev',
    description: 'A framework for building native Android and iOS applications using React and JavaScript.',
    purpose: 'Allows developers to write cross-platform mobile apps in React that compile into real, native platform widgets on iOS (UIKit) and Android (View).',
    whyUseIt: 'Unified codebase for mobile platforms with high-performance native bridges, modern Fabric renderer, and instant Fast Refresh development.',
    category: 'Mobile App Development',
    techStack: ['React', 'JavaScript', 'C++', 'Java/Kotlin', 'Objective-C/Swift'],
    language: 'JavaScript',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 118000,
    forks: 24300,
    license: 'MIT',
    lastUpdated: 'Recent (Active)',
    installGuide: 'npx @react-native-community/cli@latest init MyProject',
    learningRoadmap: [
      { step: 1, title: 'Native Components & Flexbox', description: 'Understand View, Text, Image, ScrollView, and FlatList with mobile-first CSS Flexbox styling.' },
      { step: 2, title: 'Navigation with React Navigation', description: 'Implement native tab bars, stack screens, and deep links.' },
      { step: 3, title: 'Native Module Integration', description: 'Access hardware sensors (camera, geolocation, biometric auth) via native modules.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'packages/react-native',
      keyFolders: [
        { path: 'ReactAndroid', role: 'Java/Kotlin bridging and Android JNI layer.' },
        { path: 'ReactCommon/fabric', role: 'C++ cross-platform Fabric rendering pipeline.' },
      ],
      architecturalNotes: 'The New Architecture replaces JSON bridge message passing with TurboModules and direct C++ JSI (JavaScript Interface) memory access.',
    },
    youtubeTutorial: {
      title: 'React Native Crash Course – Build a Native Mobile App',
      url: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
      videoId: 'Fi3AJZZregE',
      channel: 'Traversy Media',
    },
    icon: 'Smartphone',
  },
  {
    name: 'Flutter',
    repoOwner: 'flutter',
    repoName: 'flutter',
    githubUrl: 'https://github.com/flutter/flutter',
    docsUrl: 'https://flutter.dev',
    description: 'Google’s open-source UI toolkit for building beautiful, natively compiled multi-platform applications from a single codebase.',
    purpose: 'Compiles Dart code into native ARM machine code and renders every pixel directly through the Impeller/Skia 2D graphics engine.',
    whyUseIt: 'Pixel-identical cross-platform rendering across iOS, Android, macOS, Windows, Linux, and Web with 120fps smooth animations and rich Material/Cupertino widget libraries.',
    category: 'Mobile App Development',
    techStack: ['Dart', 'C++', 'Impeller', 'Skia', 'Mobile Widgets'],
    language: 'Dart',
    difficulty: 'Intermediate',
    isBeginnerFriendly: true,
    stars: 164000,
    forks: 27100,
    license: 'BSD-3-Clause',
    lastUpdated: 'Recent (Active)',
    installGuide: 'flutter create my_app\ncd my_app && flutter run',
    learningRoadmap: [
      { step: 1, title: 'Widget Tree Composition', description: 'Master StatelessWidget vs StatefulWidget and nesting layout widgets (Column, Row, Stack).' },
      { step: 2, title: 'State Management (Riverpod / Bloc)', description: 'Structure app state predictably across screens using Riverpod or Bloc patterns.' },
      { step: 3, title: 'Custom Painters & Animations', description: 'Draw custom geometric canvases with CustomPainter and animate physics-based springs.' },
    ],
    sourceCodeExploration: {
      entryPoint: 'packages/flutter/lib/material.dart',
      keyFolders: [
        { path: 'packages/flutter/lib/src/widgets', role: 'Core declarative widget hierarchy and element lifecycle.' },
        { path: 'packages/flutter/lib/src/rendering', role: 'RenderObject tree, layout passes, and paint compositing.' },
      ],
      architecturalNotes: 'Bypasses OEM platform widgets by rendering directly to the screen buffer via the custom Impeller graphics engine.',
    },
    youtubeTutorial: {
      title: 'Flutter Tutorial for Beginners – Full 3-Hour Mobile App Course',
      url: 'https://www.youtube.com/watch?v=Fi3AJZZregE',
      videoId: 'Fi3AJZZregE',
      channel: 'freeCodeCamp.org',
    },
    icon: 'Smartphone',
  },
];
