// Part 2: AI Writing, Research & Search, Chatbots & Assistants, Voice & Audio
export const toolsPart2 = [
  // ── E. AI WRITING AND CONTENT CREATION ──
  {
    name: 'ChatGPT',
    description: 'OpenAI versatile conversational and writing model, capable of drafting essays, structuring long-form content, and creative writing.',
    category: 'Writing & Content',
    subcategory: 'AI Writer',
    website: 'https://chatgpt.com',
    pricing: 'Freemium',
    features: ['Long-form drafting', 'Style adaptation', 'Custom instructions', 'Canvas editor'],
    tags: ['writing', 'content', 'openai', 'llm'],
    platforms: ['Web', 'iOS', 'Android', 'macOS', 'Windows'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Claude',
    description: 'Anthropic frontier AI known for nuanced, articulate writing, complex synthesis, and large context comprehension.',
    category: 'Writing & Content',
    subcategory: 'AI Writer',
    website: 'https://claude.ai',
    pricing: 'Freemium',
    features: ['Artifacts live preview', 'Extended thinking', 'Nuanced prose', 'Document synthesis'],
    tags: ['writing', 'anthropic', 'research', 'editing'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Jasper',
    description: 'Enterprise AI marketing co-pilot designed to maintain brand voice across campaigns, blogs, and multi-channel content.',
    category: 'Writing & Content',
    subcategory: 'Copywriting',
    website: 'https://jasper.ai',
    pricing: 'Paid',
    features: ['Brand voice memory', 'Campaign builder', 'SEO integration', 'Team workflows'],
    tags: ['marketing', 'copywriting', 'enterprise', 'branding'],
    platforms: ['Web', 'Chrome Extension'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Copy.ai',
    description: 'AI platform for go-to-market teams automating outbound messaging, ad copy, blogs, and marketing workflows.',
    category: 'Writing & Content',
    subcategory: 'Copywriting',
    website: 'https://copy.ai',
    pricing: 'Freemium',
    features: ['GTM workflows', 'Infobase brand assets', 'Ad copy generator', 'Multilingual output'],
    tags: ['copywriting', 'gtm', 'marketing', 'sales'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Writesonic',
    description: 'AI content creation and SEO platform providing article generation, keyword optimization, and factual grounding.',
    category: 'Writing & Content',
    subcategory: 'SEO Writing',
    website: 'https://writesonic.com',
    pricing: 'Freemium',
    features: ['AI Article Writer 6', 'Real-time search data', 'Brand voice', 'Internal linking'],
    tags: ['seo', 'articles', 'content', 'blogging'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Rytr',
    description: 'Affordable, easy-to-use AI writing assistant generating blogs, emails, and social posts in 30+ languages.',
    category: 'Writing & Content',
    subcategory: 'AI Writer',
    website: 'https://rytr.me',
    pricing: 'Freemium',
    features: ['30+ languages', 'Tone selector', 'Plagiarism checker', 'Rich text editor'],
    tags: ['budget', 'copywriting', 'multilingual', 'editor'],
    platforms: ['Web', 'Chrome Extension'],
    skillLevel: 'Beginner',
    rating: 4.3,
    lastVerified: '2025-10',
  },
  {
    name: 'Grammarly',
    description: 'Comprehensive AI writing assistant providing grammar checks, tone adjustment, conciseness tips, and generative rewriting.',
    category: 'Writing & Content',
    subcategory: 'Editing & Grammar',
    website: 'https://grammarly.com',
    pricing: 'Freemium',
    features: ['Grammar & spellcheck', 'Tone detector', 'Generative rewrites', 'Plagiarism detection'],
    tags: ['grammar', 'editing', 'proofreading', 'productivity'],
    platforms: ['Web', 'Windows', 'macOS', 'Browser Extensions', 'iOS', 'Android'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'QuillBot',
    description: 'AI paraphrasing tool with grammar check, summarizer, citation generator, and translator modes.',
    category: 'Writing & Content',
    subcategory: 'Paraphrasing',
    website: 'https://quillbot.com',
    pricing: 'Freemium',
    features: ['Paraphraser modes', 'Grammar checker', 'Summarizer', 'Citation generator'],
    tags: ['paraphrase', 'summarize', 'citations', 'students'],
    platforms: ['Web', 'Word Extension', 'Chrome Extension'],
    skillLevel: 'All Levels',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Wordtune',
    description: 'AI reading and writing companion that offers context-aware rephrasing, tone shifts, and summarization.',
    category: 'Writing & Content',
    subcategory: 'Rephrasing',
    website: 'https://wordtune.com',
    pricing: 'Freemium',
    features: ['Casual & formal rewrite', 'Length expander/shortener', 'Spices continuation', 'AI reader'],
    tags: ['editing', 'rephrase', 'writing', 'clarity'],
    platforms: ['Web', 'Browser Extensions', 'Word Add-in'],
    skillLevel: 'All Levels',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'DeepL Write',
    description: 'AI-powered writing improver fixing syntax, phrasing, and tone with deep contextual accuracy.',
    category: 'Writing & Content',
    subcategory: 'Style & Grammar',
    website: 'https://deepl.com/write',
    pricing: 'Freemium',
    features: ['Style suggestions', 'Alternative words', 'European language nuances', 'Privacy guaranteed'],
    tags: ['editing', 'deepl', 'multilingual', 'style'],
    platforms: ['Web', 'Desktop Apps'],
    skillLevel: 'All Levels',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Sudowrite',
    description: 'The premier AI narrative and novel writing platform built by and for fiction authors and screenwriters.',
    category: 'Writing & Content',
    subcategory: 'Creative Writing',
    website: 'https://sudowrite.com',
    pricing: 'Paid',
    features: ['Story Bible', 'Chapter generator', 'Sensory descriptions', 'Brainstorming modes'],
    tags: ['fiction', 'novels', 'creative', 'storytelling'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Anyword',
    description: 'Performance copywriting AI platform that scores predicted engagement and conversion before publishing.',
    category: 'Writing & Content',
    subcategory: 'Conversion Copy',
    website: 'https://anyword.com',
    pricing: 'Paid',
    features: ['Predictive performance score', 'Audience targeting', 'Brand voice analyzer', 'A/B testing'],
    tags: ['copywriting', 'conversion', 'marketing', 'analytics'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.4,
    lastVerified: '2025-10',
  },
  {
    name: 'Writer',
    description: 'Enterprise generative AI platform with proprietary Palmyra LLMs, governance guardrails, and knowledge graphs.',
    category: 'Writing & Content',
    subcategory: 'Enterprise Writing',
    website: 'https://writer.com',
    pricing: 'Paid',
    features: ['Palmyra LLMs', 'Brand styleguide enforcement', 'Knowledge graph', 'Regulatory compliance'],
    tags: ['enterprise', 'compliance', 'brand', 'governance'],
    platforms: ['Web', 'Extensions', 'Figma', 'Word'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'HyperWrite',
    description: 'AI personal writing assistant with chrome-based browser automation and real-time sentence suggestions.',
    category: 'Writing & Content',
    subcategory: 'AI Assistant',
    website: 'https://hyperwriteai.com',
    pricing: 'Freemium',
    features: ['Personal AI agent', 'TypeAhead autocomplete', 'Document summarizer', 'Email replies'],
    tags: ['autocomplete', 'agent', 'browser', 'writing'],
    platforms: ['Web', 'Chrome Extension'],
    skillLevel: 'Beginner',
    rating: 4.3,
    lastVerified: '2025-10',
  },
  {
    name: 'TextCortex',
    description: 'Customizable AI co-pilot with ZenoChat integrating company knowledge bases and web search.',
    category: 'Writing & Content',
    subcategory: 'Workspace Assistant',
    website: 'https://textcortex.com',
    pricing: 'Freemium',
    features: ['ZenoChat assistant', 'Knowledge bases', 'Web search integration', 'Persona creator'],
    tags: ['productivity', 'knowledge', 'writing', 'multilingual'],
    platforms: ['Web', 'Browser Extension'],
    skillLevel: 'All Levels',
    rating: 4.4,
    lastVerified: '2025-10',
  },
  {
    name: 'Notion AI',
    description: 'Embedded AI assistant inside Notion for generating docs, extracting action items, and querying workspace data.',
    category: 'Writing & Content',
    subcategory: 'Workspace AI',
    website: 'https://notion.so/product/ai',
    pricing: 'Paid',
    features: ['Workspace Q&A', 'Document drafting', 'Table auto-fill', 'Action item extraction'],
    tags: ['notion', 'workspace', 'productivity', 'docs'],
    platforms: ['Web', 'macOS', 'Windows', 'iOS', 'Android'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Lex',
    description: 'Modern, minimalist word processor with intelligent generative AI features, feedback modes, and collaborative writing.',
    category: 'Writing & Content',
    subcategory: 'Word Processor',
    website: 'https://lex.page',
    pricing: 'Freemium',
    features: ['Ask Lex feedback', 'Title generator', 'Collaborative editor', 'Clean writing canvas'],
    tags: ['minimalist', 'editor', 'drafting', 'collaboration'],
    platforms: ['Web'],
    skillLevel: 'All Levels',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Jenni AI',
    description: 'Research and academic writing assistant with in-text citation auto-completion, paraphrase, and literature search.',
    category: 'Writing & Content',
    subcategory: 'Academic Writing',
    website: 'https://jenni.ai',
    pricing: 'Freemium',
    features: ['In-text citation builder', 'Academic tone', 'Plagiarism checking', 'Literature lookup'],
    tags: ['academic', 'research', 'citations', 'students'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'ProWritingAid',
    description: 'Deep structural manuscript editor analyzing pacing, consistency, dialogue tags, grammar, and style.',
    category: 'Writing & Content',
    subcategory: 'Manuscript Editing',
    website: 'https://prowritingaid.com',
    pricing: 'Freemium',
    features: ['20+ writing reports', 'Pacing analysis', 'Consistency checker', 'Scrivener integration'],
    tags: ['editing', 'authors', 'manuscript', 'style'],
    platforms: ['Web', 'Word', 'Scrivener', 'Chrome'],
    skillLevel: 'Intermediate',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'LanguageTool',
    description: 'Open-source and privacy-focused multilingual grammar, style, and spell checker supporting over 30 languages.',
    category: 'Writing & Content',
    subcategory: 'Grammar Checker',
    website: 'https://languagetool.org',
    pricing: 'Freemium',
    features: ['30+ languages', 'Privacy respect', 'Style recommendations', 'Open source core'],
    tags: ['privacy', 'open-source', 'grammar', 'multilingual'],
    isOpenSource: true,
    platforms: ['Web', 'Browser Extensions', 'Office', 'Desktop'],
    skillLevel: 'All Levels',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Hemingway Editor',
    description: 'Beloved readability and clarity editor with new AI features for bold, clear sentence rewriting.',
    category: 'Writing & Content',
    subcategory: 'Readability',
    website: 'https://hemingwayapp.com',
    pricing: 'Freemium',
    features: ['Readability grade level', 'Passive voice highlighter', 'AI sentence fixer', 'Conciseness tips'],
    tags: ['readability', 'clarity', 'editing', 'simplicity'],
    platforms: ['Web', 'macOS', 'Windows'],
    skillLevel: 'All Levels',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Frase',
    description: 'AI SEO content platform that analyzes top SERP competitors to generate optimized content briefs and articles.',
    category: 'Writing & Content',
    subcategory: 'SEO Writing',
    website: 'https://frase.io',
    pricing: 'Paid',
    features: ['SERP competitor analysis', 'Content briefs', 'SEO scoring', 'AI outlines'],
    tags: ['seo', 'serp', 'content-brief', 'marketing'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Scalenut',
    description: 'Comprehensive SEO content lifecycle platform offering keyword clusters, automated briefs, and Cruise Mode writing.',
    category: 'Writing & Content',
    subcategory: 'SEO Writing',
    website: 'https://scalenut.com',
    pricing: 'Paid',
    features: ['Cruise Mode generator', 'Keyword clustering', 'SEO audit', 'Traffic analyzer'],
    tags: ['seo', 'content-marketing', 'keywords', 'automation'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.4,
    lastVerified: '2025-10',
  },
  {
    name: 'Koala AI',
    description: 'High-speed AI article and blog writer powered by real-time Google search data and Amazon affiliate product roundups.',
    category: 'Writing & Content',
    subcategory: 'Blog Generator',
    website: 'https://koala.sh',
    pricing: 'Freemium',
    features: ['KoalaWriter', 'Real-time search results', 'Amazon affiliate roundups', 'KoalaChat'],
    tags: ['blogging', 'affiliate', 'seo', 'fast-writing'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },

  // ── F. AI RESEARCH AND SEARCH ──
  {
    name: 'Perplexity',
    description: 'Conversational answer engine indexing the live web in real time with verifiable citations and Pro Search reasoning.',
    category: 'Research & Search',
    subcategory: 'Search Engine',
    website: 'https://perplexity.ai',
    pricing: 'Freemium',
    features: ['Live web citations', 'Pro Search multi-step reasoning', 'Collections workspace', 'Model switching'],
    tags: ['search', 'citations', 'research', 'realtime'],
    platforms: ['Web', 'iOS', 'Android', 'macOS'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'NotebookLM',
    description: 'Google AI notebook that grounds responses exclusively in your uploaded source materials with Audio Overview podcasts.',
    category: 'Research & Search',
    subcategory: 'Source Grounding',
    website: 'https://notebooklm.google.com',
    pricing: 'Free',
    features: ['Audio Overview deep dive podcasts', 'Source grounding citations', 'Note curation', 'Multi-document synthesis'],
    tags: ['google', 'notebook', 'citations', 'podcasts'],
    platforms: ['Web'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Elicit',
    description: 'AI research assistant that automates literature reviews, synthesizes paper findings, and extracts systematic data tables.',
    category: 'Research & Search',
    subcategory: 'Academic Research',
    website: 'https://elicit.com',
    pricing: 'Freemium',
    features: ['200M+ research papers', 'Systematic table extraction', 'Synthesis summaries', 'Filter by study type'],
    tags: ['papers', 'literature-review', 'academia', 'science'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Consensus',
    description: 'AI search engine that extracts findings directly from scientific research to evaluate scientific consensus on claims.',
    category: 'Research & Search',
    subcategory: 'Academic Search',
    website: 'https://consensus.app',
    pricing: 'Freemium',
    features: ['Consensus Meter', 'Peer-reviewed evidence', 'Study quality indicators', 'Instant paper summaries'],
    tags: ['scientific', 'consensus', 'evidence', 'papers'],
    platforms: ['Web'],
    skillLevel: 'All Levels',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'SciSpace',
    description: 'End-to-end scientific platform to read, understand, and discover research papers with conversational PDF questioning.',
    category: 'Research & Search',
    subcategory: 'Paper Analysis',
    website: 'https://typeset.io',
    pricing: 'Freemium',
    features: ['Copilot for PDFs', 'Literature mapping', 'Math equation explainer', 'Multi-language paper translation'],
    tags: ['pdf', 'science', 'math', 'academic'],
    platforms: ['Web', 'Chrome Extension'],
    skillLevel: 'All Levels',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Semantic Scholar',
    description: 'Free, AI-powered academic search engine developed by the Allen Institute for AI indexing over 200 million papers.',
    category: 'Research & Search',
    subcategory: 'Academic Index',
    website: 'https://semanticscholar.org',
    pricing: 'Free',
    features: ['TLDR paper summaries', 'Citation graph insights', 'Author tracking', 'Open API'],
    tags: ['free', 'ai2', 'citations', 'papers'],
    platforms: ['Web', 'API'],
    skillLevel: 'All Levels',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'ResearchRabbit',
    description: 'Visual literature mapping tool that constructs interactive citation networks to discover related research papers.',
    category: 'Research & Search',
    subcategory: 'Literature Mapping',
    website: 'https://researchrabbitapp.com',
    pricing: 'Free',
    features: ['Interactive graph visualization', 'Zotero sync', 'Author networks', 'Personalized recommendations'],
    tags: ['visualization', 'graph', 'zotero', 'academic'],
    platforms: ['Web'],
    skillLevel: 'All Levels',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Connected Papers',
    description: 'Visual tool to find and explore academic papers connected by co-citation and bibliographic coupling in graph view.',
    category: 'Research & Search',
    subcategory: 'Graph Exploration',
    website: 'https://connectedpapers.com',
    pricing: 'Freemium',
    features: ['Visual graph of connected papers', 'Prior works identification', 'Derivative works discovery', 'Multi-disciplinary'],
    tags: ['visual-graph', 'papers', 'citations', 'literature'],
    platforms: ['Web'],
    skillLevel: 'All Levels',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Litmaps',
    description: 'Citation network visualization and paper tracking platform showing chronological progress of scientific topics.',
    category: 'Research & Search',
    subcategory: 'Literature Timeline',
    website: 'https://litmaps.com',
    pricing: 'Freemium',
    features: ['Timeline mapping', 'Automated research alerts', 'Citation overlap', 'Reference manager export'],
    tags: ['timeline', 'citations', 'research-monitoring', 'science'],
    platforms: ['Web'],
    skillLevel: 'All Levels',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Scite',
    description: 'Award-winning platform evaluating scientific papers through Smart Citations that show whether findings are supported or contrasted.',
    category: 'Research & Search',
    subcategory: 'Citation Verification',
    website: 'https://scite.ai',
    pricing: 'Paid',
    features: ['Smart Citations classification', 'Supporting/contrasting evidence', 'Reference check', 'Scite Assistant'],
    tags: ['citations', 'verification', 'evidence', 'peer-review'],
    platforms: ['Web', 'Browser Extension'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Scholarcy',
    description: 'AI-powered article summarizer that breaks research papers, book chapters, and reports into interactive summary flashcards.',
    category: 'Research & Search',
    subcategory: 'Summarization',
    website: 'https://scholarcy.com',
    pricing: 'Freemium',
    features: ['Interactive summary cards', 'Key findings extraction', 'Table and figure parsing', 'Robo-highlighter'],
    tags: ['summarizer', 'flashcards', 'reading', 'papers'],
    platforms: ['Web', 'Browser Extension'],
    skillLevel: 'All Levels',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Humata',
    description: 'AI PDF analyzer allowing users to chat with files, summarize 1000+ page documents, and extract cited data points.',
    category: 'Research & Search',
    subcategory: 'Document Q&A',
    website: 'https://humata.ai',
    pricing: 'Freemium',
    features: ['Unlimited file uploads', 'Page-level citations', 'Compare multiple documents', 'Export answers'],
    tags: ['pdf', 'document-qa', 'citations', 'enterprise'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'ChatPDF',
    description: 'Instant document chat tool that answers questions, extracts summaries, and explains concepts from uploaded PDF files.',
    category: 'Research & Search',
    subcategory: 'Document Chat',
    website: 'https://chatpdf.com',
    pricing: 'Freemium',
    features: ['Instant analysis', 'Multi-language answers', 'Source page citations', 'Shareable chats'],
    tags: ['pdf', 'students', 'quick-answers', 'free-tier'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'AskYourPDF',
    description: 'Advanced document conversational engine featuring Zotero plugin, knowledge spaces, and multi-file query synthesis.',
    category: 'Research & Search',
    subcategory: 'Document Chat',
    website: 'https://askyourpdf.com',
    pricing: 'Freemium',
    features: ['Zotero integration', 'Knowledge workspaces', 'API endpoints', 'Chrome extension'],
    tags: ['pdf', 'zotero', 'api', 'workspace'],
    platforms: ['Web', 'Chrome Extension', 'API'],
    skillLevel: 'All Levels',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Explainpaper',
    description: 'Tool designed to clarify dense academic writing by highlighting confusing passages to receive instant plain-English explanations.',
    category: 'Research & Search',
    subcategory: 'Reading Comprehension',
    website: 'https://explainpaper.com',
    pricing: 'Freemium',
    features: ['Highlight to explain', 'Adjustable explanation depth', 'Follow-up queries', 'Math notation breakdowns'],
    tags: ['reading', 'academic', 'plain-english', 'students'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.4,
    lastVerified: '2025-10',
  },
  {
    name: 'OpenAlex',
    description: 'Fully open, comprehensive catalog of the global research system with over 250 million works and detailed API access.',
    category: 'Research & Search',
    subcategory: 'Open Scientific Data',
    website: 'https://openalex.org',
    pricing: 'Free',
    features: ['250M+ scholarly records', 'Author & institution disambiguation', 'Free open API', 'Topic hierarchies'],
    tags: ['open-data', 'open-source', 'api', 'scholarly'],
    isOpenSource: true,
    platforms: ['Web', 'API'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Wolfram Alpha',
    description: 'Computational intelligence engine solving mathematical formulas, analyzing curated scientific datasets, and presenting step-by-step proofs.',
    category: 'Research & Search',
    subcategory: 'Computational Knowledge',
    website: 'https://wolframalpha.com',
    pricing: 'Freemium',
    features: ['Step-by-step solutions', 'Curated computational data', 'Symbolic math engine', 'Data visualization'],
    tags: ['mathematics', 'science', 'computation', 'stem'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Exa',
    description: 'Search engine designed specifically for AI agents and LLMs, using neural embeddings to return clean web knowledge and structured data.',
    category: 'Research & Search',
    subcategory: 'Agent Search API',
    website: 'https://exa.ai',
    pricing: 'Freemium',
    features: ['Neural semantic search', 'Clean HTML/text extraction', 'Live web crawling', 'Developer API'],
    tags: ['api', 'neural-search', 'agents', 'embeddings'],
    platforms: ['API', 'Web'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },

  // ── G. AI CHATBOTS AND ASSISTANTS ──
  {
    name: 'Microsoft Copilot',
    description: 'Everyday AI companion by Microsoft integrated into Windows, Edge, and Microsoft 365 with web grounding.',
    category: 'Chatbots & Assistants',
    subcategory: 'General Assistant',
    website: 'https://copilot.microsoft.com',
    pricing: 'Freemium',
    features: ['Web search answers', 'DALL-E image generation', 'Office 365 synergy', 'Voice interaction'],
    tags: ['microsoft', 'copilot', 'windows', 'search'],
    platforms: ['Web', 'Windows', 'iOS', 'Android'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Gemini',
    description: 'Google multimodal flagship intelligence system featuring 2M token context, native workspace sync, and real-time reasoning.',
    category: 'Chatbots & Assistants',
    subcategory: 'General Assistant',
    website: 'https://gemini.google.com',
    pricing: 'Freemium',
    features: ['2M context window', 'Google Workspace extensions', 'Deep Research mode', 'Multimodal analysis'],
    tags: ['google', 'multimodal', 'gemini', 'workspace'],
    platforms: ['Web', 'Android', 'iOS'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Grok',
    description: 'Conversational model built by xAI with real-time access to X/Twitter data and open-weights releases.',
    category: 'Chatbots & Assistants',
    subcategory: 'Real-time Assistant',
    website: 'https://x.ai',
    pricing: 'Paid',
    features: ['Live X platform knowledge', 'Fun & normal mode', 'Vision capabilities', 'Code generation'],
    tags: ['xai', 'social', 'realtime', 'grok'],
    platforms: ['Web', 'X App'],
    skillLevel: 'All Levels',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'DeepSeek',
    description: 'Open-weights reasoning model powerhouse delivering math, logic, and coding performance at groundbreaking cost efficiency.',
    category: 'Chatbots & Assistants',
    subcategory: 'Reasoning Assistant',
    website: 'https://chat.deepseek.com',
    pricing: 'Free',
    features: ['DeepSeek-R1 reasoning', 'Transparent chain-of-thought', 'Open weights', 'High coding accuracy'],
    tags: ['reasoning', 'open-weights', 'math', 'coding'],
    isOpenSource: true,
    platforms: ['Web', 'iOS', 'Android', 'API'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Mistral Le Chat',
    description: 'Conversational assistant from Mistral AI offering web search, image processing, canvas editing, and multilingual intelligence.',
    category: 'Chatbots & Assistants',
    subcategory: 'European AI Assistant',
    website: 'https://chat.mistral.ai',
    pricing: 'Freemium',
    features: ['Mistral Large models', 'Canvas mode', 'Web search grounding', 'Doc analysis'],
    tags: ['mistral', 'europe', 'privacy', 'open-weights'],
    platforms: ['Web'],
    skillLevel: 'All Levels',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Qwen Chat',
    description: 'Alibaba open-weights conversational intelligence platform with advanced reasoning, coding, and vision capabilities.',
    category: 'Chatbots & Assistants',
    subcategory: 'Multimodal Assistant',
    website: 'https://chat.qwenlm.ai',
    pricing: 'Free',
    features: ['Qwen 2.5 models', 'Long context comprehension', 'Vision & code reasoning', 'Open weights'],
    tags: ['alibaba', 'open-weights', 'multilingual', 'reasoning'],
    isOpenSource: true,
    platforms: ['Web', 'API'],
    skillLevel: 'All Levels',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Meta AI',
    description: 'AI assistant powered by Llama 3 across WhatsApp, Instagram, Messenger, and web with image creation capabilities.',
    category: 'Chatbots & Assistants',
    subcategory: 'Social Assistant',
    website: 'https://meta.ai',
    pricing: 'Free',
    features: ['Llama 3 powered', 'Real-time image generation', 'Meta apps integration', 'Free web search'],
    tags: ['meta', 'llama', 'social', 'free'],
    platforms: ['Web', 'WhatsApp', 'Instagram', 'Messenger'],
    skillLevel: 'All Levels',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Poe',
    description: 'Fast, multi-model conversational ecosystem by Quora granting access to GPT-4o, Claude 3.7, FLUX, and custom bots in one place.',
    category: 'Chatbots & Assistants',
    subcategory: 'Multi-Model Platform',
    website: 'https://poe.com',
    pricing: 'Freemium',
    features: ['Single subscription for all models', 'Bot creator monetization', 'Model comparison', 'Mobile-first'],
    tags: ['multi-model', 'quora', 'bot-creator', 'mobile'],
    platforms: ['Web', 'iOS', 'Android', 'macOS', 'Windows'],
    skillLevel: 'All Levels',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'HuggingChat',
    description: 'Open-source conversational AI interface by Hugging Face running the latest open-access models with web search.',
    category: 'Chatbots & Assistants',
    subcategory: 'Open Source Chat',
    website: 'https://huggingface.co/chat',
    pricing: 'Free',
    features: ['Open-source LLMs', 'Web search toggle', 'Custom assistant prompts', 'Community models'],
    tags: ['open-source', 'huggingface', 'privacy', 'free'],
    isOpenSource: true,
    platforms: ['Web'],
    skillLevel: 'All Levels',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'You.com',
    description: 'AI search and productivity engine offering customizable smart modes for research, coding, and comprehensive answers.',
    category: 'Chatbots & Assistants',
    subcategory: 'Search Assistant',
    website: 'https://you.com',
    pricing: 'Freemium',
    features: ['Custom AI modes', 'Multi-model access', 'Live web citations', 'Team research'],
    tags: ['search', 'research', 'citations', 'assistants'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'All Levels',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Character.AI',
    description: 'Platform hosting millions of user-created conversational personas, historical figures, and interactive roleplay companions.',
    category: 'Chatbots & Assistants',
    subcategory: 'Persona Chatbot',
    website: 'https://character.ai',
    pricing: 'Freemium',
    features: ['Custom character creation', 'Voice calls with personas', 'Group chats', 'Creative roleplay'],
    tags: ['personas', 'entertainment', 'roleplay', 'creative'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Pi',
    description: 'Emotionally intelligent, supportive conversational AI companion developed by Inflection AI for empathetic dialogue.',
    category: 'Chatbots & Assistants',
    subcategory: 'Personal Companion',
    website: 'https://pi.ai',
    pricing: 'Free',
    features: ['Empathetic dialogue', 'Realistic voice synthesis', 'Reflective coaching', 'Distraction-free interface'],
    tags: ['empathy', 'voice', 'companion', 'coaching'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Genspark',
    description: 'AI-first search engine generating custom, interactive Sparkpages synthesized across multiple sources for any query.',
    category: 'Chatbots & Assistants',
    subcategory: 'Research Agent',
    website: 'https://genspark.ai',
    pricing: 'Freemium',
    features: ['Dynamic Sparkpage generation', 'Multi-agent synthesis', 'Product comparison grids', 'Ad-free answers'],
    tags: ['search', 'sparkpages', 'agents', 'synthesis'],
    platforms: ['Web'],
    skillLevel: 'All Levels',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Kimi',
    description: 'Moonshot AI conversational model specializing in ultra-long context parsing up to 2 million Chinese and English tokens.',
    category: 'Chatbots & Assistants',
    subcategory: 'Long-Context Assistant',
    website: 'https://kimi.moonshot.cn',
    pricing: 'Freemium',
    features: ['2M context window', 'High-accuracy PDF reading', 'Web browsing', 'Financial report extraction'],
    tags: ['long-context', 'document-analysis', 'moonshot', 'research'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'All Levels',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Duck.ai',
    description: 'Privacy-first anonymous AI chat service by DuckDuckGo with zero data retention and model choice.',
    category: 'Chatbots & Assistants',
    subcategory: 'Private Chat',
    website: 'https://duckduckgo.com/chat',
    pricing: 'Free',
    features: ['Zero user tracking', 'Choice of open models', 'No signup needed', 'DuckDuckGo privacy'],
    tags: ['privacy', 'anonymous', 'free', 'duckduckgo'],
    platforms: ['Web'],
    skillLevel: 'All Levels',
    rating: 4.5,
    lastVerified: '2025-10',
  },

  // ── H. AI VOICE, SPEECH AND AUDIO ──
  {
    name: 'ElevenLabs',
    description: 'Industry benchmark generative voice platform providing emotional voice cloning, dubbing, and sound effect synthesis in 32+ languages.',
    category: 'Audio & Voice',
    subcategory: 'Voice Synthesis',
    website: 'https://elevenlabs.io',
    pricing: 'Freemium',
    features: ['Instant voice cloning', 'Emotional articulation', 'AI dubbing studio', 'Sound effects generator'],
    tags: ['tts', 'voice-cloning', 'dubbing', 'audio'],
    platforms: ['Web', 'API', 'iOS', 'Android'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Murf AI',
    description: 'Versatile AI voice studio offering 120+ lifelike voices across 20+ languages for podcasts, presentations, and video ads.',
    category: 'Audio & Voice',
    subcategory: 'Voiceover Studio',
    website: 'https://murf.ai',
    pricing: 'Freemium',
    features: ['120+ natural voices', 'Pitch & speed controls', 'Voice cloning', 'Sync with video'],
    tags: ['voiceover', 'studio', 'podcasts', 'elearning'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'PlayHT',
    description: 'High-fidelity AI text-to-speech platform with ultra-low latency streaming voice APIs and emotional human inflection.',
    category: 'Audio & Voice',
    subcategory: 'Voice API',
    website: 'https://play.ht',
    pricing: 'Freemium',
    features: ['Play3 generative model', 'Real-time conversational voice API', '900+ voices', 'Podcast hosting'],
    tags: ['tts', 'api', 'streaming', 'low-latency'],
    platforms: ['Web', 'API'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Speechify',
    description: 'Leading AI text-to-speech reading assistant that converts books, articles, and PDFs into natural audio at 4.5x speed.',
    category: 'Audio & Voice',
    subcategory: 'Audio Reader',
    website: 'https://speechify.com',
    pricing: 'Freemium',
    features: ['Celebrity voice narration', 'Scan printed pages to audio', 'Up to 4.5x reading speed', 'Cross-device sync'],
    tags: ['reader', 'tts', 'accessibility', 'productivity'],
    platforms: ['iOS', 'Android', 'macOS', 'Chrome', 'Web'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'WellSaid Labs',
    description: 'Enterprise AI voice platform providing pristine vocal consistency and studio-grade quality for training and media.',
    category: 'Audio & Voice',
    subcategory: 'Enterprise Voice',
    website: 'https://wellsaidlabs.com',
    pricing: 'Paid',
    features: ['Studio director controls', 'Phonetic spelling edits', 'Custom enterprise avatars', 'Commercial license'],
    tags: ['enterprise', 'training', 'professional', 'voiceover'],
    platforms: ['Web', 'API'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'LOVO',
    description: 'AI voice generator and video editor with Genny, offering 500+ voices, auto-subtitles, and stock media.',
    category: 'Audio & Voice',
    subcategory: 'Voiceover Studio',
    website: 'https://lovo.ai',
    pricing: 'Freemium',
    features: ['500+ voices in 100+ languages', 'Granular emotion controls', 'Integrated video timeline', 'AI scriptwriter'],
    tags: ['video-editing', 'voiceover', 'emotions', 'multilingual'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Resemble AI',
    description: 'Generative audio platform offering hyper-realistic custom voice cloning, audio watermarking, and real-time deepfake detection.',
    category: 'Audio & Voice',
    subcategory: 'Voice Security',
    website: 'https://resemble.ai',
    pricing: 'Paid',
    features: ['Neural speech watermarking', 'Deepfake detection', 'Real-time voice conversion', 'Granular emotion modulation'],
    tags: ['voice-cloning', 'security', 'watermark', 'deepfake-detection'],
    platforms: ['Web', 'API'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Cartesia',
    description: 'Next-generation ultra-fast voice foundation models with under 100ms latency designed for interactive AI voice agents.',
    category: 'Audio & Voice',
    subcategory: 'Realtime Voice Model',
    website: 'https://cartesia.ai',
    pricing: 'Paid',
    features: ['Sonic foundation model', 'Sub-100ms latency', 'Stateful audio generation', 'Developer API'],
    tags: ['low-latency', 'voice-agents', 'realtime', 'api'],
    platforms: ['API'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Deepgram',
    description: 'High-speed, cost-effective speech-to-text and text-to-speech API powering conversational AI products with Nova-3.',
    category: 'Audio & Voice',
    subcategory: 'Speech API',
    website: 'https://deepgram.com',
    pricing: 'Freemium',
    features: ['Nova-3 transcription', 'Aura fast TTS', 'Live audio streaming', 'Domain customization'],
    tags: ['stt', 'tts', 'developer-api', 'transcription'],
    platforms: ['API'],
    skillLevel: 'Intermediate',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'AssemblyAI',
    description: 'Production-ready speech AI APIs offering speech-to-text, speaker diarization, sentiment analysis, and audio summarization.',
    category: 'Audio & Voice',
    subcategory: 'Speech Intelligence',
    website: 'https://assemblyai.com',
    pricing: 'Freemium',
    features: ['Universal-2 transcription', 'Speaker diarization', 'LeMUR LLM audio reasoning', 'PII redaction'],
    tags: ['speech-to-text', 'diarization', 'api', 'intelligence'],
    platforms: ['API'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'OpenAI Whisper',
    description: 'State-of-the-art open-source automatic speech recognition model trained on 680,000 hours of multilingual audio data.',
    category: 'Audio & Voice',
    subcategory: 'Open Speech Recognition',
    website: 'https://github.com/openai/whisper',
    pricing: 'Open Source',
    features: ['Robust open-source STT', 'Multilingual transcription', 'English translation', 'Offline local execution'],
    tags: ['open-source', 'stt', 'openai', 'local-run'],
    isOpenSource: true,
    platforms: ['Python', 'Local', 'API'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Krisp',
    description: 'On-device AI voice clarity app that eliminates background noise, echo, and chatter in real-time during live calls.',
    category: 'Audio & Voice',
    subcategory: 'Noise Cancellation',
    website: 'https://krisp.ai',
    pricing: 'Freemium',
    features: ['Bidirectional noise removal', 'Acoustic echo cancellation', 'Meeting transcription', 'Call bot integration'],
    tags: ['noise-cancellation', 'calls', 'meetings', 'zoom'],
    platforms: ['Windows', 'macOS'],
    skillLevel: 'Beginner',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Adobe Podcast',
    description: 'Web-based audio recording and enhancement suite featuring AI speech enhancement that makes microphone recordings sound studio-grade.',
    category: 'Audio & Voice',
    subcategory: 'Audio Enhancement',
    website: 'https://podcast.adobe.com',
    pricing: 'Freemium',
    features: ['Enhanced Speech filter', 'Mic Check tool', 'Web recording studio', 'Text-based audio editing'],
    tags: ['adobe', 'podcast', 'audio-cleaning', 'studio-sound'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Auphonic',
    description: 'Automated post-production audio mastering service handling loudness normalization, noise gating, and leveler algorithms.',
    category: 'Audio & Voice',
    subcategory: 'Audio Mastering',
    website: 'https://auphonic.com',
    pricing: 'Freemium',
    features: ['LUFS loudness normalization', 'Multitrack algorithm', 'Whisper auto-transcription', 'Metadata distribution'],
    tags: ['mastering', 'podcasting', 'loudness', 'post-production'],
    platforms: ['Web', 'API'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Moises',
    description: 'AI music platform separating vocal and instrumental stems, detecting pitch/chords, and mastering tracks for musicians.',
    category: 'Audio & Voice',
    subcategory: 'Stem Separation',
    website: 'https://moises.ai',
    pricing: 'Freemium',
    features: ['AI stem separation', 'Chord and key detection', 'Metronome smart BPM', 'Voice mastering'],
    tags: ['musicians', 'stems', 'audio-separation', 'practice'],
    platforms: ['Web', 'iOS', 'Android', 'Desktop'],
    skillLevel: 'All Levels',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Lalal.ai',
    description: 'High-precision vocal remover and stem extraction service isolating voice, drums, bass, guitar, and synth tracks.',
    category: 'Audio & Voice',
    subcategory: 'Stem Separation',
    website: 'https://lalal.ai',
    pricing: 'Freemium',
    features: ['Orion neural network', 'Voice cleaner', 'Vocal and instrument split', 'Lossless audio support'],
    tags: ['stem-splitter', 'vocals', 'mixing', 'audio-cleaner'],
    platforms: ['Web', 'macOS', 'Windows', 'iOS', 'Android'],
    skillLevel: 'All Levels',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'VocalRemover.org',
    description: 'Free online browser tool that separates song vocals from music using AI algorithms with zero installation.',
    category: 'Audio & Voice',
    subcategory: 'Free Stem Splitter',
    website: 'https://vocalremover.org',
    pricing: 'Free',
    features: ['Instant vocal removal', 'Karaoke track creator', 'BPM and key finder', 'Audio cutter/joiner'],
    tags: ['free', 'karaoke', 'stem-splitter', 'browser'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
];
