// Part 3: AI Music, Graphic Design/UI/UX, Automation & Agents, Data Analytics, Marketing & SEO
export const toolsPart3 = [
  // ── I. AI MUSIC AND SOUND DESIGN ──
  {
    name: 'Suno',
    description: 'Generates full-length radio-quality songs with expressive vocals, lyrics, instrumentation, and arrangement across any genre.',
    category: 'Music & Sound',
    subcategory: 'AI Music Generator',
    website: 'https://suno.com',
    pricing: 'Freemium',
    features: ['Full song synthesis', 'Custom lyrics input', 'Vocal style direction', 'Stem audio export'],
    tags: ['music', 'songs', 'vocals', 'audio'],
    platforms: ['Web', 'iOS'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Udio',
    description: 'Groundbreaking AI music creation tool known for musical fidelity, natural vocal cadence, and song extension controls.',
    category: 'Music & Sound',
    subcategory: 'AI Music Generator',
    website: 'https://udio.com',
    pricing: 'Freemium',
    features: ['High-fidelity audio synthesis', 'Song section extensions', 'Lyric timing editor', 'Remixing features'],
    tags: ['music', 'udio', 'generation', 'composition'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'AIVA',
    description: 'AI soundtrack and orchestral composition engine used by video game studios, film directors, and composers.',
    category: 'Music & Sound',
    subcategory: 'Composition & Scoring',
    website: 'https://aiva.ai',
    pricing: 'Freemium',
    features: ['MIDI export & editing', '250+ musical styles', 'Full copyright ownership plans', 'Orchestral scoring'],
    tags: ['soundtrack', 'midi', 'orchestra', 'gaming'],
    platforms: ['Web', 'Desktop'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Soundraw',
    description: 'Royalty-free music generator empowering content creators to customize tempo, mood, instruments, and track duration.',
    category: 'Music & Sound',
    subcategory: 'Royalty-Free Music',
    website: 'https://soundraw.io',
    pricing: 'Freemium',
    features: ['Granular song section editing', 'Mood and genre matching', 'Royalty-free licensing', 'Video sync playback'],
    tags: ['royalty-free', 'youtube', 'bgm', 'creators'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Beatoven.ai',
    description: 'AI background music generator that uses emotion-driven composition to create soundtrack music for videos and podcasts.',
    category: 'Music & Sound',
    subcategory: 'Background Score',
    website: 'https://beatoven.ai',
    pricing: 'Freemium',
    features: ['Mood-based scene tagging', 'Cut-by-cut music customization', 'Royalty-free perpetual license', 'Stem download'],
    tags: ['podcasts', 'video-score', 'mood-music', 'licensing'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Boomy',
    description: 'Democratized AI music generator allowing anyone to create original songs in seconds and submit them directly to streaming platforms.',
    category: 'Music & Sound',
    subcategory: 'Instant Song Maker',
    website: 'https://boomy.com',
    pricing: 'Freemium',
    features: ['Instant track generation', 'Streaming distribution to Spotify/Apple', 'Custom vocal recording', 'Royalties tracking'],
    tags: ['instant-music', 'distribution', 'streaming', 'monetization'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.3,
    lastVerified: '2025-10',
  },
  {
    name: 'Loudly',
    description: 'AI music platform featuring thousands of musical stems, customizable genre formulas, and royalty-free music generation.',
    category: 'Music & Sound',
    subcategory: 'Music Synthesis',
    website: 'https://loudly.com',
    pricing: 'Freemium',
    features: ['Genre formula engine', 'High quality mastering', 'Stem separation', 'Commercial license'],
    tags: ['creators', 'music-generator', 'stems', 'commercial'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.4,
    lastVerified: '2025-10',
  },
  {
    name: 'Stable Audio',
    description: 'Stability AI diffusion model trained for generating music, audio textures, and sound effects up to 3 minutes in stereo.',
    category: 'Music & Sound',
    subcategory: 'Audio Diffusion',
    website: 'https://stableaudio.com',
    pricing: 'Freemium',
    features: ['44.1kHz stereo audio', 'Prompt-guided sound FX', 'Musical style prompt adherence', 'Audio-to-audio variation'],
    tags: ['stability', 'diffusion', 'sound-fx', 'stereo'],
    platforms: ['Web', 'API'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Mubert',
    description: 'Generative streaming music ecosystem producing endless real-time royalty-free soundtracks for apps, streamers, and games.',
    category: 'Music & Sound',
    subcategory: 'Generative Streaming',
    website: 'https://mubert.com',
    pricing: 'Freemium',
    features: ['Mubert Render API', 'Live stream BGM plugin', 'Text-to-music generation', 'Artist revenue share model'],
    tags: ['streaming', 'twitch', 'api', 'endless-audio'],
    platforms: ['Web', 'API'],
    skillLevel: 'Intermediate',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Soundful',
    description: 'Studio-grade generative AI music platform producing high-resolution tracks and stems for producers and creators.',
    category: 'Music & Sound',
    subcategory: 'Production Music',
    website: 'https://soundful.com',
    pricing: 'Freemium',
    features: ['Full stem downloads', 'MIDI downloads', 'One-click monetization license', 'BPM and key matching'],
    tags: ['production', 'stems', 'midi', 'studio'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Riffusion',
    description: 'Real-time music creation app transforming visual audio spectrograms into musical loops, riffs, and lyrics.',
    category: 'Music & Sound',
    subcategory: 'Spectrogram Synthesis',
    website: 'https://riffusion.com',
    pricing: 'Free',
    features: ['Spectrogram diffusion', 'Lyric prompting', 'Loop generation', 'Community sharing'],
    tags: ['spectrogram', 'open-model', 'loops', 'riff'],
    isOpenSource: true,
    platforms: ['Web', 'iOS'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'BandLab SongStarter',
    description: 'AI musical idea generator providing royalty-free instrumental starter ideas and beat concepts directly within BandLab DAW.',
    category: 'Music & Sound',
    subcategory: 'Beat Starter',
    website: 'https://bandlab.com/songstarter',
    pricing: 'Free',
    features: ['Instant beat ideas', 'Seamless DAW import', 'FX manipulation', 'Mobile production'],
    tags: ['daw', 'mobile-music', 'beatmaking', 'free'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Kits AI',
    description: 'AI voice platform for music producers offering licensed artist vocal models, vocal training, and studio vocal transformation.',
    category: 'Music & Sound',
    subcategory: 'Voice Modeling',
    website: 'https://kits.ai',
    pricing: 'Freemium',
    features: ['Official artist voice models', 'Custom model training', 'Vocal separator', 'Pitch correction'],
    tags: ['singing-voice', 'vocal-cloning', 'music-production', 'vst'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'AudioShake',
    description: 'Award-winning AI audio isolation platform separating dialogue, instruments, and vocals for sync licensing and spatial audio.',
    category: 'Music & Sound',
    subcategory: 'Spatial & Stem Separation',
    website: 'https://audioshake.ai',
    pricing: 'Contact',
    features: ['Spatial audio stems', 'Sync licensing prep', 'Lyric transcription sync', 'Indie and enterprise API'],
    tags: ['industry-standard', 'stems', 'spatial-audio', 'licensing'],
    platforms: ['Web', 'API'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },

  // ── J. AI GRAPHIC DESIGN AND UI/UX ──
  {
    name: 'Figma AI',
    description: 'Intelligent design assistant embedded into Figma that generates UI components, renames layers, and replaces mock text.',
    category: 'Design & UI/UX',
    subcategory: 'UI Design Tool',
    website: 'https://figma.com',
    pricing: 'Freemium',
    features: ['First-draft UI generation', 'Automated layer renaming', 'Contextual image generation', 'Realistic dummy data'],
    tags: ['figma', 'ui', 'ux', 'product-design'],
    platforms: ['Web', 'macOS', 'Windows'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Relume',
    description: 'AI website architecture builder generating sitemaps and wireframe design systems exportable directly to Figma and Webflow.',
    category: 'Design & UI/UX',
    subcategory: 'Wireframing & Sitemaps',
    website: 'https://relume.io',
    pricing: 'Freemium',
    features: ['AI sitemap generation', 'Component wireframing', 'Direct Webflow export', 'Figma design kit sync'],
    tags: ['wireframes', 'sitemaps', 'webflow', 'figma'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Visily',
    description: 'AI wireframing and prototyping software transforming hand-drawn sketches, screenshots, and prompts into modern UI wireframes.',
    category: 'Design & UI/UX',
    subcategory: 'Rapid Wireframing',
    website: 'https://visily.ai',
    pricing: 'Freemium',
    features: ['Sketch to wireframe', 'Screenshot scanner to UI', 'Pre-built component library', 'Smart design assistant'],
    tags: ['wireframing', 'prototyping', 'sketch-to-code', 'ui'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Khroma',
    description: 'AI color tool for designers that learns your personal color preferences and generates endless curated harmonious palettes.',
    category: 'Design & UI/UX',
    subcategory: 'Color Palettes',
    website: 'https://khroma.co',
    pricing: 'Free',
    features: ['Neural personalized color engine', 'Palette combinations', 'Typography test displays', 'WCAG contrast scores'],
    tags: ['color', 'palette', 'design-tokens', 'free'],
    platforms: ['Web'],
    skillLevel: 'All Levels',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Looka',
    description: 'AI brand identity maker that generates custom logos, business cards, typography pairings, and full brand guideline kits.',
    category: 'Design & UI/UX',
    subcategory: 'Logo & Branding',
    website: 'https://looka.com',
    pricing: 'Freemium',
    features: ['AI logo designer', 'Brand identity guidelines', 'Social media kits', 'Vector SVG exports'],
    tags: ['logo', 'branding', 'identity', 'vector'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Designs.ai',
    description: 'All-in-one creative suite leveraging AI to design logos, videos, banners, and mockups in minutes.',
    category: 'Design & UI/UX',
    subcategory: 'Design Suite',
    website: 'https://designs.ai',
    pricing: 'Paid',
    features: ['Logomaker', 'Videomaker', 'Designmaker', 'Color matcher'],
    tags: ['creative-suite', 'banners', 'marketing-assets', 'mockups'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.4,
    lastVerified: '2025-10',
  },
  {
    name: 'Motiff',
    description: 'AI-first collaborative UI design tool featuring AI duplication, consistency checkers, and design system governance.',
    category: 'Design & UI/UX',
    subcategory: 'UI Design Tool',
    website: 'https://motiff.com',
    pricing: 'Freemium',
    features: ['AI duplication', 'Design system scanner', 'Component auto-grouping', 'Figma file compatibility'],
    tags: ['ui', 'ux', 'design-system', 'prototyping'],
    platforms: ['Web', 'macOS', 'Windows'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Spline',
    description: 'Collaborative 3D design and web interaction tool with generative AI for 3D modeling, texturing, and physics simulation.',
    category: 'Design & UI/UX',
    subcategory: '3D Web Design',
    website: 'https://spline.design',
    pricing: 'Freemium',
    features: ['Prompt to 3D generation', 'Web interactive embeds', 'Physics and animations', 'React & Three.js export'],
    tags: ['3d', 'webgl', 'interactive', 'animations'],
    platforms: ['Web', 'macOS', 'Windows'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Dora',
    description: 'AI website designer delivering 3D animated landing pages with interactive models and scroll-triggered camera motions without coding.',
    category: 'Design & UI/UX',
    subcategory: '3D Web Builder',
    website: 'https://dora.run',
    pricing: 'Freemium',
    features: ['Text-to-3D website builder', 'Interactive 3D models', 'Keyframe scroll animations', 'Custom domain publish'],
    tags: ['3d', 'landing-pages', 'animations', 'nocode'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Microsoft Designer',
    description: 'AI graphic design app creating social posts, invitations, stickers, and banners powered by DALL-E and Microsoft models.',
    category: 'Design & UI/UX',
    subcategory: 'Graphic Creator',
    website: 'https://designer.microsoft.com',
    pricing: 'Free',
    features: ['Prompt-to-design templates', 'Generative erase and expand', 'Sticker and badge maker', 'Social size resize'],
    tags: ['microsoft', 'social-media', 'banners', 'free'],
    platforms: ['Web', 'Windows', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Adobe Express',
    description: 'Quick-creation design app integrated with Adobe Firefly generative AI for instant graphics, flyers, and animations.',
    category: 'Design & UI/UX',
    subcategory: 'Graphic Creator',
    website: 'https://express.adobe.com',
    pricing: 'Freemium',
    features: ['Firefly text-to-image', 'Generative fill and text effects', 'One-click resize', 'Adobe Stock library sync'],
    tags: ['adobe', 'social-graphics', 'flyers', 'templates'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Kittl',
    description: 'Next-generation graphic design tool built for merchandise, t-shirts, vintage badges, and complex typography illustrations.',
    category: 'Design & UI/UX',
    subcategory: 'Illustration & Print',
    website: 'https://kittl.com',
    pricing: 'Freemium',
    features: ['AI vector generator', 'Text transform warping', 'Print-on-demand mockups', 'Vintage badge templates'],
    tags: ['print', 'typography', 'vector', 'apparel'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },

  // ── K. AI AUTOMATION AND AGENTS ──
  {
    name: 'n8n',
    description: 'Fair-code workflow automation platform with native AI agent nodes, vector store integrations, and self-hosted privacy.',
    category: 'Automation & Agents',
    subcategory: 'Workflow Automation',
    website: 'https://n8n.io',
    pricing: 'Freemium',
    features: ['AI Agent and LLM chain nodes', 'Self-hostable open source core', '500+ pre-built integrations', 'Custom JavaScript/Python'],
    tags: ['automation', 'agents', 'open-source', 'self-hosted'],
    isOpenSource: true,
    platforms: ['Self-hosted', 'Cloud', 'Docker'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Zapier',
    description: 'The market leader in no-code app integration with Zapier Central and AI actions connecting over 6,000 SaaS platforms.',
    category: 'Automation & Agents',
    subcategory: 'Integration Platform',
    website: 'https://zapier.com',
    pricing: 'Freemium',
    features: ['6,000+ app connectors', 'Zapier Central AI bots', 'AI custom logic steps', 'Interfaces and tables'],
    tags: ['integration', 'no-code', 'workflows', 'saas'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Dify',
    description: 'Open-source LLM application development platform uniting backend-as-a-service with agentic workflow visual orchestration.',
    category: 'Automation & Agents',
    subcategory: 'Agent Orchestration',
    website: 'https://dify.ai',
    pricing: 'Freemium',
    features: ['Visual prompt engineering', 'Agent workflows', 'RAG pipeline builder', 'Enterprise self-hosting'],
    tags: ['open-source', 'rag', 'llm-ops', 'agents'],
    isOpenSource: true,
    platforms: ['Web', 'Self-hosted', 'Docker'],
    skillLevel: 'Intermediate',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Flowise',
    description: 'Open-source drag-and-drop UI to build customized LLM flows, autonomous agents, and LangChain applications.',
    category: 'Automation & Agents',
    subcategory: 'Visual LLM Builder',
    website: 'https://flowiseai.com',
    pricing: 'Open Source',
    features: ['Drag & drop nodes', 'LangChain & LlamaIndex support', 'Vector DB connectors', 'Embeddable chat widget'],
    tags: ['open-source', 'langchain', 'no-code', 'developer'],
    isOpenSource: true,
    platforms: ['Self-hosted', 'Docker', 'Cloud'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Langflow',
    description: 'Visual framework for building multi-agent AI systems and RAG pipelines with effortless Python and LangChain export.',
    category: 'Automation & Agents',
    subcategory: 'Visual Agent Builder',
    website: 'https://langflow.org',
    pricing: 'Open Source',
    features: ['Component canvas', 'Python code generation', 'API endpoint creation', 'Pre-configured templates'],
    tags: ['open-source', 'python', 'agents', 'langchain'],
    isOpenSource: true,
    platforms: ['Self-hosted', 'Docker', 'Web'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Lindy',
    description: 'Autonomous AI employee platform capable of handling calendar triage, email drafting, meeting notes, and sales outreach.',
    category: 'Automation & Agents',
    subcategory: 'AI Teammate',
    website: 'https://lindy.ai',
    pricing: 'Freemium',
    features: ['Pre-built assistant personas', 'Calendar & email autonomy', '3,000+ app triggers', 'Custom agent builder'],
    tags: ['ai-employee', 'executive-assistant', 'inbox', 'scheduling'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Gumloop',
    description: 'Visual AI workflow builder designed to automate complex, multi-step browser tasks, scraping, and LLM data enrichment.',
    category: 'Automation & Agents',
    subcategory: 'AI Web Scraping & Flow',
    website: 'https://gumloop.com',
    pricing: 'Freemium',
    features: ['Web scraping nodes', 'Bulk document processing', 'Multi-model chaining', 'Scheduled cron triggers'],
    tags: ['scraping', 'workflows', 'data-enrichment', 'automation'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Relevance AI',
    description: 'Build and deploy a fleet of autonomous B2B AI agents that run research, lead qualification, and customer support tasks.',
    category: 'Automation & Agents',
    subcategory: 'AI Workforce',
    website: 'https://relevanceai.com',
    pricing: 'Freemium',
    features: ['B2B autonomous agents', 'Multi-agent collaboration', 'Custom tool creation', 'Detailed execution audit'],
    tags: ['b2b', 'workforce', 'multi-agent', 'sales-ops'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Bardeen',
    description: 'Browser-based workflow automation extension combining web scraping, CRM data entry, and AI shortcuts with one click.',
    category: 'Automation & Agents',
    subcategory: 'Browser Automation',
    website: 'https://bardeen.ai',
    pricing: 'Freemium',
    features: ['No-code web scraper', 'Magic Box prompt automation', 'Contextual page actions', 'CRM and Notion sync'],
    tags: ['browser', 'extension', 'scraping', 'productivity'],
    platforms: ['Chrome Extension'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Activepieces',
    description: 'Open-source, self-hostable business automation platform built as an extensible alternative to Zapier.',
    category: 'Automation & Agents',
    subcategory: 'Open Source Automation',
    website: 'https://activepieces.com',
    pricing: 'Freemium',
    features: ['TypeScript piece framework', 'Self-hostable privacy', 'Visual workflow editor', 'Community connectors'],
    tags: ['open-source', 'self-host', 'typescript', 'privacy'],
    isOpenSource: true,
    platforms: ['Web', 'Self-hosted', 'Docker'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Pipedream',
    description: 'Serverless integration platform for developers to connect APIs with code-level control and pre-built triggers.',
    category: 'Automation & Agents',
    subcategory: 'Developer Integration',
    website: 'https://pipedream.com',
    pricing: 'Freemium',
    features: ['Node.js & Python code steps', 'Thousands of pre-built actions', 'Serverless execution', 'State persistence'],
    tags: ['developer', 'serverless', 'api', 'code-level'],
    platforms: ['Web'],
    skillLevel: 'Advanced',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'CrewAI',
    description: 'Leading open-source framework for orchestrating role-playing autonomous AI agents collaborating to solve complex tasks.',
    category: 'Automation & Agents',
    subcategory: 'Multi-Agent Framework',
    website: 'https://crewai.com',
    pricing: 'Open Source',
    features: ['Role-based agent design', 'Hierarchical & sequential processes', 'Tool delegation', 'CrewAI Enterprise platform'],
    tags: ['open-source', 'python', 'multi-agent', 'orchestration'],
    isOpenSource: true,
    platforms: ['Python', 'Cloud'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'AutoGen',
    description: 'Microsoft Research framework enabling multi-agent conversation systems that can work together with human feedback.',
    category: 'Automation & Agents',
    subcategory: 'Multi-Agent Framework',
    website: 'https://microsoft.github.io/autogen',
    pricing: 'Open Source',
    features: ['Conversable agent architecture', 'Code execution sandboxes', 'Human-in-the-loop', 'AutoGen Studio UI'],
    tags: ['microsoft', 'open-source', 'research', 'multi-agent'],
    isOpenSource: true,
    platforms: ['Python', 'Local'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'LangGraph',
    description: 'Library by LangChain for building cyclic, stateful multi-agent workflows with persistence, time-travel, and human approval.',
    category: 'Automation & Agents',
    subcategory: 'Stateful Agent Graphs',
    website: 'https://langchain-ai.github.io/langgraph',
    pricing: 'Open Source',
    features: ['Cyclic graph orchestration', 'Built-in memory persistence', 'Human-in-the-loop pause/resume', 'LangGraph Studio'],
    tags: ['langchain', 'state-machine', 'cyclic-graphs', 'production'],
    isOpenSource: true,
    platforms: ['Python', 'TypeScript', 'Cloud'],
    skillLevel: 'Advanced',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },

  // ── L. AI DATA ANALYTICS AND BUSINESS INTELLIGENCE ──
  {
    name: 'Julius AI',
    description: 'Powerful AI data scientist that analyzes spreadsheets, executes Python calculations, and generates publication-grade charts.',
    category: 'Data & Analytics',
    subcategory: 'AI Data Analyst',
    website: 'https://julius.ai',
    pricing: 'Freemium',
    features: ['Excel & CSV data modeling', 'Python code sandbox execution', 'Predictive regressions', 'Interactive visualizations'],
    tags: ['data-science', 'spreadsheets', 'charts', 'python'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Power BI Copilot',
    description: 'Microsoft conversational intelligence inside Power BI that auto-generates visual reports, DAX calculations, and narrative summaries.',
    category: 'Data & Analytics',
    subcategory: 'Enterprise BI',
    website: 'https://powerbi.microsoft.com',
    pricing: 'Paid',
    features: ['Natural language report generation', 'Automated DAX formulas', 'Executive summary cards', 'Semantic model search'],
    tags: ['microsoft', 'powerbi', 'enterprise', 'reporting'],
    platforms: ['Windows', 'Web'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Tableau AI',
    description: 'Tableau Pulse and generative co-pilot delivering personalized metric digests and conversational data exploration.',
    category: 'Data & Analytics',
    subcategory: 'Enterprise BI',
    website: 'https://tableau.com',
    pricing: 'Paid',
    features: ['Tableau Pulse digest', 'Calculated field assistant', 'Automated anomaly detection', 'Natural language queries'],
    tags: ['salesforce', 'tableau', 'dashboards', 'metrics'],
    platforms: ['Web', 'Desktop'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'ThoughtSpot',
    description: 'Search and AI-driven analytics platform allowing any business user to query live data clouds using natural conversation.',
    category: 'Data & Analytics',
    subcategory: 'Search-Driven Analytics',
    website: 'https://thoughtspot.com',
    pricing: 'Paid',
    features: ['SpotIQ AI insights', 'Natural language search on SQL', 'Embeddable Liveboards', 'Direct Snowflake connection'],
    tags: ['thoughtspot', 'liveboards', 'cloud-data', 'search'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Hex',
    description: 'Collaborative data workspace uniting SQL, Python, R, and AI for exploratory data science and interactive app building.',
    category: 'Data & Analytics',
    subcategory: 'Data Workspace',
    website: 'https://hex.tech',
    pricing: 'Freemium',
    features: ['Hex Magic AI assistant', 'SQL & Python interoperability', 'Interactive data apps', 'Team version control'],
    tags: ['python', 'sql', 'notebooks', 'collaboration'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Dataiku',
    description: 'Everyday AI and machine learning governance platform orchestrating data pipelines from preparation to MLOps deployment.',
    category: 'Data & Analytics',
    subcategory: 'Enterprise Data Science',
    website: 'https://dataiku.com',
    pricing: 'Paid',
    features: ['Visual data preparation', 'AutoML model training', 'Generative AI LLM mesh', 'Enterprise governance'],
    tags: ['enterprise', 'automl', 'governance', 'pipelines'],
    platforms: ['Web', 'Enterprise Server'],
    skillLevel: 'Advanced',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Akkio',
    description: 'No-code AI analytics platform enabling agencies and marketing teams to predict churn, forecast sales, and clean data.',
    category: 'Data & Analytics',
    subcategory: 'No-Code Predictive AI',
    website: 'https://akkio.com',
    pricing: 'Paid',
    features: ['Chat with data tables', 'Predictive modeling in minutes', 'Live dashboard reporting', 'BigQuery sync'],
    tags: ['no-code', 'predictive', 'agencies', 'forecasting'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Rows',
    description: 'The modern AI-augmented spreadsheet connecting with 50+ integrations and providing built-in AI analyst formulas.',
    category: 'Data & Analytics',
    subcategory: 'AI Spreadsheet',
    website: 'https://rows.com',
    pricing: 'Freemium',
    features: ['AI Analyst answers', 'Built-in web enrichments', 'Interactive sharing', 'Live API integrations'],
    tags: ['spreadsheet', 'excel-alternative', 'enrichment', 'visualizations'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Sigma',
    description: 'Cloud analytics spreadsheet interface queryable at massive scale directly against Snowflake, BigQuery, and Databricks.',
    category: 'Data & Analytics',
    subcategory: 'Cloud Scale Analytics',
    website: 'https://sigmacomputing.com',
    pricing: 'Paid',
    features: ['Spreadsheet UI for SQL databases', 'AI formula writing', 'Direct cloud warehouse query', 'Zero data extracts'],
    tags: ['cloud-warehouse', 'snowflake', 'bigquery', 'spreadsheet-ui'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Databricks Assistant',
    description: 'Context-aware AI pair programmer inside Databricks Lakehouse generating PySpark, SQL queries, and debugging execution plans.',
    category: 'Data & Analytics',
    subcategory: 'Lakehouse AI Assistant',
    website: 'https://databricks.com',
    pricing: 'Paid',
    features: ['PySpark code generation', 'Data error auto-fix', 'Data catalog context', 'Lakehouse optimization'],
    tags: ['databricks', 'spark', 'lakehouse', 'big-data'],
    platforms: ['Web'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Snowflake Cortex',
    description: 'Fully managed AI and ML service inside Snowflake allowing instant access to frontier LLMs and vector search on your data.',
    category: 'Data & Analytics',
    subcategory: 'Cloud Warehouse AI',
    website: 'https://snowflake.com',
    pricing: 'Paid',
    features: ['Serverless LLM SQL functions', 'Cortex Search vector engine', 'Snowflake Copilot', 'Enterprise data boundary'],
    tags: ['snowflake', 'cortex', 'sql-ai', 'vector-search'],
    platforms: ['Cloud'],
    skillLevel: 'Advanced',
    rating: 4.7,
    lastVerified: '2025-10',
  },

  // ── M. AI MARKETING, SEO AND SOCIAL MEDIA ──
  {
    name: 'Semrush',
    description: 'Leading digital marketing suite with AI Copilot, content analyzer, keyword magic tool, and competitor intelligence.',
    category: 'Marketing & SEO',
    subcategory: 'SEO Intelligence',
    website: 'https://semrush.com',
    pricing: 'Paid',
    features: ['AI Copilot recommendations', 'Keyword Magic Tool', 'Backlink gap analysis', 'Position tracker'],
    tags: ['seo', 'semrush', 'keywords', 'competitors'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Ahrefs',
    description: 'Comprehensive SEO toolset with AI content helper, SERP overview insights, and industry-benchmark backlink index.',
    category: 'Marketing & SEO',
    subcategory: 'SEO & Backlinks',
    website: 'https://ahrefs.com',
    pricing: 'Paid',
    features: ['Site Explorer 2', 'AI keyword generator', 'Content Explorer', 'Rank Tracker'],
    tags: ['ahrefs', 'backlinks', 'seo', 'rank-tracker'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Surfer SEO',
    description: 'On-page optimization tool analyzing 500+ SERP ranking factors to give real-time content scoring guidelines.',
    category: 'Marketing & SEO',
    subcategory: 'On-Page SEO',
    website: 'https://surferseo.com',
    pricing: 'Paid',
    features: ['Content Score meter', 'Surfer AI article writer', 'Keyword research clusters', 'Audit tool'],
    tags: ['on-page-seo', 'content-score', 'nlp-terms', 'ranking'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'HubSpot AI',
    description: 'Breeze AI co-pilot suite inside HubSpot powering customer agents, content creation, social scheduling, and CRM workflows.',
    category: 'Marketing & SEO',
    subcategory: 'Inbound Marketing CRM',
    website: 'https://hubspot.com',
    pricing: 'Freemium',
    features: ['Breeze Copilot', 'Content Assistant', 'Predictive lead scoring', 'Automated email campaigns'],
    tags: ['hubspot', 'crm', 'inbound-marketing', 'breeze'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'All Levels',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Buffer AI',
    description: 'Social media management assistant that drafts posts, suggests best publishing times, and repurposes content across networks.',
    category: 'Marketing & SEO',
    subcategory: 'Social Media Scheduler',
    website: 'https://buffer.com',
    pricing: 'Freemium',
    features: ['AI Assistant copy ideas', 'Cross-channel scheduling', 'Engagement inbox', 'Analytics reports'],
    tags: ['social-media', 'buffer', 'scheduling', 'repurposing'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Hootsuite OwlyWriter',
    description: 'Social marketing platform equipped with OwlyWriter AI to generate viral post concepts, hashtags, and schedule feeds.',
    category: 'Marketing & SEO',
    subcategory: 'Social Media Management',
    website: 'https://hootsuite.com',
    pricing: 'Paid',
    features: ['OwlyWriter AI', 'Social listening streams', 'Unified team inbox', 'Ad campaign manager'],
    tags: ['hootsuite', 'social-listening', 'enterprise-social', 'copy'],
    platforms: ['Web', 'Mobile'],
    skillLevel: 'Intermediate',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Predis.ai',
    description: 'AI social media content generator turning short product descriptions into complete reels, carousels, and captioned posts.',
    category: 'Marketing & SEO',
    subcategory: 'Social Media Post Generator',
    website: 'https://predis.ai',
    pricing: 'Freemium',
    features: ['Reels and shorts generator', 'Competitor AI analysis', 'Auto-hashtag research', 'Calendar auto-scheduler'],
    tags: ['reels', 'carousels', 'instagram', 'ecommerce'],
    platforms: ['Web', 'Mobile'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'AdCreative.ai',
    description: 'AI conversion platform that generates high-converting ad banners, video creatives, and text copy tailored for paid ads.',
    category: 'Marketing & SEO',
    subcategory: 'Paid Advertising',
    website: 'https://adcreative.ai',
    pricing: 'Paid',
    features: ['Ad conversion score', 'Dynamic creatives generation', 'Competitor ad spy', 'Multi-platform sizing'],
    tags: ['ad-banners', 'paid-media', 'meta-ads', 'conversion'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Taplio',
    description: 'The all-in-one AI platform for LinkedIn growth, personal branding, post scheduling, and relationship management.',
    category: 'Marketing & SEO',
    subcategory: 'LinkedIn Growth',
    website: 'https://taplio.com',
    pricing: 'Paid',
    features: ['LinkedIn viral post ideas', 'AI comment generator', 'Queue scheduling', 'Lead relationship list'],
    tags: ['linkedin', 'personal-brand', 'b2b-growth', 'networking'],
    platforms: ['Web', 'Chrome Extension'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'vidIQ',
    description: 'YouTube growth tool offering AI video title generators, daily content ideas, competitor tracking, and SEO keyword scoring.',
    category: 'Marketing & SEO',
    subcategory: 'YouTube Optimization',
    website: 'https://vidiq.com',
    pricing: 'Freemium',
    features: ['Daily video ideas', 'Keyword search volume & score', 'AI title & thumbnail preview', 'Competitor live audit'],
    tags: ['youtube', 'video-seo', 'analytics', 'creators'],
    platforms: ['Web', 'Chrome Extension', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'TubeBuddy',
    description: 'YouTube channel management and optimization browser extension with AI title generator, A/B testing, and keyword explorer.',
    category: 'Marketing & SEO',
    subcategory: 'YouTube Optimization',
    website: 'https://tubebuddy.com',
    pricing: 'Freemium',
    features: ['Thumbnail A/B testing', 'Keyword explorer', 'Best practice checklist', 'SEO studio'],
    tags: ['youtube', 'ab-testing', 'extension', 'thumbnails'],
    platforms: ['Chrome Extension', 'Web', 'Mobile'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
];
