// Part 5: 3D & Games, ML & Models, Meeting & Notes, Career & Resume, Finance & Accounting
export const toolsPart5 = [
  // ── S. AI 3D, ANIMATION AND GAME DEVELOPMENT ──
  {
    name: 'Meshy',
    description: 'Generative 3D creation platform turning text prompts and 2D concept images into textured 3D assets in minutes.',
    category: '3D & Game Dev',
    subcategory: '3D Asset Generation',
    website: 'https://meshy.ai',
    pricing: 'Freemium',
    features: ['Text-to-3D mesh generation', 'Image-to-3D model reconstruction', 'AI texture mapping & PBR maps', 'GLTF/FBX/OBJ export'],
    tags: ['3d', 'modeling', 'game-dev', 'textures'],
    platforms: ['Web', 'API'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Tripo AI',
    description: 'Instant 3D model generator creating high-detail textured geometry in under 10 seconds from a single prompt or image.',
    category: '3D & Game Dev',
    subcategory: 'Fast 3D Synthesis',
    website: 'https://tripo3d.ai',
    pricing: 'Freemium',
    features: ['Sub-10 second generation', 'Image-to-3D pipeline', 'Automatic retopology', 'Rigging and animation export'],
    tags: ['3d', 'fast-generation', 'gaming', 'unity'],
    platforms: ['Web', 'API'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Luma AI',
    description: 'Interactive neural radiance field (NeRF) and Gaussian Splatting app capturing photorealistic 3D environments from mobile video.',
    category: '3D & Game Dev',
    subcategory: 'NeRF & Gaussian Splats',
    website: 'https://lumalabs.ai',
    pricing: 'Freemium',
    features: ['Gaussian Splatting captures', 'Cinematic camera paths', 'Web and Unreal Engine exports', 'Interactive 3D viewing'],
    tags: ['nerf', 'gaussian-splatting', 'photogrammetry', '3d'],
    platforms: ['Web', 'iOS'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Scenario',
    description: 'AI platform for game developers to train custom style-consistent image generation models on their own game art.',
    category: '3D & Game Dev',
    subcategory: 'Game Art Models',
    website: 'https://scenario.com',
    pricing: 'Freemium',
    features: ['Custom game style training', 'Asset concept generator', 'Canvas inpainting & composition', 'Unity/Unreal plugins'],
    tags: ['gaming', 'concept-art', 'custom-models', 'game-dev'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Inworld AI',
    description: 'Character engine for gaming and interactive worlds powering intelligent, multimodal NPCs with personality, memory, and voice.',
    category: '3D & Game Dev',
    subcategory: 'AI NPC Engine',
    website: 'https://inworld.ai',
    pricing: 'Freemium',
    features: ['Smart NPC characters', 'Long-term memory persistence', 'Real-time voice & emotions', 'Unity, Unreal & Roblox SDKs'],
    tags: ['npc', 'game-ai', 'dialogue', 'gaming'],
    platforms: ['SDK', 'Unreal', 'Unity'],
    skillLevel: 'Advanced',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Kaedim',
    description: 'AI-powered 2D-to-3D production pipeline delivering game-ready production meshes with clean quad topology in minutes.',
    category: '3D & Game Dev',
    subcategory: 'Production 3D Pipeline',
    website: 'https://kaedim3d.com',
    pricing: 'Paid',
    features: ['Production-ready quad topology', 'Automated UV unwrapping', 'PBR textures', 'Direct Blender/Maya export'],
    tags: ['production-ready', 'topology', '3d-assets', 'blender'],
    platforms: ['Web'],
    skillLevel: 'Advanced',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Rodin',
    description: 'Deemos AI generative 3D foundation model generating high-fidelity digital humans, avatars, and assets from text and photos.',
    category: '3D & Game Dev',
    subcategory: '3D Avatars & Humans',
    website: 'https://hyperhuman.deemos.com/rodin',
    pricing: 'Freemium',
    features: ['Sub-minute high-res 3D avatar', 'Realistic facial hair and textures', 'Clean manifold geometry', 'Animatable rigging export'],
    tags: ['avatars', 'digital-humans', 'rodin', '3d'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Blockade Labs',
    description: 'Skybox AI tool generating 360-degree panoramic VR environments, equirectangular world textures, and immersive skyboxes.',
    category: '3D & Game Dev',
    subcategory: '360 Skyboxes & VR',
    website: 'https://blockadelabs.com',
    pricing: 'Freemium',
    features: ['360-degree panoramic generation', 'Interactive skybox depth maps', 'Mesh export', 'Unity plugin'],
    tags: ['skybox', 'vr', 'panoramic', 'environments'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Cascadeur',
    description: 'Physics-based AI 3D animation software for keyframing character motion, ragdoll physics, and secondary kinematics.',
    category: '3D & Game Dev',
    subcategory: 'Physics Animation',
    website: 'https://cascadeur.com',
    pricing: 'Freemium',
    features: ['AutoPosing neural tool', 'Physics-based trajectory validation', 'Secondary motion generator', 'FBX & DAE format export'],
    tags: ['animation', 'physics', 'keyframing', 'rigging'],
    platforms: ['Windows', 'macOS', 'Linux'],
    skillLevel: 'Intermediate',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'DeepMotion',
    description: 'AI motion capture and body tracking platform that converts standard 2D video clips into 3D animations without mocap suits.',
    category: '3D & Game Dev',
    subcategory: 'Video to Motion Capture',
    website: 'https://deepmotion.com',
    pricing: 'Freemium',
    features: ['Animate 3D markerless mocap', 'Facial tracking and hand tracking', 'Physics simulation filter', 'BVH and FBX export'],
    tags: ['motion-capture', 'mocap', 'video-to-3d', 'animation'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Move AI',
    description: 'Markerless motion capture software using computer vision and iPhone cameras to capture production-grade mocap data anywhere.',
    category: '3D & Game Dev',
    subcategory: 'Markerless Mocap',
    website: 'https://move.ai',
    pricing: 'Paid',
    features: ['Multi-camera markerless capture', 'Single-phone Move One app', 'Finger tracking and foot locking', 'Clean animation data export'],
    tags: ['mocap', 'cv', 'sports', 'production'],
    platforms: ['iOS', 'Web'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },

  // ── T. AI MACHINE LEARNING AND MODEL DEVELOPMENT ──
  {
    name: 'Hugging Face',
    description: 'The definitive open-source hub for AI community collaboration, hosting 1M+ models, datasets, spaces, and transformers libraries.',
    category: 'ML & Model Dev',
    subcategory: 'Model Hub & Community',
    website: 'https://huggingface.co',
    pricing: 'Freemium',
    features: ['1,000,000+ open-source models', 'Transformers and Diffusers libraries', 'Inference Endpoints', 'Interactive Spaces demo hosting'],
    tags: ['huggingface', 'open-source', 'models', 'datasets'],
    isOpenSource: true,
    platforms: ['Web', 'API', 'Python'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 5.0,
    lastVerified: '2025-10',
  },
  {
    name: 'Replicate',
    description: 'Cloud platform that runs open-source machine learning models with a single line of code and serverless pay-per-second scaling.',
    category: 'ML & Model Dev',
    subcategory: 'Model Deployment API',
    website: 'https://replicate.com',
    pricing: 'Paid',
    features: ['Serverless cloud inference', 'Pay only for compute seconds', 'Cog container packaging', 'Fine-tuning API'],
    tags: ['replicate', 'api', 'serverless', 'inference'],
    platforms: ['Web', 'API'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Together AI',
    description: 'Fast cloud platform for building and running generative AI models with ultra-fast inference engines and fine-tuning clusters.',
    category: 'ML & Model Dev',
    subcategory: 'Cloud Inference & Training',
    website: 'https://together.ai',
    pricing: 'Paid',
    features: ['Fastest Llama-3 inference', 'Together GPU clusters', 'LoRA fine-tuning', 'Sub-second image generation'],
    tags: ['inference', 'gpu', 'cloud', 'fine-tuning'],
    platforms: ['Cloud', 'API'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Groq',
    description: 'Ultra-fast AI inference platform powered by the LPU (Language Processing Unit), streaming LLM answers at 500+ tokens per second.',
    category: 'ML & Model Dev',
    subcategory: 'Ultra-Fast Inference',
    website: 'https://groq.com',
    pricing: 'Freemium',
    features: ['LPU chip architecture', '500+ tokens per second', 'OpenAI-compatible API', 'Whisper audio transcription'],
    tags: ['groq', 'lpu', 'speed', 'inference'],
    platforms: ['API', 'Web'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Fireworks AI',
    description: 'Production AI platform delivering lightning-fast inference and serverless fine-tuning for open-source models.',
    category: 'ML & Model Dev',
    subcategory: 'Model Serving',
    website: 'https://fireworks.ai',
    pricing: 'Paid',
    features: ['Sub-100ms first token latency', 'Function calling and structured JSON', 'FireAttention engine', 'Dedicated enterprise deployments'],
    tags: ['inference', 'serving', 'json-mode', 'api'],
    platforms: ['API'],
    skillLevel: 'Advanced',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'OpenRouter',
    description: 'Unified API gateway providing access to dozens of frontier LLMs from OpenAI, Anthropic, Google, and open-source through a single key.',
    category: 'ML & Model Dev',
    subcategory: 'LLM Gateway',
    website: 'https://openrouter.ai',
    pricing: 'Paid',
    features: ['Single unified API format', 'Auto-fallback routing', 'Transparent token pricing', 'Prompt ranking & stats'],
    tags: ['api-gateway', 'multi-model', 'routing', 'developer'],
    platforms: ['API', 'Web'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Ollama',
    description: 'Lightweight, extensible tool for running large language models locally on macOS, Linux, and Windows with a simple CLI.',
    category: 'ML & Model Dev',
    subcategory: 'Local Model Runner',
    website: 'https://ollama.com',
    pricing: 'Open Source',
    features: ['Run models offline locally', 'Simple command-line interface', 'REST API and OpenAI compatibility', 'Modelfile customization'],
    tags: ['local-llm', 'open-source', 'cli', 'privacy'],
    isOpenSource: true,
    platforms: ['macOS', 'Linux', 'Windows'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'LM Studio',
    description: 'Desktop application to discover, download, and run local LLMs offline on your computer with a clean chat interface and local server.',
    category: 'ML & Model Dev',
    subcategory: 'Local Desktop LLM',
    website: 'https://lmstudio.ai',
    pricing: 'Free',
    features: ['One-click model download from HF', 'Offline local server', 'GPU acceleration (Metal/CUDA)', 'In-app model parameters tuning'],
    tags: ['local', 'desktop', 'privacy', 'gguf'],
    platforms: ['macOS', 'Windows', 'Linux'],
    skillLevel: 'Beginner',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'vLLM',
    description: 'High-throughput and memory-efficient LLM serving engine featuring PagedAttention for production model inference.',
    category: 'ML & Model Dev',
    subcategory: 'LLM Serving Engine',
    website: 'https://vllm.ai',
    pricing: 'Open Source',
    features: ['PagedAttention memory management', 'Continuous batching', 'Distributed execution', 'OpenAI-compatible server'],
    tags: ['serving', 'high-throughput', 'open-source', 'paged-attention'],
    isOpenSource: true,
    platforms: ['Linux', 'Docker', 'Python'],
    skillLevel: 'Advanced',
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Modal',
    description: 'Serverless cloud compute for AI developers that runs Python functions in containers on GPUs with sub-second cold starts.',
    category: 'ML & Model Dev',
    subcategory: 'Serverless GPU Compute',
    website: 'https://modal.com',
    pricing: 'Paid',
    features: ['Code-defined containers', 'Fast GPU scaling', 'Zero YAML or Kubernetes', 'Web endpoints & cron jobs'],
    tags: ['serverless', 'gpu', 'python', 'cloud-compute'],
    platforms: ['Cloud', 'CLI'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'RunPod',
    description: 'Globally distributed GPU cloud providing on-demand compute instances and serverless endpoints for AI training and inference.',
    category: 'ML & Model Dev',
    subcategory: 'GPU Cloud Compute',
    website: 'https://runpod.io',
    pricing: 'Paid',
    features: ['Affordable on-demand GPU pods', 'Serverless GPU execution', 'Fast network storage volumes', 'Pre-configured AI templates'],
    tags: ['gpu', 'cloud', 'runpod', 'compute'],
    platforms: ['Cloud'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Weights & Biases',
    description: 'The developer platform for AI and machine learning tracking experiments, model versions, datasets, and LLM evaluations.',
    category: 'ML & Model Dev',
    subcategory: 'MLOps Experiment Tracking',
    website: 'https://wandb.ai',
    pricing: 'Freemium',
    features: ['Experiment tracking & metrics dashboards', 'Model registry and lineage', 'Weave LLM evaluation framework', 'Artifacts storage'],
    tags: ['mlops', 'experiments', 'evaluation', 'metrics'],
    platforms: ['Python', 'Web'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Roboflow',
    description: 'End-to-end computer vision platform to label images, train models, and deploy object detection to production cameras.',
    category: 'ML & Model Dev',
    subcategory: 'Computer Vision MLOps',
    website: 'https://roboflow.com',
    pricing: 'Freemium',
    features: ['AI-assisted image annotation', 'Roboflow Universe dataset library', 'One-click YOLO model training', 'Edge device deployment'],
    tags: ['computer-vision', 'yolo', 'annotation', 'object-detection'],
    platforms: ['Web', 'API', 'Edge'],
    skillLevel: 'Intermediate',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Google Colab',
    description: 'Hosted Jupyter notebook service by Google providing free and premium access to cloud GPUs and TPUs with seamless Drive sync.',
    category: 'ML & Model Dev',
    subcategory: 'Cloud Notebooks',
    website: 'https://colab.research.google.com',
    pricing: 'Freemium',
    features: ['Free GPU/TPU access tiers', 'Seamless Google Drive saving', 'Pre-installed AI packages', 'Colab AI coding assistant'],
    tags: ['colab', 'jupyter', 'python', 'cloud-gpu'],
    platforms: ['Web'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },

  // ── U. AI MEETING, NOTES AND TRANSCRIPTION ──
  {
    name: 'Otter.ai',
    description: 'AI meeting assistant that joins video calls, generates real-time transcripts, extracts action items, and generates summaries.',
    category: 'Meeting & Notes',
    subcategory: 'Meeting Assistant',
    website: 'https://otter.ai',
    pricing: 'Freemium',
    features: ['OtterPilot automated meeting joining', 'Live collaborative transcription', 'Automated meeting outline & action items', 'Chat with Otter Q&A'],
    tags: ['meetings', 'transcription', 'notes', 'zoom'],
    platforms: ['Web', 'iOS', 'Android', 'Chrome'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Fireflies.ai',
    description: 'Automated AI meeting recorder and search engine transcribing voice conversations across Zoom, Teams, and Google Meet.',
    category: 'Meeting & Notes',
    subcategory: 'Meeting Intelligence',
    website: 'https://fireflies.ai',
    pricing: 'Freemium',
    features: ['Multi-platform meeting bot', 'AskFred AI conversation search', 'Sentiment and talk-time metrics', 'CRM auto-logging'],
    tags: ['meetings', 'transcription', 'fireflies', 'analytics'],
    platforms: ['Web', 'Chrome Extension'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Fathom',
    description: 'Free AI meeting assistant for Zoom, Google Meet, and Microsoft Teams providing instant summaries and CRM sync.',
    category: 'Meeting & Notes',
    subcategory: 'Meeting Notetaker',
    website: 'https://fathom.video',
    pricing: 'Freemium',
    features: ['100% free transcription & notes tier', 'One-click highlights during calls', 'Direct Salesforce and HubSpot sync', 'Shareable meeting clips'],
    tags: ['fathom', 'free-tier', 'zoom', 'crm-sync'],
    platforms: ['macOS', 'Windows', 'Web'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'tl;dv',
    description: 'AI meeting recorder capturing video and transcripts in 30+ languages, with AI multi-meeting synthesis.',
    category: 'Meeting & Notes',
    subcategory: 'Meeting Knowledge Hub',
    website: 'https://tldv.io',
    pricing: 'Freemium',
    features: ['Video clip snippets creation', 'Multi-meeting topic synthesis', 'Automatic timestamped chapters', 'Notion and Slack integrations'],
    tags: ['video-recording', 'transcripts', 'clips', 'teams'],
    platforms: ['Chrome Extension', 'Desktop App', 'Web'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Granola',
    description: 'AI notepad for people who like taking their own notes, pairing human shorthand with AI audio transcription to create polished notes.',
    category: 'Meeting & Notes',
    subcategory: 'Hybrid Notepad',
    website: 'https://granola.so',
    pricing: 'Freemium',
    features: ['Bot-free audio capture', 'Combines human notes with transcript', 'Customizable markdown templates', 'Instant Slack sharing'],
    tags: ['minimalist', 'mac-app', 'bot-free', 'clean-notes'],
    platforms: ['macOS'],
    skillLevel: 'Beginner',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Supernormal',
    description: 'AI meeting notes tool that writes detailed executive summaries, action item trackers, and integrates with Google Meet.',
    category: 'Meeting & Notes',
    subcategory: 'Executive Summaries',
    website: 'https://supernormal.com',
    pricing: 'Freemium',
    features: ['Custom summary formats', 'Automatic task delegation', 'Chrome extension recording', 'Multi-lingual meeting notes'],
    tags: ['executive', 'summaries', 'google-meet', 'teams'],
    platforms: ['Web', 'Chrome Extension'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },

  // ── V. AI RESUME, CAREER AND INTERVIEW PREPARATION ──
  {
    name: 'Teal',
    description: 'All-in-one career growth platform with AI resume builder, job tracker, resume keyword matcher, and LinkedIn profile review.',
    category: 'Career & Resume',
    subcategory: 'Job Search & Resume',
    website: 'https://tealhq.com',
    pricing: 'Freemium',
    features: ['AI resume bullet generator', 'Job application tracking board', 'Job description keyword match score', 'Chrome job bookmark extension'],
    tags: ['resume', 'job-search', 'career', 'ats-check'],
    platforms: ['Web', 'Chrome Extension'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Kickresume',
    description: 'AI resume and cover letter builder with customizable ATS-ready designer templates and career advice guides.',
    category: 'Career & Resume',
    subcategory: 'Resume Builder',
    website: 'https://kickresume.com',
    pricing: 'Freemium',
    features: ['GPT-4 powered resume drafting', 'ATS-friendly design templates', 'AI cover letter generator', 'Personal portfolio website maker'],
    tags: ['resume-design', 'cover-letter', 'ats', 'templates'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Rezi',
    description: 'ATS-focused resume software that analyzes resumes against specific job posts to maximize interview invitation rates.',
    category: 'Career & Resume',
    subcategory: 'ATS Optimization',
    website: 'https://rezi.ai',
    pricing: 'Freemium',
    features: ['Rezi Score ATS analysis', 'AI content writer', 'Keyword gap identifier', 'Cover letter & resignation letter builder'],
    tags: ['ats', 'score', 'resume', 'optimization'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Jobscan',
    description: 'Resume optimization tool comparing your resume against job postings to reverse-engineer ATS algorithms.',
    category: 'Career & Resume',
    subcategory: 'Resume Matcher',
    website: 'https://jobscan.co',
    pricing: 'Freemium',
    features: ['ATS match rate percentage', 'Hard and soft skill audits', 'LinkedIn profile optimizer', 'Formatting recommendations'],
    tags: ['ats-scan', 'match-rate', 'keywords', 'interviews'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Interview Warmup',
    description: 'Google AI tool helping job seekers practice interview questions and get machine insights on topics covered and key terms used.',
    category: 'Career & Resume',
    subcategory: 'Mock Interviews',
    website: 'https://grow.google/certificates/interview-warmup',
    pricing: 'Free',
    features: ['Free Google practice platform', 'Audio or text responses', 'Job-specific question categories', 'Talking points & terms review'],
    tags: ['google', 'mock-interview', 'free', 'practice'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Final Round AI',
    description: 'Real-time AI interview copilot providing live transcription, coding hints, and behavioral answer guidance during technical interviews.',
    category: 'Career & Resume',
    subcategory: 'Live Interview Copilot',
    website: 'https://finalroundai.com',
    pricing: 'Paid',
    features: ['Live Interview Copilot', 'Real-time coding question hints', 'Mock interview simulations', 'Post-interview performance score'],
    tags: ['interviews', 'copilot', 'coding-interview', 'career'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },

  // ── W. AI FINANCE AND ACCOUNTING ──
  {
    name: 'Intuit Assist',
    description: 'GenAI financial assistant inside TurboTax, QuickBooks, and Credit Karma answering tax queries and forecasting business cash flow.',
    category: 'Finance & Accounting',
    subcategory: 'Tax & Bookkeeping AI',
    website: 'https://intuit.com/intuit-assist',
    pricing: 'Verify on official website',
    features: ['Automated bookkeeping anomalies', 'Tax preparation insights', 'Cash flow projections', 'Small business invoice reminders'],
    tags: ['taxes', 'quickbooks', 'intuit', 'accounting'],
    platforms: ['Web', 'Mobile'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Ramp Intelligence',
    description: 'Finance automation inside Ramp corporate cards analyzing spending contracts, detecting wasteful subscriptions, and auto-matching receipts.',
    category: 'Finance & Accounting',
    subcategory: 'Spend Management',
    website: 'https://ramp.com/intelligence',
    pricing: 'Verify on official website',
    features: ['Contract price benchmarking', 'Automated receipt matching', 'Expense policy enforcement', 'Duplicate SaaS detection'],
    tags: ['corporate-cards', 'expense-management', 'finance', 'cost-cutting'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Vic.ai',
    description: 'Autonomous accounting platform using computer vision and machine learning to process invoices and approve purchase orders without human input.',
    category: 'Finance & Accounting',
    subcategory: 'Autonomous AP',
    website: 'https://vic.ai',
    pricing: 'Verify on official website',
    features: ['Autonomous 3-way invoice matching', 'Automated GL coding', 'Real-time spend anomaly detection', 'ERP sync'],
    tags: ['accounts-payable', 'invoices', 'autonomous-accounting', 'erp'],
    platforms: ['Web'],
    skillLevel: 'Advanced',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'AlphaSense',
    description: 'Market intelligence and financial search platform aggregating SEC filings, broker research, earnings call transcripts, and expert interviews.',
    category: 'Finance & Accounting',
    subcategory: 'Market Intelligence',
    website: 'https://alpha-sense.com',
    pricing: 'Verify on official website',
    features: ['Smart Synonyms financial search', 'Generative earnings call summaries', 'SEC 10-K & 10-Q filing analysis', 'Expert interview transcripts library'],
    tags: ['market-research', 'sec-filings', 'earnings-calls', 'finance'],
    platforms: ['Web'],
    skillLevel: 'Advanced',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'FinChat',
    description: 'AI investment research assistant providing complete financial data, verified metrics, charts, and transcript answers on public companies.',
    category: 'Finance & Accounting',
    subcategory: 'Equity Research',
    website: 'https://finchat.io',
    pricing: 'Freemium',
    features: ['Public company financials database', 'Instant SEC-verified metric queries', 'Segment breakdown graphs', 'Earnings call Q&A breakdown'],
    tags: ['stocks', 'equity-research', 'investing', 'financial-models'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
];
