// Part 4: Presentations & Docs, Education & Students, Cybersecurity & DevOps, Sales & Support, Translation
export const toolsPart4 = [
  // ── N. AI PRESENTATIONS AND DOCUMENTS ──
  {
    name: 'Gamma',
    description: 'AI presentation and webpage generator that creates polished, interactive slide decks and documents from text prompts in seconds.',
    category: 'Presentations & Docs',
    subcategory: 'AI Presentations',
    website: 'https://gamma.app',
    pricing: 'Freemium',
    features: ['One-click deck generation', 'Flexible cards layout', 'Interactive embeds', 'Analytics tracking'],
    tags: ['presentations', 'slides', 'docs', 'gamma'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Beautiful.ai',
    description: 'Smart presentation software using automated design principles to adapt layouts dynamically as you add content.',
    category: 'Presentations & Docs',
    subcategory: 'Smart Slide Design',
    website: 'https://beautiful.ai',
    pricing: 'Paid',
    features: ['Designer Bot', 'Smart slide templates', 'Team brand guardrails', 'PowerPoint export'],
    tags: ['slides', 'presentation', 'design-rules', 'enterprise'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Pitch',
    description: 'Collaborative presentation software with AI drafting, custom templates, and real-time multiplayer editing.',
    category: 'Presentations & Docs',
    subcategory: 'Collaborative Decks',
    website: 'https://pitch.com',
    pricing: 'Freemium',
    features: ['AI slide generator', 'Multiplayer collaboration', 'Live video sharing', 'Engagement analytics'],
    tags: ['decks', 'pitch', 'collaboration', 'startups'],
    platforms: ['Web', 'macOS', 'Windows', 'iOS', 'Android'],
    skillLevel: 'All Levels',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Slidesgo AI',
    description: 'AI presentation maker creating customizable Google Slides and PowerPoint presentations with rich illustration templates.',
    category: 'Presentations & Docs',
    subcategory: 'Slide Templates',
    website: 'https://slidesgo.com/ai-presentations',
    pricing: 'Freemium',
    features: ['Topic to full presentation', 'Style selection', 'Google Slides export', 'Freepik graphics integration'],
    tags: ['slidesgo', 'powerpoint', 'google-slides', 'templates'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Decktopus',
    description: 'AI presentation generator designed for business proposals, client onboarding, and lead generation with embedded forms.',
    category: 'Presentations & Docs',
    subcategory: 'Interactive Decks',
    website: 'https://decktopus.com',
    pricing: 'Freemium',
    features: ['Form embed in slides', 'Voiceover recorder', 'Automatic layout engine', 'Custom domain sharing'],
    tags: ['proposals', 'sales-deck', 'forms', 'lead-gen'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'MagicSlides',
    description: 'Google Slides add-on that converts any text, YouTube video, or topic into presentation slides in seconds.',
    category: 'Presentations & Docs',
    subcategory: 'Google Slides Add-on',
    website: 'https://magicslides.app',
    pricing: 'Freemium',
    features: ['Google Slides native extension', 'YouTube to slides', 'Multiple language output', 'Custom template styles'],
    tags: ['google-slides', 'add-on', 'youtube-summary', 'presentation'],
    platforms: ['Google Workspace'],
    skillLevel: 'Beginner',
    rating: 4.4,
    lastVerified: '2025-10',
  },
  {
    name: 'Napkin AI',
    description: 'Transforms written text and business documentation into beautiful visual diagrams, flowcharts, and infographics.',
    category: 'Presentations & Docs',
    subcategory: 'Visual Explanation',
    website: 'https://napkin.ai',
    pricing: 'Freemium',
    features: ['Text-to-diagram converter', 'Customizable SVG exports', 'Infographic cards', 'Document illustration'],
    tags: ['diagrams', 'infographics', 'visuals', 'communication'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'PDF.ai',
    description: 'Conversational PDF platform allowing instant document interrogation, legal contract review, and data extraction.',
    category: 'Presentations & Docs',
    subcategory: 'PDF Assistant',
    website: 'https://pdf.ai',
    pricing: 'Freemium',
    features: ['Chat with documents', 'Chrome extension viewer', 'Page citation linking', 'Document summary'],
    tags: ['pdf', 'document-qa', 'contracts', 'research'],
    platforms: ['Web', 'Chrome Extension'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Smallpdf AI',
    description: 'Suite of PDF tools enhanced with AI for instant summarization, document chatting, and format conversion.',
    category: 'Presentations & Docs',
    subcategory: 'PDF Suite',
    website: 'https://smallpdf.com/ai-pdf',
    pricing: 'Freemium',
    features: ['PDF summarizer', 'Document question answering', 'PDF compression and edit', 'OCR text recognition'],
    tags: ['pdf', 'compression', 'ocr', 'productivity'],
    platforms: ['Web', 'Desktop', 'Mobile'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },

  // ── O. AI EDUCATION AND PRODUCTIVITY FOR STUDENTS ──
  {
    name: 'Khanmigo',
    description: 'AI tutor developed by Khan Academy that guides students through math and science problems using Socratic questioning without giving away answers.',
    category: 'Education & Learning',
    subcategory: 'Socratic AI Tutor',
    website: 'https://khanacademy.org/khanmigo',
    pricing: 'Freemium',
    features: ['Socratic dialogue method', 'Math step-by-step guidance', 'Teacher lesson planner', 'Ethical student guardrails'],
    tags: ['education', 'tutoring', 'khan-academy', 'math'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Quizlet',
    description: 'Study platform with AI-powered Q-Chat tutor, Magic Notes summary generator, and adaptive flashcard revision schedules.',
    category: 'Education & Learning',
    subcategory: 'Study & Flashcards',
    website: 'https://quizlet.com',
    pricing: 'Freemium',
    features: ['Q-Chat conversational tutor', 'Magic Notes upload', 'Spaced repetition flashcards', 'Practice test generation'],
    tags: ['flashcards', 'study', 'spaced-repetition', 'exams'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Duolingo Max',
    description: 'Premium language learning tier featuring GPT-4 powered Explain My Answer and Roleplay real-life conversation scenarios.',
    category: 'Education & Learning',
    subcategory: 'Language Learning',
    website: 'https://duolingo.com',
    pricing: 'Paid',
    features: ['Explain My Answer breakdowns', 'Roleplay scenarios', 'Bite-sized gamified lessons', 'Personalized learning curve'],
    tags: ['duolingo', 'languages', 'roleplay', 'gamified'],
    platforms: ['iOS', 'Android', 'Web'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'ELSA Speak',
    description: 'AI pronunciation and accent coach using speech recognition to provide syllable-by-syllable feedback for English learners.',
    category: 'Education & Learning',
    subcategory: 'Pronunciation Coach',
    website: 'https://elsaspeak.com',
    pricing: 'Freemium',
    features: ['Syllable pronunciation scoring', 'IELTS test preparation', 'Conversational roleplays', 'Daily bite-sized drills'],
    tags: ['pronunciation', 'english', 'speech-coaching', 'accents'],
    platforms: ['iOS', 'Android'],
    skillLevel: 'All Levels',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Speak',
    description: 'Conversational language learning app that gets students speaking out loud with realistic interactive conversational AI personas.',
    category: 'Education & Learning',
    subcategory: 'Language Speaking',
    website: 'https://speak.com',
    pricing: 'Paid',
    features: ['Open-ended voice conversation', 'Instant grammar correction', 'Real-world scenario practice', 'Adaptive repetition'],
    tags: ['languages', 'speaking', 'fluency', 'conversation'],
    platforms: ['iOS', 'Android'],
    skillLevel: 'All Levels',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Praktika',
    description: 'Immersive language learning app featuring ultra-realistic interactive AI avatars acting as personal English tutors.',
    category: 'Education & Learning',
    subcategory: 'Avatar English Tutor',
    website: 'https://praktika.ai',
    pricing: 'Paid',
    features: ['Lifelike 3D avatars', 'Accent coaching', 'Diverse real-world topics', 'Personalized curriculum'],
    tags: ['avatars', 'tutors', 'english', 'immersion'],
    platforms: ['iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Photomath',
    description: 'Camera-based math problem solver by Google that recognizes handwriting and explains step-by-step solutions.',
    category: 'Education & Learning',
    subcategory: 'Math Solver',
    website: 'https://photomath.com',
    pricing: 'Freemium',
    features: ['Camera scan handwritten math', 'Step-by-step animated guides', 'Interactive graphs', 'Deep explanations'],
    tags: ['math', 'homework', 'camera-scan', 'students'],
    platforms: ['iOS', 'Android'],
    skillLevel: 'All Levels',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Gauth',
    description: 'AI homework helper and multi-subject math solver providing step-by-step problem breakdowns across STEM subjects.',
    category: 'Education & Learning',
    subcategory: 'Homework Helper',
    website: 'https://gauthmath.com',
    pricing: 'Freemium',
    features: ['Instant photo scan solver', 'STEM subjects coverage', 'Step-by-step explanations', 'Live expert tutor option'],
    tags: ['homework', 'stem', 'physics', 'math'],
    platforms: ['iOS', 'Android', 'Web'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Brainly AI',
    description: 'Peer-to-peer student learning network enhanced with AI for instant verified answers and guided homework explanations.',
    category: 'Education & Learning',
    subcategory: 'Peer Learning',
    website: 'https://brainly.com',
    pricing: 'Freemium',
    features: ['AI Tutor step breakdowns', 'Peer-verified database', 'Community Q&A', 'Textbook solutions'],
    tags: ['homework', 'community', 'textbooks', 'students'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.4,
    lastVerified: '2025-10',
  },
  {
    name: 'StudyFetch',
    description: 'AI learning platform that transforms course lectures, recordings, and PDFs into flashcards, notes, and interactive quizzes.',
    category: 'Education & Learning',
    subcategory: 'Study Hub',
    website: 'https://studyfetch.com',
    pricing: 'Freemium',
    features: ['Spark.E conversational tutor', 'Lecture recording transcription', 'Quiz generation', 'Flashcard sets'],
    tags: ['lectures', 'quizzes', 'flashcards', 'study-tools'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Knowt',
    description: 'Free study app providing AI flashcards, practice exam simulations, and seamless import from Quizlet.',
    category: 'Education & Learning',
    subcategory: 'Free Study App',
    website: 'https://knowt.com',
    pricing: 'Free',
    features: ['Free Quizlet import', 'Practice exam simulation', 'Video note sync', 'Spaced repetition'],
    tags: ['free', 'study', 'flashcards', 'exams'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Yoodli',
    description: 'AI speech coach providing private, personalized feedback on speaking pace, filler words, eye contact, and executive presence.',
    category: 'Education & Learning',
    subcategory: 'Speech Coach',
    website: 'https://yoodli.ai',
    pricing: 'Freemium',
    features: ['Filler word detection', 'Pacing and pause metrics', 'Mock interview scenarios', 'Interactive speech games'],
    tags: ['speech-coach', 'public-speaking', 'interviews', 'confidence'],
    platforms: ['Web'],
    skillLevel: 'All Levels',
    rating: 4.8,
    lastVerified: '2025-10',
  },

  // ── P. AI CYBERSECURITY AND DEVOPS ──
  {
    name: 'Snyk',
    description: 'Developer-first security platform using DeepCode AI to detect, fix, and explain vulnerabilities in code, dependencies, and containers.',
    category: 'Cybersecurity & DevOps',
    subcategory: 'Application Security',
    website: 'https://snyk.io',
    pricing: 'Freemium',
    features: ['DeepCode AI vulnerability fixes', 'Open source dependency scanning', 'Container security', 'Infrastructure as Code security'],
    tags: ['security', 'vulnerabilities', 'devops', 'open-source'],
    platforms: ['CLI', 'IDE', 'GitHub', 'Web'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Semgrep',
    description: 'Fast, open-source static analysis engine with Semgrep Assistant to filter false positives and auto-remediate security bugs.',
    category: 'Cybersecurity & DevOps',
    subcategory: 'Static Code Analysis',
    website: 'https://semgrep.dev',
    pricing: 'Freemium',
    features: ['Semgrep Assistant auto-fixes', 'Custom policy rules', 'Supply chain scanning', 'Secrets detection'],
    tags: ['sast', 'code-analysis', 'security', 'devsecops'],
    isOpenSource: true,
    platforms: ['CLI', 'CI/CD', 'GitHub'],
    skillLevel: 'Intermediate',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'GitHub Advanced Security',
    description: 'Native code security suite inside GitHub offering AI secret scanning, CodeQL analysis, and Copilot autofix.',
    category: 'Cybersecurity & DevOps',
    subcategory: 'Repository Security',
    website: 'https://github.com/features/security',
    pricing: 'Paid',
    features: ['Copilot Autofix for vulnerabilities', 'CodeQL semantic analysis', 'Secret scanning with push protection', 'Dependabot security updates'],
    tags: ['github', 'security', 'codeql', 'secrets'],
    platforms: ['GitHub'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Microsoft Security Copilot',
    description: 'Generative AI security solution empowering analysts to defend at machine speed with natural language threat investigations.',
    category: 'Cybersecurity & DevOps',
    subcategory: 'SecOps Copilot',
    website: 'https://microsoft.com/security/business/ai-machine-learning/microsoft-security-copilot',
    pricing: 'Paid',
    features: ['Threat incident summarization', 'Reverse engineering scripts', 'Guided response steps', 'Defender & Sentinel integration'],
    tags: ['microsoft', 'soc', 'threat-hunting', 'secops'],
    platforms: ['Web', 'Azure'],
    skillLevel: 'Advanced',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Wiz',
    description: 'Cloud security platform connecting across multi-cloud environments with AI-powered vulnerability correlation and risk graphs.',
    category: 'Cybersecurity & DevOps',
    subcategory: 'Cloud Security CNAPP',
    website: 'https://wiz.io',
    pricing: 'Paid',
    features: ['Security graph correlation', 'Agentless scanning', 'Cloud detection & response', 'AI runtime monitoring'],
    tags: ['cloud-security', 'aws', 'azure', 'gcp'],
    platforms: ['Cloud'],
    skillLevel: 'Advanced',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'CrowdStrike Charlotte AI',
    description: 'Generative AI security analyst integrated into the Falcon platform to accelerate threat hunting and incident remediation.',
    category: 'Cybersecurity & DevOps',
    subcategory: 'Endpoint & Threat Hunting',
    website: 'https://crowdstrike.com',
    pricing: 'Paid',
    features: ['Multi-turn security dialogue', 'Instant adversary attribution', 'Automated containment workflows', 'Falcon telemetry grounding'],
    tags: ['crowdstrike', 'endpoint', 'threat-hunting', 'enterprise'],
    platforms: ['Cloud'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'SentinelOne Purple AI',
    description: 'Autonomous cybersecurity AI that simplifies complex threat hunting queries and orchestrates instant incident response.',
    category: 'Cybersecurity & DevOps',
    subcategory: 'Autonomous SOC',
    website: 'https://sentinelone.com',
    pricing: 'Paid',
    features: ['Natural language threat queries', 'Unified alert correlation', 'Autonomous rollback remediation', 'MITRE ATT&CK mapping'],
    tags: ['sentinelone', 'soc', 'threat-hunting', 'automation'],
    platforms: ['Cloud'],
    skillLevel: 'Advanced',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Datadog Bits AI',
    description: 'AI DevOps assistant across Datadog that investigates outages, explains error stack traces, and suggests code fixes.',
    category: 'Cybersecurity & DevOps',
    subcategory: 'Observability & APM',
    website: 'https://datadoghq.com',
    pricing: 'Paid',
    features: ['Incident root cause analysis', 'Natural language monitor setup', 'Synthetic testing AI', 'Log pattern anomalies'],
    tags: ['datadog', 'apm', 'observability', 'devops'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Dynatrace Davis AI',
    description: 'Causal AI engine providing deterministic root cause analysis and automated cloud operations for enterprise architectures.',
    category: 'Cybersecurity & DevOps',
    subcategory: 'Causal Observability',
    website: 'https://dynatrace.com',
    pricing: 'Paid',
    features: ['Causal AI deterministic root cause', 'Predictive anomaly detection', 'Generative CoPilot assistance', 'Automated cloud remediations'],
    tags: ['dynatrace', 'causal-ai', 'enterprise-apm', 'cloud-ops'],
    platforms: ['Cloud'],
    skillLevel: 'Advanced',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'New Relic AI',
    description: 'Generative AI observability assistant that queries telemetry data, detects performance bottlenecks, and analyzes code errors.',
    category: 'Cybersecurity & DevOps',
    subcategory: 'Observability',
    website: 'https://newrelic.com',
    pricing: 'Freemium',
    features: ['Natural language telemetry queries', 'Error analysis and stack decoding', 'Infrastructure health checks', 'Full-stack APM'],
    tags: ['observability', 'apm', 'newrelic', 'monitoring'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Harness AI',
    description: 'Modern software delivery platform with AI DevOps agents for automated CI/CD pipelines, verification, and cost optimization.',
    category: 'Cybersecurity & DevOps',
    subcategory: 'CI/CD & Delivery',
    website: 'https://harness.io',
    pricing: 'Freemium',
    features: ['AIDA generative assistant', 'Automated deployment verification', 'Chaos engineering', 'Cloud cost optimization'],
    tags: ['cicd', 'devops', 'continuous-delivery', 'automation'],
    platforms: ['Cloud'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'GitLab Duo',
    description: 'Suite of AI capabilities integrated into GitLab spanning code suggestions, security remediation, and CI/CD troubleshooting.',
    category: 'Cybersecurity & DevOps',
    subcategory: 'DevSecOps Platform',
    website: 'https://gitlab.com',
    pricing: 'Paid',
    features: ['Code suggestions', 'Vulnerability explanation & fix', 'Root cause pipeline analysis', 'MR summary generation'],
    tags: ['gitlab', 'devsecops', 'git', 'pipelines'],
    platforms: ['Web', 'VS Code', 'JetBrains'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },

  // ── Q. AI BUSINESS, SALES AND CUSTOMER SUPPORT ──
  {
    name: 'Intercom Fin',
    description: 'Breakthrough customer service AI bot resolving over 50% of support tickets instantly with zero hallucination and strict grounding.',
    category: 'Sales & Support',
    subcategory: 'Support AI Bot',
    website: 'https://intercom.com/fin',
    pricing: 'Paid',
    features: ['Zero hallucination guardrails', 'Answers grounded in help docs', 'Smooth human handoff', 'Omnichannel support'],
    tags: ['intercom', 'customer-support', 'fin', 'helpdesk'],
    platforms: ['Web', 'Mobile'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Zendesk AI',
    description: 'Built-in customer service intelligence that classifies ticket intent, detects customer sentiment, and suggests agent replies.',
    category: 'Sales & Support',
    subcategory: 'Support Intelligence',
    website: 'https://zendesk.com/ai',
    pricing: 'Paid',
    features: ['Intent and sentiment detection', 'Macro agent recommendations', 'Generative ticket expansion', 'Knowledge base gap finder'],
    tags: ['zendesk', 'ticketing', 'customer-experience', 'enterprise'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Salesforce Agentforce',
    description: 'Autonomous AI agents by Salesforce that execute tasks across sales, service, marketing, and commerce directly within CRM data.',
    category: 'Sales & Support',
    subcategory: 'Autonomous CRM Agents',
    website: 'https://salesforce.com/agentforce',
    pricing: 'Paid',
    features: ['Autonomous multi-step actions', 'Atlas reasoning engine', 'Direct Data Cloud grounding', 'Human-in-the-loop controls'],
    tags: ['salesforce', 'crm', 'autonomous-agents', 'enterprise'],
    platforms: ['Web'],
    skillLevel: 'Advanced',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Freshworks Freddy AI',
    description: 'AI suite for customer service and IT service management automating ticket resolutions and empowering service teams.',
    category: 'Sales & Support',
    subcategory: 'Service Management',
    website: 'https://freshworks.com/freddy-ai',
    pricing: 'Paid',
    features: ['Freddy Copilot for agents', 'Freddy Self-Service bots', 'Predictive churn insights', 'Automated ticket triage'],
    tags: ['freshworks', 'itsm', 'customer-support', 'triage'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Gorgias AI',
    description: 'E-commerce focused customer support platform automating order tracking, returns, and exchanges for Shopify merchants.',
    category: 'Sales & Support',
    subcategory: 'E-commerce Support',
    website: 'https://gorgias.com',
    pricing: 'Paid',
    features: ['Shopify order actions inside chat', 'Automated return flow', 'Sentiment analysis', 'Revenue tracking per ticket'],
    tags: ['shopify', 'ecommerce', 'customer-service', 'support'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Tidio Lyro',
    description: 'Conversational AI chatbot built for small businesses that resolves support queries using proprietary FAQ data.',
    category: 'Sales & Support',
    subcategory: 'Small Business Chat',
    website: 'https://tidio.com/lyro',
    pricing: 'Freemium',
    features: ['Claude-powered factual responses', 'Live website chat widget', 'Lead capture automation', 'Simple Shopify integration'],
    tags: ['tidio', 'live-chat', 'small-business', 'faq-bot'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Gong',
    description: 'Revenue intelligence platform analyzing sales calls and customer interactions to guide deals and forecast revenue.',
    category: 'Sales & Support',
    subcategory: 'Revenue Intelligence',
    website: 'https://gong.io',
    pricing: 'Paid',
    features: ['Sales conversation transcription', 'Competitor mention tracking', 'Deal risk warnings', 'Revenue forecast modeling'],
    tags: ['sales', 'revenue-intelligence', 'deals', 'calls'],
    platforms: ['Web', 'Mobile'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Clari',
    description: 'Revenue platform using AI to orchestrate sales forecasts, inspect pipeline hygiene, and govern execution.',
    category: 'Sales & Support',
    subcategory: 'Revenue Forecasting',
    website: 'https://clari.com',
    pricing: 'Paid',
    features: ['AI revenue forecasting', 'Pipeline inspection', 'Automated CRM updates', 'RevAI generative insights'],
    tags: ['revenue', 'forecasting', 'pipeline', 'sales-ops'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Apollo.io',
    description: 'All-in-one B2B sales intelligence and engagement platform with 275M+ verified contacts, AI email writer, and dialer.',
    category: 'Sales & Support',
    subcategory: 'Sales Prospecting',
    website: 'https://apollo.io',
    pricing: 'Freemium',
    features: ['275M+ B2B contact database', 'AI email personalization', 'Automated outbound sequences', 'Built-in dialer and call recorder'],
    tags: ['prospecting', 'leads', 'b2b', 'outbound-sales'],
    platforms: ['Web', 'Chrome Extension'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Clay',
    description: 'Dynamic data enrichment and outbound sales engine combining 50+ data providers and AI web research agents.',
    category: 'Sales & Support',
    subcategory: 'Data Enrichment & Outbound',
    website: 'https://clay.com',
    pricing: 'Freemium',
    features: ['Waterfall enrichment across 50+ sources', 'Claygent AI web researcher', 'Hyper-personalized cold emails', 'CRM sync'],
    tags: ['data-enrichment', 'outbound', 'waterfall', 'sales-tech'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },

  // ── R. AI TRANSLATION AND LANGUAGE LEARNING ──
  {
    name: 'DeepL',
    description: 'World-renowned neural machine translation engine known for natural phrasing, nuanced accuracy, and corporate document translation.',
    category: 'Translation & Language',
    subcategory: 'Neural Translation',
    website: 'https://deepl.com',
    pricing: 'Freemium',
    features: ['30+ languages translation', 'Full document preservation (DOCX, PDF, PPTX)', 'Custom company glossaries', 'Enterprise data security'],
    tags: ['translation', 'deepl', 'multilingual', 'enterprise'],
    platforms: ['Web', 'Windows', 'macOS', 'iOS', 'Android', 'API'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Google Translate',
    description: 'Free translation service supporting over 130 languages with instant camera translation, voice conversations, and web page rendering.',
    category: 'Translation & Language',
    subcategory: 'Universal Translation',
    website: 'https://translate.google.com',
    pricing: 'Free',
    features: ['130+ languages supported', 'Camera visual translation', 'Offline language pack downloads', 'Real-time conversation mode'],
    tags: ['google', 'free', 'languages', 'universal'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Microsoft Translator',
    description: 'Enterprise translation service supporting real-time speech translation, multi-device live conversations, and document translation.',
    category: 'Translation & Language',
    subcategory: 'Enterprise Translation',
    website: 'https://translator.microsoft.com',
    pricing: 'Freemium',
    features: ['Live multi-device conversation', 'Azure Cognitive Services API', 'Office document translation', 'Custom Translator models'],
    tags: ['microsoft', 'enterprise', 'speech-translation', 'azure'],
    platforms: ['Web', 'Windows', 'iOS', 'Android', 'API'],
    skillLevel: 'All Levels',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Wordvice AI',
    description: 'AI proofreading and academic translation tool built specifically for scientific researchers, students, and authors.',
    category: 'Translation & Language',
    subcategory: 'Academic Proofreading',
    website: 'https://wordvice.ai',
    pricing: 'Freemium',
    features: ['Academic vocabulary enhancer', 'Plagiarism checking', 'Tone and style switcher', 'Manuscript translation'],
    tags: ['academic', 'manuscript', 'research', 'proofreading'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Reverso',
    description: 'AI translation and context lookup tool providing real-world sentence examples, verb conjugation, and synomyms.',
    category: 'Translation & Language',
    subcategory: 'Context Translation',
    website: 'https://reverso.net',
    pricing: 'Freemium',
    features: ['Contextual sentence search', 'Complete verb conjugation', 'Pronunciation by native speakers', 'Integrated grammar check'],
    tags: ['context', 'conjugation', 'learning', 'multilingual'],
    platforms: ['Web', 'Mobile', 'Desktop'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Memrise',
    description: 'Language learning platform using AI video conversations with native speaker clips and MemBot chat practice.',
    category: 'Translation & Language',
    subcategory: 'Language Practice',
    website: 'https://memrise.com',
    pricing: 'Freemium',
    features: ['MemBot AI conversation partner', 'Thousands of native speaker video clips', 'Spaced repetition vocabulary', 'Real-life topics'],
    tags: ['language-learning', 'video-clips', 'vocabulary', 'conversation'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'LingQ',
    description: 'Immersion language learning system that turns any web article, YouTube video, or Netflix show into interactive lessons with AI.',
    category: 'Translation & Language',
    subcategory: 'Immersion Learning',
    website: 'https://lingq.com',
    pricing: 'Freemium',
    features: ['Import web content & Netflix', 'Interactive word lookup and tracking', 'Spaced repetition vocabulary', 'Extensive audio library'],
    tags: ['immersion', 'reading', 'languages', 'content-import'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
];
