// Part 6: Healthcare, E-Commerce, Knowledge & Mind Maps, Legal, Science/Robotics
export const toolsPart6 = [
  // ── X. AI HEALTHCARE AND LIFE SCIENCES ──
  {
    name: 'OpenEvidence',
    description: 'AI medical search engine for healthcare professionals providing peer-reviewed, cited clinical answers to complex medical questions.',
    category: 'Healthcare & Bio',
    subcategory: 'Clinical Decision Support',
    website: 'https://openevidence.com',
    pricing: 'Free',
    features: ['PubMed and medical journal grounding', 'Peer-reviewed clinical evidence', 'Physician-reviewed outputs', 'Strict medical disclaimer'],
    tags: ['healthcare', 'clinical', 'medicine', 'doctors'],
    platforms: ['Web', 'Mobile'],
    skillLevel: 'Advanced',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Glass Health',
    description: 'Clinical decision support and medical diagnosis tool that assists physicians with differential diagnoses and clinical plans.',
    category: 'Healthcare & Bio',
    subcategory: 'Differential Diagnosis',
    website: 'https://glass.health',
    pricing: 'Freemium',
    features: ['Differential diagnosis generation', 'Clinical plan drafting', 'Evidence citations', 'Personal clinical notebook'],
    tags: ['healthcare', 'diagnosis', 'clinical', 'physicians'],
    platforms: ['Web'],
    skillLevel: 'Advanced',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Abridge',
    description: 'Enterprise generative AI clinical documentation platform converting patient-doctor conversations into structured medical notes in real time.',
    category: 'Healthcare & Bio',
    subcategory: 'Clinical Documentation',
    website: 'https://abridge.com',
    pricing: 'Verify on official website',
    features: ['Ambient conversation capture', 'EHR electronic medical record sync (Epic)', 'Linked audio citations', 'HIPAA compliant'],
    tags: ['healthcare', 'ehr', 'ambient-ai', 'clinical-notes'],
    platforms: ['iOS', 'Android', 'Web'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'AlphaFold',
    description: 'DeepMind landmark AI system accurately predicting 3D structures of proteins and biomolecular complexes across the tree of life.',
    category: 'Healthcare & Bio',
    subcategory: 'Protein Structure Prediction',
    website: 'https://alphafold.ebi.ac.uk',
    pricing: 'Open Source',
    features: ['AlphaFold 3 molecular interactions', '200M+ predicted protein structures', 'Open database access', 'Drug discovery acceleration'],
    tags: ['biology', 'proteins', 'deepmind', 'drug-discovery'],
    isOpenSource: true,
    platforms: ['Web', 'Python', 'Database'],
    skillLevel: 'Advanced',
    isFeatured: true,
    rating: 5.0,
    lastVerified: '2025-10',
  },
  {
    name: 'BioRender',
    description: 'Scientific illustration software with AI illustration tools enabling researchers to create publication-grade biological figures in minutes.',
    category: 'Healthcare & Bio',
    subcategory: 'Scientific Illustration',
    website: 'https://biorender.com',
    pricing: 'Freemium',
    features: ['50,000+ biologically accurate icons', 'AI figure generator & layout assistant', 'Publication licensing', 'Team peer review'],
    tags: ['scientific-figures', 'biology', 'illustration', 'papers'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Insilico Medicine',
    description: 'Generative AI platform Pharma.AI discovering novel biological targets and synthesizing clinical drug candidates.',
    category: 'Healthcare & Bio',
    subcategory: 'Drug Discovery',
    website: 'https://insilico.com',
    pricing: 'Verify on official website',
    features: ['PandaOmics target discovery', 'Generative chemistry Chemistry42', 'Clinical trial prediction', 'First fully AI-designed drugs in trials'],
    tags: ['drug-discovery', 'pharma', 'biotech', 'chemistry'],
    platforms: ['Web'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },

  // ── Y. AI E-COMMERCE AND PRODUCT PHOTOGRAPHY ──
  {
    name: 'Pebblely',
    description: 'AI product photography studio transforming ordinary phone photos of products into professional, studio-lit marketing assets.',
    category: 'E-commerce',
    subcategory: 'Product Photography',
    website: 'https://pebblely.com',
    pricing: 'Freemium',
    features: ['AI lighting and shadow matching', 'Custom themed environments', 'Multiple aspect ratio generation', 'Shopify app integration'],
    tags: ['ecommerce', 'product-photo', 'marketing', 'shopify'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Flair AI',
    description: 'AI design tool for consumer packaged goods (CPG) generating high-end commercial photo shoots with flexible prop placement.',
    category: 'E-commerce',
    subcategory: 'CPG Photography',
    website: 'https://flair.ai',
    pricing: 'Freemium',
    features: ['Drag & drop prop placement', 'Scene lighting preservation', '3D rotation composition', 'High-res image upscaling'],
    tags: ['cpg', 'product-photography', 'commercials', 'branding'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Claid.ai',
    description: 'Automated image editing API and platform for marketplaces that standardizes backgrounds, fixes lighting, and upscales UGC photos.',
    category: 'E-commerce',
    subcategory: 'Marketplace Image Processing',
    website: 'https://claid.ai',
    pricing: 'Paid',
    features: ['Marketplace image standardization', 'Automated retouching API', 'Ultra-fast upscaling', 'Background replacement'],
    tags: ['api', 'marketplaces', 'ecommerce', 'automation'],
    platforms: ['Web', 'API'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Shopify Magic',
    description: 'Suite of free AI features integrated into Shopify that writes product descriptions, generates banner images, and automates marketing.',
    category: 'E-commerce',
    subcategory: 'Store Automation',
    website: 'https://shopify.com/magic',
    pricing: 'Free',
    features: ['One-click product descriptions', 'Instant background image generator', 'Sidekick merchant assistant', 'Email subject optimizer'],
    tags: ['shopify', 'ecommerce', 'store-owner', 'free'],
    platforms: ['Web', 'Shopify Admin'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Algolia',
    description: 'AI search and discovery engine for e-commerce providing semantic neural search, personalized ranking, and recommendations.',
    category: 'E-commerce',
    subcategory: 'Search & Recommendations',
    website: 'https://algolia.com',
    pricing: 'Freemium',
    features: ['Neural search with natural language', 'Dynamic re-ranking based on buyer intent', 'Real-time autocomplete', 'Personalized recommendations'],
    tags: ['search', 'ecommerce-search', 'recommendations', 'api'],
    platforms: ['API', 'Web'],
    skillLevel: 'Intermediate',
    rating: 4.8,
    lastVerified: '2025-10',
  },

  // ── Z. AI DIAGRAMS, MIND MAPS AND KNOWLEDGE MANAGEMENT ──
  {
    name: 'Whimsical AI',
    description: 'Visual workspace tool that generates mind maps, flowcharts, user journeys, and sticky note brainstorms using AI prompts.',
    category: 'Knowledge & Mind Maps',
    subcategory: 'Visual Mind Maps',
    website: 'https://whimsical.com',
    pricing: 'Freemium',
    features: ['Mind map node expansion', 'Text-to-flowchart builder', 'Wireframes & sticky notes', 'Real-time multiplayer'],
    tags: ['mind-maps', 'flowcharts', 'diagrams', 'ideation'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Miro AI',
    description: 'Visual collaboration whiteboard platform equipped with AI for clustering sticky notes, summarizing boards, and diagram generation.',
    category: 'Knowledge & Mind Maps',
    subcategory: 'Collaborative Whiteboard',
    website: 'https://miro.com/ai',
    pricing: 'Freemium',
    features: ['Sticky note thematic clustering', 'Prompt to flowchart and mind map', 'Retrospective board summarization', 'User story map builder'],
    tags: ['miro', 'whiteboard', 'brainstorming', 'agile'],
    platforms: ['Web', 'Windows', 'macOS', 'iOS', 'Android'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Lucidchart AI',
    description: 'Intelligent diagramming application that generates cloud architectures, sequence diagrams, and process flows from descriptions.',
    category: 'Knowledge & Mind Maps',
    subcategory: 'Architecture Diagramming',
    website: 'https://lucidchart.com',
    pricing: 'Freemium',
    features: ['Prompt-to-diagram generation', 'Automated cloud infrastructure import (AWS, Azure)', 'Collaborative canvas', 'Data linking to live spreadsheets'],
    tags: ['architecture', 'flowcharts', 'uml', 'cloud-diagrams'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Eraser',
    description: 'AI canvas built specifically for engineering teams that generates sequence diagrams, architecture flows, and markdown docs from code.',
    category: 'Knowledge & Mind Maps',
    subcategory: 'Engineering Diagrams',
    website: 'https://eraser.io',
    pricing: 'Freemium',
    features: ['Diagram-as-code syntax', 'Git repo to architecture diagram', 'Sequence diagrams generator', 'Collaborative canvas'],
    tags: ['engineers', 'diagram-as-code', 'architecture', 'github'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Mermaid Chart AI',
    description: 'Visual editor and AI assistant built on Mermaid.js for creating text-based sequence diagrams, flowcharts, and Gantt charts.',
    category: 'Knowledge & Mind Maps',
    subcategory: 'Code-Based Diagramming',
    website: 'https://mermaidchart.com',
    pricing: 'Freemium',
    features: ['Natural language to Mermaid code', 'Multi-user visual editor', 'VS Code & GitHub plugins', 'Live presentation mode'],
    tags: ['mermaid', 'diagram-as-code', 'markdown', 'developers'],
    platforms: ['Web', 'VS Code'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Obsidian AI',
    description: 'Local-first personal knowledge base and markdown second brain enhanced with community AI plugins, Smart Connections, and local embeddings.',
    category: 'Knowledge & Mind Maps',
    subcategory: 'Second Brain',
    website: 'https://obsidian.md',
    pricing: 'Freemium',
    features: ['Local markdown storage', 'Smart Connections semantic graph', 'Local or cloud LLM query', 'End-to-end encrypted sync'],
    tags: ['second-brain', 'pkm', 'local-first', 'privacy'],
    platforms: ['Windows', 'macOS', 'Linux', 'iOS', 'Android'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Mem',
    description: 'Self-organizing AI workspace that connects notes, emails, and meetings automatically without requiring folders or tags.',
    category: 'Knowledge & Mind Maps',
    subcategory: 'Self-Organizing Notes',
    website: 'https://mem.ai',
    pricing: 'Freemium',
    features: ['Folderless self-organization', 'Mem Chat across personal notes', 'Automatic related note links', 'Meeting audio capture'],
    tags: ['notes', 'knowledge', 'mem', 'ai-workspace'],
    platforms: ['Web', 'macOS', 'iOS'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Taskade AI',
    description: 'Unified AI workspace featuring dynamic mind maps, task lists, workflow automation agents, and team chat in a single tool.',
    category: 'Knowledge & Mind Maps',
    subcategory: 'Multi-View Workspace',
    website: 'https://taskade.com',
    pricing: 'Freemium',
    features: ['Custom AI agent teams', 'Mind map to task board switcher', 'Automated workflow triggers', 'Multi-player live canvas'],
    tags: ['taskade', 'mind-maps', 'project-management', 'agents'],
    platforms: ['Web', 'macOS', 'Windows', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },

  // ── SPECIALIZED DOMAINS: LEGAL, SCIENCE, ROBOTICS ──
  {
    name: 'Harvey AI',
    description: 'Domain-specific legal AI platform built with OpenAI for premier law firms to assist in contract analysis, litigation, and due diligence.',
    category: 'Legal & Compliance',
    subcategory: 'Legal Intelligence',
    website: 'https://harvey.ai',
    pricing: 'Verify on official website',
    features: ['Contract due diligence reviews', 'Legal research synthesis', 'Multi-jurisdictional analysis', 'Enterprise grade security & privacy'],
    tags: ['legal', 'law-firms', 'contracts', 'due-diligence'],
    platforms: ['Web'],
    skillLevel: 'Advanced',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Casetext CoCounsel',
    description: 'AI legal assistant by Thomson Reuters that searches case law, reviews deposition transcripts, and prepares legal research memos.',
    category: 'Legal & Compliance',
    subcategory: 'Legal Research',
    website: 'https://casetext.com',
    pricing: 'Verify on official website',
    features: ['Verified case law database citations', 'Deposition transcript search', 'Contract redlining assistant', 'Thomson Reuters backing'],
    tags: ['legal', 'case-law', 'litigation', 'attorneys'],
    platforms: ['Web'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Ironclad AI',
    description: 'Contract lifecycle management software utilizing AI to parse contract terms, detect non-standard clauses, and expedite negotiations.',
    category: 'Legal & Compliance',
    subcategory: 'Contract Lifecycle',
    website: 'https://ironcladapp.com',
    pricing: 'Verify on official website',
    features: ['AI clause anomaly detection', 'Automated contract redlines', 'Dynamic workflow routing', 'Repository search across all signed MSAs'],
    tags: ['contracts', 'clm', 'legal-tech', 'compliance'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Mathpix',
    description: 'AI OCR tool that converts images, screenshots, and PDFs of mathematical equations and scientific formulas into clean LaTeX and MathML.',
    category: 'Science & Engineering',
    subcategory: 'Math & Science OCR',
    website: 'https://mathpix.com',
    pricing: 'Freemium',
    features: ['Handwritten math OCR to LaTeX', 'Full chemistry and physics formula parsing', 'Snip desktop screenshot tool', 'Markdown scientific editor'],
    tags: ['math', 'latex', 'ocr', 'science'],
    platforms: ['Windows', 'macOS', 'Linux', 'iOS', 'Android'],
    skillLevel: 'All Levels',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'NVIDIA Isaac Sim',
    description: 'Extensible robotics simulation application and synthetic data generation tool built on NVIDIA Omniverse for testing autonomous robots.',
    category: 'Robotics & Computer Vision',
    subcategory: 'Robotics Simulation',
    website: 'https://developer.nvidia.com/isaac/sim',
    pricing: 'Freemium',
    features: ['PhysX photorealistic physics', 'Synthetic data generation for training CV', 'ROS and ROS 2 integration', 'Reinforcement learning for robot manipulators'],
    tags: ['robotics', 'nvidia', 'simulation', 'omniverse'],
    platforms: ['Linux', 'Windows'],
    skillLevel: 'Advanced',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
];
