// Part 7: Additional domain coverage for Finance, Health, E-Commerce, Career, Meetings, Legal & Science
export const toolsPart7 = [
  // ── MORE FINANCE & ACCOUNTING ──
  {
    name: 'QuickBooks AI',
    description: 'Intuit QuickBooks automated ledger with smart bookkeeping, invoice generation, expense categorization, and cash flow predictions.',
    category: 'Finance & Accounting',
    subcategory: 'SME Accounting',
    website: 'https://quickbooks.intuit.com',
    pricing: 'Verify on official website',
    features: ['Automated bank transaction sorting', 'Smart invoice reminders', 'Cash flow planner', 'Receipt scanning'],
    tags: ['accounting', 'quickbooks', 'small-business', 'invoices'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Xero AI',
    description: 'Cloud accounting platform with automated bank reconciliation, analytics, and intelligent document data capture.',
    category: 'Finance & Accounting',
    subcategory: 'Cloud Accounting',
    website: 'https://xero.com',
    pricing: 'Verify on official website',
    features: ['Automated bank reconciliation', 'Hubdoc receipt capture', 'Cash flow prediction', 'Payroll management'],
    tags: ['accounting', 'xero', 'bookkeeping', 'finance'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Datarails',
    description: 'FP&A platform for Excel users leveraging AI to automate financial consolidations, budgeting, and variance analysis.',
    category: 'Finance & Accounting',
    subcategory: 'FP&A Automation',
    website: 'https://datarails.com',
    pricing: 'Verify on official website',
    features: ['Native Excel modeling', 'Automated financial consolidation', 'Variance drill-down', 'FP&A Genius AI chat'],
    tags: ['fpa', 'excel', 'finance', 'cfo'],
    platforms: ['Web', 'Excel'],
    skillLevel: 'Advanced',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'BILL AI',
    description: 'Intelligent accounts payable and accounts receivable platform automating invoice entry and approvals for businesses.',
    category: 'Finance & Accounting',
    subcategory: 'AP & AR Automation',
    website: 'https://bill.com',
    pricing: 'Verify on official website',
    features: ['AI invoice data capture', 'Multi-level approval workflows', 'International wire payments', 'Accounting software sync'],
    tags: ['invoices', 'accounts-payable', 'payments', 'smb'],
    platforms: ['Web', 'Mobile'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Docyt',
    description: 'AI accounting automation software that runs real-time back-office bookkeeping and multi-entity reconciliation.',
    category: 'Finance & Accounting',
    subcategory: 'Automated Bookkeeping',
    website: 'https://docyt.com',
    pricing: 'Verify on official website',
    features: ['Continuous real-time bookkeeping', 'Multi-entity consolidation', 'Live revenue tracking', 'QuickBooks integration'],
    tags: ['bookkeeping', 'multi-entity', 'reconciliation', 'backoffice'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Numeric',
    description: 'Modern close management software helping accounting teams automate balance sheet reconciliations and variance checks.',
    category: 'Finance & Accounting',
    subcategory: 'Close Management',
    website: 'https://numeric.io',
    pricing: 'Verify on official website',
    features: ['AI balance sheet reconciliations', 'Month-end close checklist', 'ERP integrations', 'Variance explanations'],
    tags: ['month-end-close', 'reconciliations', 'cpa', 'accounting'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.8,
    lastVerified: '2025-10',
  },

  // ── MORE HEALTHCARE AND LIFE SCIENCES ──
  {
    name: 'Nabla',
    description: 'Ambient AI medical assistant generating clinical notes for doctors during consultations with high medical specialty accuracy.',
    category: 'Healthcare & Bio',
    subcategory: 'Clinical Documentation',
    website: 'https://nabla.com',
    pricing: 'Verify on official website',
    features: ['Real-time ambient consultation note generation', 'Customizable medical note templates', 'EHR integrations', 'HIPAA & GDPR compliance'],
    tags: ['medical-notes', 'physicians', 'ambient-ai', 'ehr'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Heidi Health',
    description: 'Free ambient AI medical scribe for clinicians, converting consultations into accurate clinical notes across 50+ specialties.',
    category: 'Healthcare & Bio',
    subcategory: 'AI Medical Scribe',
    website: 'https://heidihealth.com',
    pricing: 'Freemium',
    features: ['Zero cost starter tier', 'Custom clinician voice', 'Specialty specific documentation', 'Letter and referral drafting'],
    tags: ['medical-scribe', 'doctors', 'clinicians', 'healthcare'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Suki',
    description: 'Voice-enabled AI healthcare assistant helping clinicians create notes, dictate medical orders, and retrieve EHR patient info.',
    category: 'Healthcare & Bio',
    subcategory: 'Voice Clinical Assistant',
    website: 'https://suki.ai',
    pricing: 'Verify on official website',
    features: ['Voice-directed EHR navigation', 'Clinical note creation', 'ICD-10 code extraction', 'Bidirectional EHR sync'],
    tags: ['voice-assistant', 'ehr', 'doctors', 'hospitals'],
    platforms: ['iOS', 'Android', 'Web'],
    skillLevel: 'Advanced',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'DeepScribe',
    description: 'AI medical scribe utilizing medical-grade acoustic models to produce comprehensive documentation for oncology and complex care.',
    category: 'Healthcare & Bio',
    subcategory: 'Complex Care Scribe',
    website: 'https://deepscribe.ai',
    pricing: 'Verify on official website',
    features: ['Specialty care note generation', 'Context-aware medical models', 'EHR integration', 'Audit trail for clinicians'],
    tags: ['oncology', 'hospitals', 'medical-scribe', 'healthcare'],
    platforms: ['iOS', 'Web'],
    skillLevel: 'Advanced',
    rating: 4.7,
    lastVerified: '2025-10',
  },

  // ── MORE E-COMMERCE & PRODUCT PHOTOGRAPHY ──
  {
    name: 'Mokker AI',
    description: 'AI product photo studio turning transparent product cutouts into professional e-commerce product photos with realistic backdrops.',
    category: 'E-commerce',
    subcategory: 'Product Backdrops',
    website: 'https://mokker.ai',
    pricing: 'Freemium',
    features: ['Automated background generation', 'High-res image upscaling', 'Multiple template scenes', 'Batch processing'],
    tags: ['product-photos', 'backdrops', 'ecommerce', 'shopify'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Booth AI',
    description: 'Generative AI platform creating studio-quality commercial photography for brands from a simple reference image and text prompt.',
    category: 'E-commerce',
    subcategory: 'Commercial Photography',
    website: 'https://booth.ai',
    pricing: 'Paid',
    features: ['Prompt-directed photoshoots', 'High resolution 4K output', 'Clothing model placement', 'Brand catalog batch run'],
    tags: ['fashion', 'commercial-photo', 'retail', 'ecommerce'],
    platforms: ['Web'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },
  {
    name: 'Vmake',
    description: 'E-commerce visual suite for fashion brands, featuring AI fashion models, video quality enhancement, and background removal.',
    category: 'E-commerce',
    subcategory: 'Fashion Models',
    website: 'https://vmake.ai',
    pricing: 'Freemium',
    features: ['Virtual fashion models', 'Mannequin to live model conversion', 'Video background cleanup', 'E-commerce ad clips'],
    tags: ['fashion', 'mannequin', 'models', 'apparel'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Vue.ai',
    description: 'Enterprise retail AI platform offering computer vision product tagging, virtual model styling, and shopper personalization.',
    category: 'E-commerce',
    subcategory: 'Retail Intelligence',
    website: 'https://vue.ai',
    pricing: 'Contact',
    features: ['Automated visual catalog management', '3D on-model photography', 'Personalized style recommendations', 'Inventory intelligence'],
    tags: ['retail', 'apparel', 'catalog', 'personalization'],
    platforms: ['Web', 'API'],
    skillLevel: 'Advanced',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Constructor',
    description: 'AI-first product discovery platform using clickstream intent and revenue optimization for e-commerce search and browse.',
    category: 'E-commerce',
    subcategory: 'Discovery & Search',
    website: 'https://constructor.com',
    pricing: 'Contact',
    features: ['Revenue-optimizing search results', 'Conversational commerce assistant', 'Auto-generated merchant facets', 'Real-time personalization'],
    tags: ['search', 'merchandising', 'conversion', 'retail'],
    platforms: ['API', 'Web'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },

  // ── MORE CAREER, RESUME & INTERVIEWS ──
  {
    name: 'Huntr',
    description: 'All-in-one job search tracker, AI resume builder, and cover letter generator keeping every job application organized.',
    category: 'Career & Resume',
    subcategory: 'Application Tracker',
    website: 'https://huntr.co',
    pricing: 'Freemium',
    features: ['Visual job application kanban board', 'AI resume tailor per job post', 'Chrome job clipper', 'Interview schedule tracking'],
    tags: ['kanban', 'job-tracker', 'resume-tailor', 'career'],
    platforms: ['Web', 'Chrome Extension'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Simplify',
    description: 'Autofill job applications across thousands of company career portals with one click and get matched with relevant jobs.',
    category: 'Career & Resume',
    subcategory: 'Application Autofill',
    website: 'https://simplify.jobs',
    pricing: 'Free',
    features: ['One-click job application autofill', 'Personalized job recommendations', 'Application status tracking', 'Over 10M applications completed'],
    tags: ['autofill', 'job-search', 'free', 'productivity'],
    platforms: ['Chrome Extension', 'Web'],
    skillLevel: 'Beginner',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Huru',
    description: 'AI job interview preparation coach generating unlimited practice interviews and scoring your answers, tone, and delivery.',
    category: 'Career & Resume',
    subcategory: 'Interview Prep',
    website: 'https://huru.ai',
    pricing: 'Freemium',
    features: ['Over 20,000 interview questions', 'Immediate audio and video feedback', 'Custom question generator from job posts', 'Delivery confidence score'],
    tags: ['interviews', 'coaching', 'speaking', 'job-prep'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Exponent',
    description: 'Interview prep platform with AI mock interviews, system design guides, and peer practice for PM and software engineering roles.',
    category: 'Career & Resume',
    subcategory: 'Tech Interview Prep',
    website: 'https://tryexponent.com',
    pricing: 'Freemium',
    features: ['AI PM & SWE mock interviews', 'System design interview courses', 'Peer interview matching', 'Company-specific interview guides'],
    tags: ['tech-interviews', 'product-management', 'system-design', 'coding'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.8,
    lastVerified: '2025-10',
  },

  // ── MORE MEETINGS & TRANSCRIPTION ──
  {
    name: 'Avoma',
    description: 'AI meeting assistant for revenue teams that logs notes directly into CRM, analyzes conversation trends, and tracks action items.',
    category: 'Meeting & Notes',
    subcategory: 'Revenue Meeting Bot',
    website: 'https://avoma.com',
    pricing: 'Freemium',
    features: ['Automated CRM note logging', 'Conversation intelligence metrics', 'Collaborative meeting agenda editor', 'Speaker talk-time breakdown'],
    tags: ['sales-calls', 'crm', 'meetings', 'transcription'],
    platforms: ['Web'],
    skillLevel: 'Intermediate',
    rating: 4.6,
    lastVerified: '2025-10',
  },
  {
    name: 'Fellow',
    description: 'Meeting management platform with AI meeting agendas, transcription summaries, and 360-degree feedback for remote teams.',
    category: 'Meeting & Notes',
    subcategory: 'Meeting Management',
    website: 'https://fellow.app',
    pricing: 'Freemium',
    features: ['Collaborative meeting agendas', 'AI meeting recording & summary', 'Peer feedback workflows', 'Action item synchronization'],
    tags: ['agendas', 'meetings', 'remote-teams', 'one-on-ones'],
    platforms: ['Web', 'Desktop', 'Mobile'],
    skillLevel: 'Beginner',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Sembly AI',
    description: 'AI team member that attends meetings, records minutes, and creates clear meeting summaries and task lists automatically.',
    category: 'Meeting & Notes',
    subcategory: 'Meeting Minutes',
    website: 'https://sembly.ai',
    pricing: 'Freemium',
    features: ['Attends calls in your place', 'Proxy attendance mode', 'Automated meeting minutes', 'Task tracking and delegation'],
    tags: ['meeting-minutes', 'remote-work', 'zoom', 'teams'],
    platforms: ['Web', 'iOS', 'Android'],
    skillLevel: 'Beginner',
    rating: 4.5,
    lastVerified: '2025-10',
  },

  // ── MORE LEGAL, SCIENCE, ROBOTICS ──
  {
    name: 'Robin AI',
    description: 'AI contract assistant combining Anthropic Claude with legal specialist supervision to review and draft legal agreements.',
    category: 'Legal & Compliance',
    subcategory: 'Contract Copilot',
    website: 'https://robinai.com',
    pricing: 'Verify on official website',
    features: ['Contract copilot in Word', 'Clause suggestion library', 'NDA fast-track review', 'Human-in-the-loop legal assurance'],
    tags: ['legal', 'contracts', 'word-plugin', 'law-firms'],
    platforms: ['Web', 'Microsoft Word'],
    skillLevel: 'Intermediate',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Spellbook',
    description: 'AI legal software embedded in Microsoft Word that reviews contracts, suggests redlines, and drafts legal provisions.',
    category: 'Legal & Compliance',
    subcategory: 'Word Legal Copilot',
    website: 'https://spellbook.legal',
    pricing: 'Verify on official website',
    features: ['Direct Microsoft Word integration', 'Aggressive clause redlines', 'Missing clause detection', 'Deal negotiation notes'],
    tags: ['lawyers', 'contracts', 'word', 'redlines'],
    platforms: ['Microsoft Word', 'Web'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Ultralytics YOLO',
    description: 'State-of-the-art computer vision platform for real-time object detection, image segmentation, pose estimation, and tracking.',
    category: 'Robotics & Computer Vision',
    subcategory: 'Real-Time Vision Model',
    website: 'https://ultralytics.com',
    pricing: 'Open Source',
    features: ['YOLO11 real-time detection', 'Edge and mobile deployment', 'Instance segmentation', 'Pose and keypoint estimation'],
    tags: ['computer-vision', 'yolo', 'open-source', 'robotics'],
    isOpenSource: true,
    platforms: ['Python', 'C++', 'iOS', 'Android'],
    skillLevel: 'Intermediate',
    isFeatured: true,
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'OpenCV AI Kit',
    description: 'Spatial AI hardware and software platform providing stereo depth perception and on-device neural network computer vision inference.',
    category: 'Robotics & Computer Vision',
    subcategory: 'Spatial AI Vision',
    website: 'https://luxonis.com',
    pricing: 'Open Source',
    features: ['DepthAI spatial computer vision', 'On-device neural inference', 'Stereo depth tracking', 'ROS / ROS 2 integration'],
    tags: ['robotics', 'opencv', 'spatial-ai', 'depth-camera'],
    isOpenSource: true,
    platforms: ['Hardware', 'Python', 'C++'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'MATLAB AI',
    description: 'MathWorks AI platform for engineers integrating deep learning, reinforcement learning, and automated embedded code generation.',
    category: 'Science & Engineering',
    subcategory: 'Engineering & Simulation',
    website: 'https://mathworks.com/solutions/artificial-intelligence.html',
    pricing: 'Paid',
    features: ['Automated neural network training', 'Simulink digital twins', 'C/C++ code export', 'Signal processing AI'],
    tags: ['engineering', 'matlab', 'simulation', 'stem'],
    platforms: ['Windows', 'macOS', 'Linux'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'ChemDraw AI',
    description: 'Chemical drawing and molecular structure intelligence tool predicting NMR spectra, stoichiometry, and properties.',
    category: 'Science & Engineering',
    subcategory: 'Chemistry & Molecular',
    website: 'https://revvitysignals.com/products/chemdraw',
    pricing: 'Paid',
    features: ['Molecule-to-structure intelligence', '1H and 13C NMR prediction', 'Stoichiometry grid calculation', 'PubChem integration'],
    tags: ['chemistry', 'molecules', 'science', 'pharma'],
    platforms: ['Windows', 'macOS', 'Web'],
    skillLevel: 'Advanced',
    rating: 4.7,
    lastVerified: '2025-10',
  },
  {
    name: 'Ansys AI',
    description: 'Engineering simulation augmented with AI physics solvers for aerodynamic, thermal, and structural analysis in seconds.',
    category: 'Science & Engineering',
    subcategory: 'Physics Simulation',
    website: 'https://ansys.com',
    pricing: 'Paid',
    features: ['SimAI neural physics predictions', 'Ansys GPT technical copilot', 'Sub-second CFD estimation', 'CAD geometry optimization'],
    tags: ['physics', 'simulation', 'aerodynamics', 'cad'],
    platforms: ['Windows', 'Linux'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Schrödinger AI',
    description: 'Physics-based and machine learning computational platform accelerating molecular discovery for therapeutics and materials.',
    category: 'Science & Engineering',
    subcategory: 'Molecular Modeling',
    website: 'https://schrodinger.com',
    pricing: 'Paid',
    features: ['Free energy perturbation FEP+', 'Automated QSAR modeling', 'Materials science simulation', 'Active learning molecular screening'],
    tags: ['molecular-modeling', 'drug-discovery', 'biotech', 'chemistry'],
    platforms: ['Linux', 'Windows'],
    skillLevel: 'Advanced',
    rating: 4.9,
    lastVerified: '2025-10',
  },
  {
    name: 'Foxglove Studio',
    description: 'Open robotics visualization and debugging tool for autonomous vehicles, drones, and mobile robotics telemetry data.',
    category: 'Robotics & Computer Vision',
    subcategory: 'Robotics Visualization',
    website: 'https://foxglove.dev',
    pricing: 'Freemium',
    features: ['MCAP & ROS bag playback', '3D point cloud LiDAR rendering', 'Custom telemetry panel extensions', 'Collaborative robotics debugging'],
    tags: ['robotics', 'ros', 'lidar', 'autonomous-vehicles'],
    isOpenSource: true,
    platforms: ['Desktop', 'Web'],
    skillLevel: 'Advanced',
    rating: 4.8,
    lastVerified: '2025-10',
  },
  {
    name: 'Rokoko Vision',
    description: 'AI dual-camera motion capture platform tracking human body movement from webcam video into 3D animation rigs.',
    category: 'Robotics & Computer Vision',
    subcategory: 'Motion Tracking',
    website: 'https://rokoko.com/products/vision',
    pricing: 'Freemium',
    features: ['Dual-camera tracking', 'Real-time FBX streaming', 'Zero sensors required', 'Blender and Unreal live sync'],
    tags: ['mocap', 'cv', 'tracking', 'animation'],
    platforms: ['Web', 'Desktop'],
    skillLevel: 'Intermediate',
    rating: 4.7,
    lastVerified: '2025-10',
  },
];

